# Generated by Django 5.2.9 on 2026-03-09 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_display_name', models.CharField(max_length=150)),
                ('role_snapshot', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('web', 'Web'), ('api', 'API'), ('cron', 'Cron'), ('management_command', 'Management Command'), ('signal', 'Signal')], default='web', max_length=20)),
                ('action_category', models.CharField(choices=[('auth', 'Auth'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('approve', 'Approve'), ('reject', 'Reject'), ('export', 'Export'), ('email', 'Email'), ('system', 'System'), ('permission_denied', 'Permission Denied'), ('file_upload', 'File Upload'), ('search', 'Search'), ('bulk_action', 'Bulk Action')], max_length=50)),
                ('action_type', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=50)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('related_object_type', models.CharField(blank=True, max_length=100)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('url_path', models.CharField(blank=True, max_length=500)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('is_backfilled', models.BooleanField(default=False)),
                ('backfill_source', models.CharField(blank=True, max_length=100)),
                ('anonymized', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'date'], name='al_user_date_idx'), models.Index(fields=['date', 'action_category'], name='al_date_cat_idx'), models.Index(fields=['user', 'timestamp'], name='al_user_ts_idx'), models.Index(fields=['module', 'date'], name='al_module_date_idx'), models.Index(fields=['is_suspicious', 'date'], name='al_suspicious_idx')],
            },
        ),
    ]
