from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Convert activity_logs to partitioned table
            -- 1. Drop FK, indexes, and PK from existing table before renaming
            ALTER TABLE activity_logs DROP CONSTRAINT IF EXISTS activity_logs_user_id_60cbbbe3_fk_users_id;
            DROP INDEX IF EXISTS activity_logs_date_966217fb;
            DROP INDEX IF EXISTS activity_logs_timestamp_5301a5c7;
            DROP INDEX IF EXISTS activity_logs_user_id_60cbbbe3;
            DROP INDEX IF EXISTS al_date_cat_idx;
            DROP INDEX IF EXISTS al_module_date_idx;
            DROP INDEX IF EXISTS al_suspicious_idx;
            DROP INDEX IF EXISTS al_user_date_idx;
            DROP INDEX IF EXISTS al_user_ts_idx;
            ALTER TABLE activity_logs DROP CONSTRAINT IF EXISTS activity_logs_pkey;

            -- 2. Rename existing table
            ALTER TABLE activity_logs RENAME TO activity_logs_unpartitioned;

            -- 3. Create partitioned parent table with composite PK (id, timestamp)
            --    PostgreSQL requires the partition key in all unique constraints
            CREATE TABLE activity_logs (
                id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id bigint,
                user_display_name varchar(150) NOT NULL,
                role_snapshot varchar(50) NOT NULL,
                source varchar(20) NOT NULL,
                action_category varchar(50) NOT NULL,
                action_type varchar(100) NOT NULL,
                module varchar(50) NOT NULL,
                object_type varchar(100) NOT NULL,
                object_id integer,
                object_repr varchar(255) NOT NULL,
                related_object_type varchar(100) NOT NULL,
                related_object_id integer,
                description text NOT NULL,
                ip_address inet,
                user_agent varchar(500) NOT NULL,
                session_key varchar(40) NOT NULL,
                request_method varchar(10) NOT NULL,
                url_path varchar(500) NOT NULL,
                status_code integer,
                response_time_ms integer,
                extra_data jsonb NOT NULL,
                is_suspicious boolean NOT NULL,
                is_backfilled boolean NOT NULL,
                backfill_source varchar(100) NOT NULL,
                anonymized boolean NOT NULL,
                "timestamp" timestamptz NOT NULL,
                "date" date NOT NULL,
                PRIMARY KEY (id, "timestamp")
            ) PARTITION BY RANGE ("timestamp");

            -- 4. Create initial partitions (current month + next 2)
            CREATE TABLE activity_logs_2026_03
                PARTITION OF activity_logs
                FOR VALUES FROM ('2026-03-01 00:00:00+00') TO ('2026-04-01 00:00:00+00');

            CREATE TABLE activity_logs_2026_04
                PARTITION OF activity_logs
                FOR VALUES FROM ('2026-04-01 00:00:00+00') TO ('2026-05-01 00:00:00+00');

            CREATE TABLE activity_logs_2026_05
                PARTITION OF activity_logs
                FOR VALUES FROM ('2026-05-01 00:00:00+00') TO ('2026-06-01 00:00:00+00');

            -- 5. Recreate indexes on partitioned table
            CREATE INDEX al_user_date_idx ON activity_logs (user_id, "date");
            CREATE INDEX al_date_cat_idx ON activity_logs ("date", action_category);
            CREATE INDEX al_user_ts_idx ON activity_logs (user_id, "timestamp");
            CREATE INDEX al_module_date_idx ON activity_logs (module, "date");
            CREATE INDEX al_suspicious_idx ON activity_logs (is_suspicious, "date");
            CREATE INDEX ON activity_logs ("timestamp");
            CREATE INDEX ON activity_logs ("date");

            -- 6. Add FK constraint
            ALTER TABLE activity_logs ADD CONSTRAINT activity_logs_user_id_fk
                FOREIGN KEY (user_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED;

            -- 7. Migrate any existing data (explicit column list to handle order differences)
            INSERT INTO activity_logs (
                id, user_display_name, role_snapshot, source, action_category,
                action_type, module, object_type, object_id, object_repr,
                related_object_type, related_object_id, description, ip_address,
                user_agent, session_key, request_method, url_path, status_code,
                response_time_ms, extra_data, is_suspicious, is_backfilled,
                backfill_source, anonymized, "timestamp", "date", user_id
            )
            SELECT
                id, user_display_name, role_snapshot, source, action_category,
                action_type, module, object_type, object_id, object_repr,
                related_object_type, related_object_id, description, ip_address,
                user_agent, session_key, request_method, url_path, status_code,
                response_time_ms, extra_data, is_suspicious, is_backfilled,
                backfill_source, anonymized, "timestamp", "date", user_id
            FROM activity_logs_unpartitioned;

            -- 8. Drop old table
            DROP TABLE activity_logs_unpartitioned;
            """,
            reverse_sql="""
            -- Reverse: merge partitions back to single table (data preserved)
            CREATE TABLE activity_logs_plain (LIKE activity_logs INCLUDING ALL);
            INSERT INTO activity_logs_plain SELECT * FROM activity_logs;
            DROP TABLE activity_logs CASCADE;
            ALTER TABLE activity_logs_plain RENAME TO activity_logs;
            """,
        ),
    ]
