# Generated by Django 5.2.9 on 2026-03-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0002_partition_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='object_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='related_object_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
