# Generated by Django 5.2.11 on 2026-03-16 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApolloCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apollo_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "created_at_remote",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("updated_at_remote", models.DateTimeField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at_remote", "-id"],
                "indexes": [
                    models.Index(fields=["name"], name="apollo_apol_name_bc264c_idx"),
                    models.Index(
                        fields=["-created_at_remote"],
                        name="apollo_apol_created_1a7c0c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ApolloMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apollo_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                ("linkedin_url", models.URLField(blank=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("subject", models.TextField(blank=True)),
                ("num_opens", models.PositiveIntegerField(default=0)),
                ("num_clicks", models.PositiveIntegerField(default=0)),
                ("replied", models.BooleanField(db_index=True, default=False)),
                ("status", models.CharField(blank=True, db_index=True, max_length=100)),
                ("email_status", models.CharField(blank=True, max_length=100)),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_opened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lead_category",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("raw_message", models.JSONField(blank=True, default=dict)),
                ("raw_activity", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="apollo.apollocampaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["campaign", "-sent_at"],
                        name="apollo_apol_campaig_1a9d12_idx",
                    ),
                    models.Index(
                        fields=["lead_category", "-sent_at"],
                        name="apollo_apol_lead_ca_6934fd_idx",
                    ),
                    models.Index(
                        fields=["status", "-sent_at"],
                        name="apollo_apol_status_3c2759_idx",
                    ),
                ],
            },
        ),
    ]
