# Generated by Django 5.2.11 on 2026-03-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apollo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApolloSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_key",
                    models.CharField(default="historical", max_length=50, unique=True),
                ),
                ("start_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "start_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("end_year", models.PositiveIntegerField(blank=True, null=True)),
                ("end_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("c_year", models.PositiveIntegerField(blank=True, null=True)),
                ("c_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("c_camp_idx", models.PositiveIntegerField(default=0)),
                ("c_page", models.PositiveIntegerField(default=1)),
                ("is_complete", models.BooleanField(default=False)),
                ("last_checkpoint_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("last_api_calls", models.PositiveIntegerField(default=0)),
                ("total_messages_synced", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Apollo Sync State",
                "verbose_name_plural": "Apollo Sync State",
            },
        ),
    ]
