# Generated by Django 5.2.11 on 2026-03-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0002_apollosyncstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apollomessage',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
