# Generated by Django 5.2.7 on 2025-10-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('city_code', models.CharField(max_length=3, unique=True)),
                ('state_code', models.CharField(max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'city_codes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GstState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=2, unique=True)),
                ('state_name', models.CharField(max_length=50)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gst_states',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('state_code', models.CharField(max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'locations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectCode',
            fields=[
                ('project_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('series_type', models.CharField(choices=[('WAAS', 'Warehouse as a Service'), ('SAAS', 'SaaS Only Client'), ('GW', 'Internal Use')], max_length=10)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('project_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('warehouse_code', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('project_status', models.CharField(choices=[('Operation Not Started', 'Operation Not Started'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Operation Not Started', max_length=50)),
                ('sales_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('operation_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('backup_coordinator', models.CharField(blank=True, max_length=100, null=True)),
                ('operation_start_date', models.DateField(blank=True, null=True)),
                ('billing_start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_codes',
                'ordering': ['client_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VendorWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(max_length=50, unique=True)),
                ('vendor_code', models.CharField(max_length=20)),
                ('vendor_name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=2)),
                ('city_code', models.CharField(max_length=3)),
                ('owner_type', models.CharField(choices=[('1PL', '1PL - Own'), ('3PL', '3PL - Third Party')], max_length=3)),
                ('facility_type', models.CharField(choices=[('WH', 'Warehouse'), ('DC', 'Distribution Center'), ('YL', 'Yard')], max_length=2)),
                ('digipin', models.CharField(max_length=8)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('sequence_no', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendor_warehouses',
                'managed': True,
            },
        ),
    ]
