# Generated by Django 5.2.7 on 2025-10-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcode',
            options={'managed': True, 'ordering': ['client_name']},
        ),
    ]
