# Generated by Django 5.2.7 on 2025-10-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_operations_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcode',
            name='billing_unit',
            field=models.CharField(blank=True, choices=[('sqft', 'Square Feet'), ('pallet', 'Pallet'), ('lumpsum', 'Lumpsum')], help_text='How this project measures space utilization', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='projectcode',
            name='minimum_billable_pallets',
            field=models.IntegerField(blank=True, help_text='Minimum billable pallets (reference only)', null=True),
        ),
        migrations.AddField(
            model_name='projectcode',
            name='minimum_billable_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum billable area in square feet (reference only)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='projectcode',
            name='mis_status',
            field=models.CharField(blank=True, choices=[('mis_daily', 'MIS Daily'), ('mis_weekly', 'MIS Weekly'), ('mis_monthly', 'MIS Monthly'), ('inciflo', 'Inciflo'), ('mis_not_required', 'MIS Not Required')], max_length=20, null=True, verbose_name='MIS Status'),
        ),
        migrations.AddField(
            model_name='projectcode',
            name='operation_mode',
            field=models.CharField(blank=True, choices=[('auto_mode', 'Auto Mode'), ('data_sharing', 'Data Sharing'), ('active_engagement', 'Active Engagement')], max_length=20, null=True, verbose_name='Operation Mode'),
        ),
    ]
