# Generated by Django 5.2.7 on 2025-11-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectcode_billing_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcode',
            options={'managed': True, 'ordering': ['code']},
        ),
    ]
