# Generated by Django 5.2.7 on 2025-11-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectcode_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcode',
            old_name='operation_manager',
            new_name='operation_coordinator',
        ),
    ]
