# Generated by Django 5.2.7 on 2025-11-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_operation_manager_to_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcode',
            name='notice_period_start_date',
            field=models.DateField(blank=True, help_text='Date when notice period started', null=True),
        ),
        migrations.AlterField(
            model_name='projectcode',
            name='project_status',
            field=models.CharField(choices=[('Operation Not Started', 'Operation Not Started'), ('Active', 'Active'), ('Notice Period', 'Notice Period'), ('Inactive', 'Inactive')], default='Operation Not Started', max_length=50),
        ),
    ]
