# Generated by Django 5.2.7 on 2025-11-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_add_notice_period_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcode',
            name='notice_period_duration',
            field=models.IntegerField(blank=True, choices=[(15, '15 Days'), (30, '1 Month (30 Days)'), (60, '2 Months (60 Days)'), (90, '3 Months (90 Days)')], help_text='Duration of notice period in days', null=True),
        ),
        migrations.AddField(
            model_name='projectcode',
            name='notice_period_end_date',
            field=models.DateField(blank=True, help_text='Auto-calculated end date of notice period', null=True),
        ),
    ]
