# Generated by Django 5.2.7 on 2025-11-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_add_notice_period_duration_and_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcode',
            name='operation_start_date',
        ),
    ]
