# Generated by Django 5.2.7 on 2025-11-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_projectcode_operation_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citycode',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gststate',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vendorwarehouse',
            options={'managed': False},
        ),
    ]
