# Generated by Django 5.2.7 on 2025-12-08 12:54
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0010_alter_citycode_options_alter_gststate_options_and_more'),
    ]
    
    operations = [
        # Drop the old table entirely (safe - new schema coming in 0012)
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS vendor_warehouses CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Then remove model from Django state
        migrations.DeleteModel(
            name='VendorWarehouse',
        ),
    ]
