# Generated by Django 5.2.7 on 2025-12-08 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_clientcard_systemsettings_vendorcard_clientcontact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcode',
            name='client_card',
            field=models.ForeignKey(blank=True, db_column='client_card_code', help_text='Link to Client Card (master data) - auto-fills client_name', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.clientcard'),
        ),
        migrations.AddField(
            model_name='projectcode',
            name='vendor_warehouse',
            field=models.ForeignKey(blank=True, db_column='vendor_warehouse_code', help_text='Link to Vendor Warehouse (master data) - auto-fills vendor_name, warehouse_code, location', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.vendorwarehouse'),
        ),
    ]
