# Generated by Django 5.2.7 on 2025-12-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectcode_client_card_projectcode_vendor_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='client_contact_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='vendor_contact_department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
