# Generated by Django 5.2.7 on 2025-12-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_clientcontact_client_contact_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['state', 'city', 'location'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
