# Generated by Django 5.2.7 on 2025-12-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_location_unique_together_location_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcode',
            name='billing_unit',
            field=models.CharField(blank=True, choices=[('sqft', 'Square Feet'), ('pallet', 'Pallet'), ('unit', 'Unit'), ('order', 'Order'), ('lumpsum', 'Lumpsum')], help_text='How this project measures space utilization', max_length=10, null=True),
        ),
    ]
