# Generated by Django 5.2.7 on 2025-12-16 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_projectcode_billing_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorwarehouse',
            unique_together=set(),
        ),
        # CRITICAL FIX: Use RunSQL with CASCADE to handle FK dependencies
        migrations.RunSQL(
            sql="""
            -- Drop old primary key constraint (CASCADE updates dependent FKs)
            ALTER TABLE vendor_warehouses DROP CONSTRAINT IF EXISTS vendor_warehouses_pkey CASCADE;
            
            -- Add new auto-increment id as primary key
            ALTER TABLE vendor_warehouses ADD COLUMN id BIGSERIAL PRIMARY KEY;
            
            -- Make warehouse_code unique but not primary
            ALTER TABLE vendor_warehouses ADD CONSTRAINT vendor_warehouses_warehouse_code_key UNIQUE (warehouse_code);
            """,
            reverse_sql="""
            -- Reverse: restore warehouse_code as PK
            ALTER TABLE vendor_warehouses DROP CONSTRAINT IF EXISTS vendor_warehouses_warehouse_code_key;
            ALTER TABLE vendor_warehouses DROP COLUMN IF EXISTS id CASCADE;
            ALTER TABLE vendor_warehouses ADD PRIMARY KEY (warehouse_code);
            """,
        ),
        migrations.AddField(
            model_name='vendorwarehouse',
            name='warehouse_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorwarehouse',
            name='warehouse_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='vendorwarehouse',
            name='warehouse_owner_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendorwarehouse',
            name='warehouse_owner_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vendorwarehouse',
            name='warehouse_pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='vendorwarehouse',
            name='warehouse_space_available',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectcode',
            name='mis_status',
            field=models.CharField(blank=True, choices=[('mis_daily', 'MIS Daily'), ('mis_weekly', 'MIS Weekly'), ('mis_monthly', 'MIS Monthly'), ('inciflo', 'Inciflo'), ('mis_automode', 'MIS Automode'), ('mis_not_required', 'MIS Not Required')], max_length=20, null=True, verbose_name='MIS Status'),
        ),
        migrations.AlterField(
            model_name='projectcode',
            name='vendor_warehouse',
            field=models.ForeignKey(blank=True, db_column='vendor_warehouse_code', help_text='Link to Vendor Warehouse (master data) - auto-fills vendor_name, warehouse_code, location', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.vendorwarehouse', to_field='warehouse_code'),
        ),
        migrations.AlterField(
            model_name='vendorwarehouse',
            name='vendor_code',
            field=models.ForeignKey(db_column='vendor_code', on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='projects.vendorcard'),
        ),
        migrations.AlterField(
            model_name='vendorwarehousedocument',
            name='warehouse_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.vendorwarehouse', to_field='warehouse_code'),
        ),
        migrations.AlterField(
            model_name='warehousecontact',
            name='warehouse_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='projects.vendorwarehouse', to_field='warehouse_code'),
        ),
        migrations.AlterModelTable(
            name='clientcard',
            table='client_cards',
        ),
        migrations.RemoveField(
            model_name='vendorwarehouse',
            name='warehouse_city_code',
        ),
        migrations.RemoveField(
            model_name='vendorwarehouse',
            name='warehouse_city_name',
        ),
        migrations.RemoveField(
            model_name='vendorwarehouse',
            name='warehouse_name',
        ),
        migrations.RemoveField(
            model_name='vendorwarehouse',
            name='warehouse_sequence_number',
        ),
        migrations.RemoveField(
            model_name='vendorwarehouse',
            name='warehouse_state_code',
        ),
        migrations.RemoveField(
            model_name='vendorwarehouse',
            name='warehouse_state_name',
        ),
    ]