# Generated by Django on YYYY-MM-DD HH:MM

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0018_alter_vendorwarehouse_unique_together_and_more'),
    ]

    operations = [
        # Create UnusedProjectId table
        migrations.CreateModel(
            name='UnusedProjectId',
            fields=[
                ('project_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Project ID')),
                ('was_intended_for', models.CharField(help_text='Description of intended use', max_length=200, verbose_name='Intended For')),
                ('intended_series', models.CharField(help_text='WAAS/SAAS/GW', max_length=10, verbose_name='Intended Series')),
                ('merged_into', models.CharField(blank=True, help_text='Project ID this was merged into', max_length=20, null=True, verbose_name='Merged Into')),
                ('created_at', models.DateTimeField(help_text='When TEMP project was created', verbose_name='Created At')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, help_text='When it was deleted/merged', verbose_name='Deleted At')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('deleted_by', models.ForeignKey(
                    null=True, 
                    on_delete=django.db.models.deletion.SET_NULL, 
                    related_name='deleted_projects', 
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Deleted By'
                )),
            ],
            options={
                'verbose_name': 'Unused Project ID',
                'verbose_name_plural': 'Unused Project IDs',
                'db_table': 'unused_project_ids',
                'ordering': ['-deleted_at'],
            },
        ),
        
        # Create ProjectNameChangeLog table
        migrations.CreateModel(
            name='ProjectNameChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_client_name', models.CharField(max_length=100, verbose_name='Old Client Name')),
                ('new_client_name', models.CharField(max_length=100, verbose_name='New Client Name')),
                ('old_project_code', models.CharField(max_length=255, verbose_name='Old Project Code')),
                ('new_project_code', models.CharField(max_length=255, verbose_name='New Project Code')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('reason', models.TextField(blank=True, help_text='Reason for name change (e.g., client rebrand)', verbose_name='Reason')),
                ('changed_by', models.ForeignKey(
                    null=True, 
                    on_delete=django.db.models.deletion.SET_NULL, 
                    related_name='project_name_changes', 
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Changed By'
                )),
                ('project', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='name_changes', 
                    to='projects.projectcode',
                    verbose_name='Project'
                )),
            ],
            options={
                'verbose_name': 'Project Name Change',
                'verbose_name_plural': 'Project Name Changes',
                'db_table': 'project_name_change_logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]