# Generated by Django 5.2.7 on 2025-12-20 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_add_temp_project_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectnamechangelog',
            options={'ordering': ['-changed_at']},
        ),
        migrations.AlterModelOptions(
            name='unusedprojectid',
            options={'ordering': ['-deleted_at']},
        ),
        migrations.AlterField(
            model_name='projectnamechangelog',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectnamechangelog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectnamechangelog',
            name='new_client_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectnamechangelog',
            name='new_project_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectnamechangelog',
            name='old_client_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectnamechangelog',
            name='old_project_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectnamechangelog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_changes', to='projects.projectcode'),
        ),
        migrations.AlterField(
            model_name='projectnamechangelog',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='unusedprojectid',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='unusedprojectid',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unusedprojectid',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unusedprojectid',
            name='intended_series',
            field=models.CharField(help_text='WAAS/SAAS/GW', max_length=10),
        ),
        migrations.AlterField(
            model_name='unusedprojectid',
            name='merged_into',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unusedprojectid',
            name='project_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unusedprojectid',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='unusedprojectid',
            name='was_intended_for',
            field=models.CharField(max_length=200),
        ),
    ]
