# Generated by Django 5.2.7 on 2025-12-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_convert_documents_to_filefields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorwarehousedocument',
            name='warehouse_owner_agreements',
            field=models.JSONField(blank=True, default=list, help_text='Multiple owner agreement files (stored as list of file paths)'),
        ),
    ]
