# Generated by Django 5.2.7 on 2025-12-22 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_vendorwarehousedocument_warehouse_owner_agreements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='documents', serialize=False, to='projects.projectcode')),
                ('project_agreement', models.FileField(blank=True, null=True, upload_to='project_documents/%Y/%m/', verbose_name='Main Agreement')),
                ('project_addendum_vendor', models.FileField(blank=True, null=True, upload_to='project_documents/%Y/%m/', verbose_name='Addendum (Vendor Commercial)')),
                ('project_addendum_client', models.FileField(blank=True, null=True, upload_to='project_documents/%Y/%m/', verbose_name='Addendum (Client)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Document',
                'verbose_name_plural': 'Project Documents',
                'db_table': 'project_documents',
            },
        ),
    ]
