# Generated by Django 5.2.7 on 2025-12-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_projectdocument'),
    ]

    operations = [
        # No-op: These changes were already applied via RunSQL in migration 0018
        # This migration exists only to sync Django's model state with the database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='vendorwarehouse',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='vendorwarehouse',
                    name='warehouse_code',
                    field=models.CharField(editable=False, max_length=30, unique=True),
                ),
            ],
            database_operations=[
                # Empty - database already has these changes from migration 0018
            ],
        ),
    ]