# Generated by Django 5.2.7 on 2025-12-27 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_vendorwarehouse_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorwarehouse',
            name='warehouse_latitude',
        ),
        migrations.RemoveField(
            model_name='vendorwarehouse',
            name='warehouse_longitude',
        ),
        migrations.RemoveField(
            model_name='vendorwarehouse',
            name='warehouse_space_available',
        ),
        migrations.AddField(
            model_name='vendorwarehouse',
            name='forklift_available',
            field=models.BooleanField(default=False, help_text='Check if forklift is available at this warehouse', verbose_name='Forklift Available'),
        ),
        migrations.AddField(
            model_name='vendorwarehouse',
            name='google_map_location',
            field=models.URLField(blank=True, help_text='Google Maps URL to warehouse location', max_length=500, null=True, verbose_name='Google Maps Location'),
        ),
        migrations.AddField(
            model_name='vendorwarehouse',
            name='warehouse_available_space_sqft',
            field=models.IntegerField(blank=True, help_text='Currently available warehouse space in square feet', null=True, verbose_name='Available Space (sq ft)'),
        ),
        migrations.CreateModel(
            name='WarehousePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload warehouse photos (JPG, PNG, PDF, PPT)', upload_to='warehouse_photos/%Y/%m/', verbose_name='Photo/Document')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('ppt', 'PowerPoint')], editable=False, max_length=10, verbose_name='File Type')),
                ('caption', models.CharField(blank=True, help_text='Optional description of the photo', max_length=200, null=True, verbose_name='Caption')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('warehouse_code', models.ForeignKey(db_column='warehouse_code', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projects.vendorwarehouse', to_field='warehouse_code', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Photo',
                'verbose_name_plural': 'Warehouse Photos',
                'db_table': 'warehouse_photos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
