# Generated by Django 5.2.7 on 2026-01-05 12:24
# Fixed: shared tables (vendor_warehouses, locations, etc.) are now owned by the
# supply app. RemoveField and DeleteModel operations must be state-only so they
# don't DROP tables/columns that supply depends on.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown_master_data', '0001_initial'),
        ('operations', '0033_alter_agreementrenewallog_options_and_more'),
        ('projects', '0025_update_vendor_warehouse_fields'),
        ('supply', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- New model (not shared) ---
        migrations.CreateModel(
            name='ProjectCodeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=20)),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_code_change_logs',
                'ordering': ['-changed_at'],
            },
        ),

        # --- State-only: remove FK fields from shared models (tables now owned by supply) ---
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='location',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='vendorwarehouse',
                    name='warehouse_location',
                ),
                migrations.RemoveField(
                    model_name='vendorwarehousedocument',
                    name='vendor_code',
                ),
                migrations.RemoveField(
                    model_name='vendorcontact',
                    name='vendor_code',
                ),
                migrations.RemoveField(
                    model_name='vendorwarehouse',
                    name='vendor_code',
                ),
                migrations.RemoveField(
                    model_name='warehousephoto',
                    name='warehouse_code',
                ),
            ],
            database_operations=[],
        ),

        # --- ProjectCode FK: point to supply.vendorwarehouse (projectcode table, not shared) ---
        migrations.AlterField(
            model_name='projectcode',
            name='vendor_warehouse',
            field=models.ForeignKey(blank=True, db_column='vendor_warehouse_code', help_text='Link to Vendor Warehouse (master data) - auto-fills vendor_name, warehouse_code, location', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='supply.vendorwarehouse', to_field='warehouse_code'),
        ),

        # --- State-only: remove remaining FK fields from shared models ---
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='vendorwarehousedocument',
                    name='warehouse_code',
                ),
                migrations.RemoveField(
                    model_name='warehousecontact',
                    name='warehouse_code',
                ),
                migrations.RemoveField(
                    model_name='vendorwarehousedocument',
                    name='warehouse_doc_uploaded_by',
                ),
                migrations.RemoveField(
                    model_name='warehousephoto',
                    name='uploaded_by',
                ),
            ],
            database_operations=[],
        ),

        # --- State-only: remove shared models from projects app (supply now owns these tables) ---
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='CityCode',
                ),
            ],
            database_operations=[],
        ),

        # --- ProjectCode billing_unit FK (projectcode table, not shared) ---
        migrations.AlterField(
            model_name='projectcode',
            name='billing_unit',
            field=models.ForeignKey(db_column='billing_unit', default='sqft', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.billingunit'),
        ),

        # --- State-only: delete remaining shared models ---
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Location',
                ),
                migrations.DeleteModel(
                    name='VendorContact',
                ),
                migrations.DeleteModel(
                    name='VendorCard',
                ),
                migrations.DeleteModel(
                    name='VendorWarehouse',
                ),
                migrations.DeleteModel(
                    name='WarehouseContact',
                ),
                migrations.DeleteModel(
                    name='VendorWarehouseDocument',
                ),
                migrations.DeleteModel(
                    name='WarehousePhoto',
                ),
            ],
            database_operations=[],
        ),

        # --- Indexes on new model (not shared) ---
        migrations.AddIndex(
            model_name='projectcodechangelog',
            index=models.Index(fields=['project_id', '-changed_at'], name='project_cod_project_cdd74f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcodechangelog',
            index=models.Index(fields=['changed_by', '-changed_at'], name='project_cod_changed_16eef3_idx'),
        ),
    ]
