# Generated by Django 5.2.7 on 2026-01-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_alter_clientcard_client_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='project_handover',
            field=models.FileField(blank=True, null=True, upload_to='project_documents/%Y/%m/', verbose_name='Handover Document'),
        ),
    ]
