# Generated by Django 5.2.7 on 2026-01-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_add_handover_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='client_contact_department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
