# Generated by Django 5.2.7 on 2026-02-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_alter_clientcontact_client_contact_department'),
    ]

    operations = [
        # First, drop the check constraint
        migrations.RunSQL(
            sql='ALTER TABLE client_contacts DROP CONSTRAINT IF EXISTS client_contacts_dept_check;',
            reverse_sql='ALTER TABLE client_contacts ADD CONSTRAINT client_contacts_dept_check CHECK (client_contact_department IN (\'operations\', \'accounts\', \'procurement\', \'management\'));'
        ),
        # Then alter the field to allow null
        migrations.AlterField(
            model_name='clientcontact',
            name='client_contact_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
