# Generated by Django 5.2.7 on 2026-02-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_remove_department_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcode',
            name='billing_start_date',
        ),
    ]
