# Generated by Django 5.2.9 on 2026-02-16 05:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_billing_start_date_from_projectcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotation_id', models.AutoField(primary_key=True, serialize=False)),
                ('quotation_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('client_name', models.CharField(help_text='Contact person name', max_length=255)),
                ('client_company', models.CharField(help_text='Company/organization name', max_length=255)),
                ('client_email', models.EmailField(help_text='Primary email for quotation delivery', max_length=254)),
                ('client_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('client_address', models.TextField(blank=True, help_text='Full address for quotation')),
                ('client_gst_number', models.CharField(blank=True, help_text='GST number (optional)', max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('validity_period', models.IntegerField(default=30, help_text='Validity in days (from QuotationSettings default)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='GST rate in percentage (from QuotationSettings default)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotation',
                'ordering': ['-date', '-quotation_id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationAudit',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('docx_generated', 'DOCX Generated'), ('pdf_generated', 'PDF Generated'), ('email_sent', 'Email Sent'), ('status_changed', 'Status Changed'), ('downloaded', 'Downloaded')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('additional_metadata', models.JSONField(blank=True, default=dict)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='projects.quotation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotation_audit',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='projects.quotation')),
            ],
            options={
                'db_table': 'quotation_location',
                'ordering': ['quotation', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_description', models.CharField(choices=[('storage', 'Storage Charges'), ('handling', 'Handling Charges'), ('wms', 'WMS Charges'), ('packing', 'Packing Charges'), ('labour', 'Labour Charges'), ('transportation', 'Transportation'), ('other', 'Other')], max_length=50)),
                ('custom_description', models.CharField(blank=True, max_length=255)),
                ('unit_cost', models.CharField(help_text="Enter number or 'at actual'", max_length=50)),
                ('quantity', models.CharField(default='1', help_text="Enter number or 'as applicable'", max_length=50)),
                ('storage_unit_type', models.CharField(blank=True, choices=[('pallet', 'Per Pallet'), ('sqft', 'Per Sq. Ft.'), ('cbm', 'Per CBM'), ('mt', 'Per MT'), ('unit', 'Per Unit')], max_length=20, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.quotationlocation')),
            ],
            options={
                'db_table': 'quotation_item',
                'ordering': ['location', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuotationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_docs_template_url', models.URLField(blank=True, help_text='Full Google Docs URL (e.g., https://docs.google.com/document/d/DOCUMENT_ID/edit)')),
                ('google_docs_template_id', models.CharField(blank=True, editable=False, help_text='Auto-extracted from URL', max_length=255)),
                ('google_service_account_file', models.FileField(blank=True, help_text='Upload service account JSON key file', null=True, upload_to='quotations/credentials/')),
                ('default_gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Default GST rate in percentage', max_digits=5)),
                ('default_validity_days', models.IntegerField(default=30, help_text='Default quotation validity in days')),
                ('email_subject_template', models.CharField(default='Quotation {quotation_number} - {client_company}', help_text='Use {quotation_number}, {client_company}, {date} as placeholders', max_length=500)),
                ('email_body_template', models.TextField(default="Dear {client_name},\n\nPlease find attached quotation {quotation_number} for your review.\n\nThis quotation is valid until {validity_date}.\n\nIf you have any questions, please don't hesitate to contact us.\n\nBest regards,\n{created_by_name}", help_text='Use {client_name}, {quotation_number}, {validity_date}, {created_by_name} as placeholders')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quotation Settings',
                'verbose_name_plural': 'Quotation Settings',
                'db_table': 'quotation_settings',
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['client_company', 'status'], name='quotation_client__e211e1_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['created_by'], name='quotation_created_08d161_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['-date'], name='quotation_date_10eaa3_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['client_email'], name='quotation_client__5b097e_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationaudit',
            index=models.Index(fields=['quotation', '-timestamp'], name='quotation_a_quotati_71dace_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationaudit',
            index=models.Index(fields=['user'], name='quotation_a_user_id_986fbd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quotationlocation',
            unique_together={('quotation', 'order')},
        ),
    ]
