# Generated by Django 5.2.9 on 2026-02-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_quotation_quotationaudit_quotationlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='billing_address',
            field=models.TextField(blank=True, help_text='Billing address'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='company_tagline',
            field=models.CharField(default='Comprehensive Warehousing & Logistics Services', help_text='Company tagline for quotation header', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='contract_terms',
            field=models.TextField(blank=True, help_text='Contract tenure terms (uses default from settings if empty)'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='for_godamwale_signatory',
            field=models.CharField(default='Annand Aryamane [9820504595]', help_text='Godamwale authorized signatory', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='liability_terms',
            field=models.TextField(blank=True, help_text='Liability & compliance terms (uses default from settings if empty)'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.TextField(blank=True, help_text='Payment terms (uses default from settings if empty)'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='poc_phone',
            field=models.CharField(blank=True, help_text='Point of contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='point_of_contact',
            field=models.CharField(blank=True, help_text='Point of contact name', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='scope_of_service',
            field=models.JSONField(blank=True, default=list, help_text='Selected services from predefined options'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='Shipping address (leave blank if same as billing)'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sla_terms',
            field=models.TextField(blank=True, help_text='SLA & service commitments (uses default from settings if empty)'),
        ),
        migrations.AddField(
            model_name='quotationsettings',
            name='default_contract_terms',
            field=models.TextField(default='• Minimum contract period: 3 months (To be discussed)\n• Auto-renewal for subsequent periods unless 30-day notice provided\n• Rates subject to annual revision based on market conditions', help_text='Default contract tenure terms'),
        ),
        migrations.AddField(
            model_name='quotationsettings',
            name='default_liability_terms',
            field=models.TextField(default='• Insurance coverage for goods in transit and storage (up to declared value) to be taken by customer\n• Compliance with GST, FSSAI, and other applicable regulations to be taken by customer\n• Liability limited to two months of rent or replacement value of damaged/lost goods, whichever is lesser\n• Force majeure clause applicable for natural disasters and unforeseen events', help_text='Default liability & compliance terms'),
        ),
        migrations.AddField(
            model_name='quotationsettings',
            name='default_payment_terms',
            field=models.TextField(default='• Payment due within 15 days from invoice date\n• One month\'s advance / transport payment in advance for the trip\n• Payment via NEFT/RTGS in favour of "Godamwale Trading & Logistics Pvt. Ltd."\n• Late payment attracts interest @ 2% per month', help_text='Default payment terms (shown in quotation if not customized)'),
        ),
        migrations.AddField(
            model_name='quotationsettings',
            name='default_sla_terms',
            field=models.TextField(default='• 99% inventory accuracy\n• Same-day dispatch for orders placed before 2:00 PM cut-off\n• Dedicated account manager for customers over 500 pallets\n• Monthly performance reports and inventory reconciliation', help_text='Default SLA & service commitments'),
        ),
        migrations.AddField(
            model_name='quotationsettings',
            name='scope_of_service_options',
            field=models.JSONField(blank=True, default=list, help_text='Predefined scope of service options (JSON array)'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='client_address',
            field=models.TextField(blank=True, help_text='Full address for quotation (deprecated - use billing_address)'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='custom_description',
            field=models.CharField(blank=True, help_text='Optional custom description override', max_length=255),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='item_description',
            field=models.CharField(choices=[('storage_per_pallet', 'Storage Charges (per pallet per month)'), ('inbound_handling', 'Inbound Handling (per unit)'), ('outbound_handling', 'Outbound Handling (per unit)'), ('pick_pack', 'Pick & Pack (per order)'), ('packaging_material', 'Packaging Material'), ('labelling', 'Labelling Services'), ('wms_access', 'WMS Platform Access (monthly per pallet)'), ('value_added', 'Value-Added Services'), ('transport', 'Transport Services'), ('other', 'Other')], max_length=50),
        ),
    ]
