# Generated by Django 5.2.9 on 2026-02-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_add_godamwale_template_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationsettings',
            name='google_service_account_file',
        ),
        migrations.AddField(
            model_name='quotationsettings',
            name='client_id',
            field=models.CharField(blank=True, default='', help_text='Google OAuth 2.0 Client ID', max_length=255),
        ),
        migrations.AddField(
            model_name='quotationsettings',
            name='client_secret',
            field=models.CharField(blank=True, default='', help_text='Google OAuth 2.0 Client Secret — stored encrypted', max_length=500),
        ),
        migrations.AddField(
            model_name='quotationsettings',
            name='redirect_uri',
            field=models.URLField(blank=True, default='', help_text='OAuth redirect URI (e.g., https://yourdomain.com/projects/quotations/oauth-callback/)'),
        ),
    ]
