# Generated by Django 5.2.9 on 2026-02-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown_master_data', '0016_seed_regions_states'),
        ('projects', '0035_quotationtoken'),
        ('supply', '0007_seed_city_codes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projectcode',
            index=models.Index(fields=['project_status'], name='project_cod_project_b6df68_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcode',
            index=models.Index(fields=['project_status', 'operation_coordinator'], name='project_cod_project_821044_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcode',
            index=models.Index(fields=['project_status', 'backup_coordinator'], name='project_cod_project_cc3ed9_idx'),
        ),
    ]
