# Generated by Django 5.2.9 on 2026-02-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown_master_data', '0016_seed_regions_states'),
        ('projects', '0036_add_performance_indexes'),
        ('supply', '0010_location_idx_loc_active_state_city_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projectcode',
            index=models.Index(fields=['vendor_name'], name='idx_pc_vendor_name'),
        ),
        migrations.AddIndex(
            model_name='projectcode',
            index=models.Index(fields=['vendor_name', 'project_status'], name='idx_pc_vendor_status'),
        ),
    ]
