# Generated by Django 5.2.9 on 2026-02-26 14:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_vendor_commercials_margin_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='scope_of_service',
        ),
        migrations.AddField(
            model_name='quotation',
            name='operational_pallet_h',
            field=models.DecimalField(decimal_places=3, default=Decimal('4.000'), help_text='Pallet height in ft (default 4.00)', max_digits=6),
        ),
        migrations.AddField(
            model_name='quotation',
            name='operational_pallet_l',
            field=models.DecimalField(decimal_places=3, default=Decimal('3.330'), help_text='Pallet length in ft (default 3.33)', max_digits=6),
        ),
        migrations.AddField(
            model_name='quotation',
            name='operational_pallet_w',
            field=models.DecimalField(decimal_places=3, default=Decimal('3.330'), help_text='Pallet width in ft (default 3.33)', max_digits=6),
        ),
        migrations.AddField(
            model_name='quotation',
            name='operational_total_boxes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total boxes to be stored across all SKUs', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='operational_variance_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Batch management buffer percentage (default 30%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='QuotationProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('type_of_business', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C')], default='B2B', max_length=10)),
                ('type_of_operation', models.CharField(choices=[('box_in_box_out', 'Box In – Box Out'), ('box_in_piece_out', 'Box In – Piece Out'), ('box_in_pallet_out', 'Box In – Pallet Out'), ('pallet_in_box_out', 'Pallet In – Box Out')], max_length=30)),
                ('packaging_type', models.CharField(blank=True, max_length=100)),
                ('avg_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Average box/bag/pallet weight in kg', max_digits=8, null=True)),
                ('dim_l', models.DecimalField(decimal_places=4, max_digits=10)),
                ('dim_w', models.DecimalField(decimal_places=4, max_digits=10)),
                ('dim_h', models.DecimalField(decimal_places=4, max_digits=10)),
                ('dim_unit', models.CharField(choices=[('MM', 'MM'), ('CM', 'CM'), ('INCH', 'INCH'), ('FT', 'FT')], default='CM', max_length=10)),
                ('share_pct', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='% of total boxes this SKU represents (0-100)', max_digits=6)),
                ('order', models.IntegerField(default=0)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='projects.quotation')),
            ],
            options={
                'db_table': 'quotation_product',
                'ordering': ['quotation', 'order'],
            },
        ),
    ]
