# Generated by Django 5.2.9 on 2026-03-06 16:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_quotation_operational_scope_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='commercial_type',
            field=models.CharField(choices=[('vendor', 'Vendor Commercial'), ('market_rate', 'Market Rate')], default='vendor', help_text='Type of cost input used for this quotation', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='default_markup_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('26.00'), help_text='Default markup % applied to cost to derive client price', max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='expiry_notified',
            field=models.BooleanField(default=False, help_text='True once expiry management command has processed this quotation'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('voided', 'Voided'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationaudit',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('docx_generated', 'DOCX Generated'), ('pdf_generated', 'PDF Generated'), ('email_sent', 'Email Sent'), ('status_changed', 'Status Changed'), ('downloaded', 'Downloaded'), ('revision_created', 'Revision Created'), ('cloned', 'Cloned'), ('acceptance_link_sent', 'Acceptance Link Sent'), ('client_accepted', 'Client Accepted'), ('client_rejected', 'Client Rejected')], max_length=50),
        ),
        migrations.CreateModel(
            name='QuotationAcceptanceToken',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('client_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_token', to='projects.quotation')),
            ],
            options={
                'db_table': 'quotation_acceptance_token',
            },
        ),
        migrations.CreateModel(
            name='QuotationRevision',
            fields=[
                ('revision_id', models.AutoField(primary_key=True, serialize=False)),
                ('revision_number', models.IntegerField()),
                ('snapshot', models.JSONField(help_text='Full snapshot: quotation fields + all locations/items at time of revision')),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='projects.quotation')),
            ],
            options={
                'db_table': 'quotation_revision',
                'ordering': ['-revision_number'],
                'unique_together': {('quotation', 'revision_number')},
            },
        ),
    ]
