# Generated by Django 5.2.9 on 2026-03-10 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_quotation_overhaul'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Group',
                'verbose_name_plural': 'Client Groups',
                'db_table': 'client_groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='clientcard',
            name='client_group',
            field=models.ForeignKey(blank=True, help_text='Group related client entities for consolidated reporting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='projects.clientgroup'),
        ),
    ]
