[mypy]
python_version = 3.11
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_no_return = True

# Django-specific
plugins = mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = minierp.settings

# Ignore missing imports for third-party libraries
[mypy-decouple.*]
ignore_missing_imports = True

[mypy-whitenoise.*]
ignore_missing_imports = True

[mypy-celery.*]
ignore_missing_imports = True

[mypy-google.*]
ignore_missing_imports = True
