# Generated by Django 5.2.7 on 2026-01-06 08:45
# Modified to handle transition from projects app to supply app

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def check_and_handle_existing_tables(apps, schema_editor):
    """
    Check if tables already exist from projects app.
    This handles the migration from projects → supply app.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check which tables already exist
        cursor.execute("""
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name IN (
                'city_codes',
                'vendor_cards', 
                'locations',
                'vendor_warehouses',
                'vendor_contacts',
                'warehouse_contacts',
                'warehouse_photos',
                'vendor_warehouse_documents',
                'warehouse_capacities',
                'warehouse_commercials',
                'warehouse_profiles'
            )
        """)
        existing_tables = {row[0] for row in cursor.fetchall()}
        
        # Log what we found
        if existing_tables:
            print(f"  Found existing tables from projects app: {', '.join(sorted(existing_tables))}")
            print(f"  These tables will be reused by supply app")
        else:
            print(f"  No existing tables found - will create fresh tables")


class ConditionalCreateModel(migrations.CreateModel):
    """
    Custom CreateModel that skips table creation if table already exists.
    This allows seamless migration from projects app to supply app.
    """
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        from django.db import connection
        
        # Get model and table name
        model = to_state.apps.get_model(app_label, self.name)
        table_name = model._meta.db_table
        
        # Check if table exists
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                )
            """, [table_name])
            table_exists = cursor.fetchone()[0]
        
        if table_exists:
            # Table exists - just update Django's model state, don't touch DB
            print(f"  Table '{table_name}' already exists (from projects app), reusing it")
            # We still need to update Django's state to know about this model
            # but we skip the actual database table creation
            model_state = to_state.models[app_label, self.name.lower()]
            # Just update state without DB operations
        else:
            # Table doesn't exist - create it normally
            print(f"  Creating new table '{table_name}'")
            super().database_forwards(app_label, schema_editor, from_state, to_state)
    
    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # For rollback, use standard behavior
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dropdown_master_data', '0001_initial'),
        ('projects', '0025_update_vendor_warehouse_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First check what tables exist
        migrations.RunPython(
            check_and_handle_existing_tables,
            reverse_code=migrations.RunPython.noop,
        ),
        
        # Use ConditionalCreateModel for all models to handle both fresh installs and migrations
        ConditionalCreateModel(
            name='CityCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_code', models.CharField(max_length=10, unique=True)),
                ('city_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'city_codes',
            },
        ),
        ConditionalCreateModel(
            name='VendorCard',
            fields=[
                ('vendor_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vendor_short_name', models.CharField(max_length=100)),
                ('vendor_legal_name', models.CharField(max_length=200)),
                ('vendor_trade_name', models.CharField(blank=True, max_length=200)),
                ('vendor_pan', models.CharField(blank=True, db_column='vendor_pan_number', max_length=10)),
                ('vendor_gstin', models.CharField(blank=True, db_column='vendor_gst_number', max_length=15)),
                ('vendor_cin_number', models.CharField(blank=True, max_length=21)),
                ('vendor_registered_address', models.TextField(blank=True)),
                ('vendor_corporate_address', models.TextField(blank=True)),
                ('vendor_is_active', models.BooleanField(default=True)),
                ('vendor_created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendor_cards',
                'ordering': ['-vendor_created_at'],
            },
        ),
        ConditionalCreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(default='central', max_length=20)),
                ('state_code', models.CharField(blank=True, max_length=2, null=True)),
                ('city_code', models.CharField(blank=True, max_length=3, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('location', models.CharField(default='Unknown', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'locations',
                'ordering': ['state', 'city', 'location'],
                'indexes': [models.Index(fields=['state_code'], name='locations_state_c_7f0345_idx'), models.Index(fields=['city_code'], name='locations_city_co_144673_idx')],
                'unique_together': {('state', 'city', 'location')},
            },
        ),
        ConditionalCreateModel(
            name='VendorContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_contact_person', models.CharField(max_length=100)),
                ('vendor_contact_designation', models.CharField(max_length=100)),
                ('vendor_contact_department', models.CharField(max_length=100)),
                ('vendor_contact_phone', models.CharField(max_length=15)),
                ('vendor_contact_email', models.EmailField(max_length=254)),
                ('vendor_contact_is_primary', models.BooleanField(default=False)),
                ('vendor_contact_is_active', models.BooleanField(default=True)),
                ('vendor_contact_created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_code', models.ForeignKey(db_column='vendor_code_id', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='supply.vendorcard')),
            ],
            options={
                'db_table': 'vendor_contacts',
            },
        ),
        ConditionalCreateModel(
            name='VendorWarehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_code', models.CharField(max_length=30, unique=True)),
                ('warehouse_name', models.CharField(blank=True, max_length=200, null=True)),
                ('warehouse_digipin', models.CharField(blank=True, max_length=20, null=True)),
                ('warehouse_address', models.TextField(blank=True, null=True)),
                ('warehouse_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('warehouse_owner_name', models.CharField(blank=True, max_length=150, null=True)),
                ('warehouse_owner_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('google_map_location', models.CharField(blank=True, max_length=500, null=True)),
                ('warehouse_is_active', models.BooleanField(default=True)),
                ('warehouse_created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse_updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_code', models.ForeignKey(db_column='vendor_code', on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='supply.vendorcard')),
                ('warehouse_location_id', models.ForeignKey(blank=True, db_column='warehouse_location_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='supply.location')),
            ],
            options={
                'db_table': 'vendor_warehouses',
                'ordering': ['-warehouse_created_at'],
            },
        ),
        ConditionalCreateModel(
            name='VendorWarehouseDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_electricity_bill', models.FileField(blank=True, null=True, upload_to='warehouse_docs/electricity/')),
                ('warehouse_property_tax_receipt', models.FileField(blank=True, null=True, upload_to='warehouse_docs/tax/')),
                ('warehouse_owner_agreements', models.JSONField(default=dict)),
                ('warehouse_poc_aadhar', models.FileField(blank=True, null=True, upload_to='warehouse_docs/poc_aadhar/')),
                ('warehouse_poc_pan', models.FileField(blank=True, null=True, upload_to='warehouse_docs/poc_pan/')),
                ('warehouse_noc_owner', models.FileField(blank=True, null=True, upload_to='warehouse_docs/noc_owner/')),
                ('warehouse_owner_pan', models.FileField(blank=True, null=True, upload_to='warehouse_docs/owner_pan/')),
                ('warehouse_owner_aadhar', models.FileField(blank=True, null=True, upload_to='warehouse_docs/owner_aadhar/')),
                ('warehouse_noc_vendor', models.FileField(blank=True, null=True, upload_to='warehouse_docs/noc_vendor/')),
                ('warehouse_doc_uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse_doc_last_updated', models.DateTimeField(auto_now=True)),
                ('vendor_code', models.ForeignKey(db_column='vendor_code_id', on_delete=django.db.models.deletion.CASCADE, to='supply.vendorcard')),
                ('warehouse_code', models.OneToOneField(db_column='warehouse_code_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='supply.vendorwarehouse', to_field='warehouse_code')),
                ('warehouse_doc_uploaded_by', models.ForeignKey(blank=True, db_column='warehouse_doc_uploaded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendor_warehouse_documents',
            },
        ),
        ConditionalCreateModel(
            name='WarehouseContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_contact_person', models.CharField(max_length=100)),
                ('warehouse_contact_designation', models.CharField(max_length=100)),
                ('warehouse_contact_department', models.CharField(max_length=20)),
                ('warehouse_contact_phone', models.CharField(max_length=15)),
                ('warehouse_contact_email', models.EmailField(max_length=254)),
                ('warehouse_contact_is_primary', models.BooleanField(default=False)),
                ('warehouse_contact_is_active', models.BooleanField(default=True)),
                ('warehouse_contact_created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse_code', models.ForeignKey(db_column='warehouse_code_id', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='supply.vendorwarehouse', to_field='warehouse_code')),
            ],
            options={
                'db_table': 'warehouse_contacts',
            },
        ),
        ConditionalCreateModel(
            name='WarehousePhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='warehouse_photos/')),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse_code', models.ForeignKey(db_column='warehouse_code', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='supply.vendorwarehouse', to_field='warehouse_code')),
            ],
            options={
                'db_table': 'warehouse_photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        ConditionalCreateModel(
            name='WarehouseCapacity',
            fields=[
                ('warehouse', models.OneToOneField(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='capacity', serialize=False, to='supply.vendorwarehouse')),
                ('total_area_sqft', models.IntegerField(blank=True, null=True)),
                ('total_capacity', models.IntegerField(blank=True, null=True)),
                ('available_capacity', models.IntegerField(blank=True, null=True)),
                ('pallets_available', models.IntegerField(blank=True, null=True)),
                ('racking_available', models.BooleanField(default=False)),
                ('racking_details', models.TextField(blank=True)),
                ('forklifts_count', models.IntegerField(blank=True, null=True)),
                ('loading_bays_count', models.IntegerField(blank=True, null=True)),
                ('operating_hours', models.CharField(blank=True, max_length=100)),
                ('is_24x7', models.BooleanField(default=False)),
                ('temperature_controlled', models.BooleanField(default=False)),
                ('hazmat_supported', models.BooleanField(default=False)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('capacity_unit_type', models.ForeignKey(blank=True, db_column='capacity_unit_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.storageunit')),
            ],
            options={
                'db_table': 'warehouse_capacities',
            },
        ),
        ConditionalCreateModel(
            name='WarehouseCommercial',
            fields=[
                ('warehouse', models.OneToOneField(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='commercial', serialize=False, to='supply.vendorwarehouse')),
                ('indicative_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_commitment_months', models.IntegerField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('notice_period_days', models.IntegerField(blank=True, null=True)),
                ('escalation_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('escalation_terms', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_unit_type', models.ForeignKey(blank=True, db_column='rate_unit_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercials_by_rate_unit', to='dropdown_master_data.storageunit')),
                ('sla_status', models.ForeignKey(blank=True, db_column='sla_status_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.slastatus')),
            ],
            options={
                'db_table': 'warehouse_commercials',
            },
        ),
        ConditionalCreateModel(
            name='WarehouseProfile',
            fields=[
                ('warehouse', models.OneToOneField(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='supply.vendorwarehouse')),
                ('fire_safety_compliant', models.BooleanField(default=False)),
                ('security_features', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_type', models.ForeignKey(blank=True, db_column='business_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.businesstype')),
                ('property_type', models.ForeignKey(blank=True, db_column='property_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.propertytype')),
                ('warehouse_grade', models.ForeignKey(blank=True, db_column='warehouse_grade_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.warehousegrade')),
            ],
            options={
                'db_table': 'warehouse_profiles',
            },
        ),
    ]