# Generated by Django 5.2.7 on 2026-01-19 12:00
# Modified to handle existing columns and indexes from projects app

from django.db import migrations, models


class ConditionalAddField(migrations.AddField):
    """
    Custom AddField operation that only adds column if it doesn't exist.
    Updates Django's state regardless, but skips DB operation if column exists.
    """
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        from django.db import connection
        
        # Get model and table name
        model = to_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table
        
        # Check if column exists
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = %s AND column_name = %s
            """, [table_name, self.name])
            column_exists = cursor.fetchone() is not None
        
        if column_exists:
            print(f"  Column '{self.name}' already exists in {table_name}, skipping")
        else:
            print(f"  Adding column '{self.name}' to {table_name}")
            # Column doesn't exist, create it normally
            super().database_forwards(app_label, schema_editor, from_state, to_state)
    
    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # For rollback, use standard behavior
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class ConditionalAddIndex(migrations.AddIndex):
    """
    Custom AddIndex operation that only creates index if it doesn't exist.
    """

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        from django.db import connection

        # Get the index name
        model = to_state.apps.get_model(app_label, self.model_name)
        index_name = self.index.name

        # Check if index exists
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT indexname
                FROM pg_indexes
                WHERE indexname = %s
            """, [index_name])
            index_exists = cursor.fetchone() is not None

        if index_exists:
            print(f"  Index '{index_name}' already exists, skipping")
        else:
            print(f"  Creating index '{index_name}'")
            # Index doesn't exist, create it normally
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # For rollback, use standard behavior
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class ConditionalAlterField(migrations.AlterField):
    """
    Custom AlterField operation that only alters if table exists.
    Skips silently if table doesn't exist (for supply app tables not yet in production).
    """

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        from django.db import connection

        # Get model and table name
        model = to_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table

        # Check if table exists
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT table_name
                FROM information_schema.tables
                WHERE table_name = %s
            """, [table_name])
            table_exists = cursor.fetchone() is not None

        if not table_exists:
            print(f"  Table '{table_name}' doesn't exist yet, skipping AlterField for '{self.name}'")
        else:
            # Table exists, alter field normally
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # For rollback, use standard behavior
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        # Use ConditionalAddField for fields that might already exist
        ConditionalAddField(
            model_name='citycode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        ConditionalAddField(
            model_name='citycode',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        ConditionalAddField(
            model_name='citycode',
            name='state_code',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        ConditionalAddField(
            model_name='citycode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        
        # AlterField operations - these are safe to run even if already correct
        ConditionalAlterField(
            model_name='citycode',
            name='city_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        ConditionalAlterField(
            model_name='citycode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        ConditionalAlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        ConditionalAlterField(
            model_name='vendorcard',
            name='vendor_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        ConditionalAlterField(
            model_name='vendorcard',
            name='vendor_short_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        ConditionalAlterField(
            model_name='vendorcontact',
            name='vendor_contact_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        ConditionalAlterField(
            model_name='vendorwarehouse',
            name='warehouse_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        ConditionalAlterField(
            model_name='vendorwarehousedocument',
            name='warehouse_doc_uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        ConditionalAlterField(
            model_name='warehousecommercial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        ConditionalAlterField(
            model_name='warehousecontact',
            name='warehouse_contact_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        ConditionalAlterField(
            model_name='warehousephoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        ConditionalAlterField(
            model_name='warehouseprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='citycode',
            unique_together={('city_name', 'state_code')},
        ),
        
        # Use ConditionalAddIndex for index that might already exist
        ConditionalAddIndex(
            model_name='citycode',
            index=models.Index(fields=['city_code'], name='idx_city_codes_code'),
        ),
    ]