# Generated by Django 5.2.7 on 2026-02-03 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0001_initial'),
        ('supply', '0003_increase_warehouse_code_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcontact',
            name='is_rfq_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorcontact',
            name='rfq_cc_emails',
            field=models.JSONField(blank=True, default=list, help_text='CC email addresses for RFQ emails (JSON array)'),
        ),
        migrations.AddField(
            model_name='vendorcontact',
            name='rfq_cities',
            field=models.CharField(blank=True, help_text="Comma-separated cities this vendor serves (e.g., 'Mumbai, Pune, Bangalore')", max_length=500),
        ),
        migrations.AddField(
            model_name='vendorcontact',
            name='rfq_contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('rfq_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('postponed', 'Postponed')], db_index=True, default='open', max_length=20)),
                ('city', models.CharField(db_index=True, max_length=200)),
                ('area_required_sqft', models.IntegerField()),
                ('product', models.CharField(max_length=200)),
                ('tenure', models.CharField(blank=True, choices=[('short', 'Short Term'), ('medium', 'Medium Term'), ('high', 'Long Term')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('storage_rate_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Storage Rate (Rs/Sq Ft)')),
                ('storage_rate_pallet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Storage Rate (Rs/Pallet)')),
                ('storage_rate_mt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Storage Rate (Rs/MT)')),
                ('handling_rate_pallet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Handling Rate (Rs/Pallet)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RFQ',
                'verbose_name_plural': 'RFQs',
                'db_table': 'rfqs',
                'ordering': ['-rfq_id'],
            },
        ),
        migrations.CreateModel(
            name='RFQVendorMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_from_account', models.EmailField(max_length=254)),
                ('sent_to_email', models.EmailField(max_length=254)),
                ('sent_cc_emails', models.JSONField(blank=True, default=list)),
                ('deadline_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('response_received', models.BooleanField(default=False)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('quoted_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor_notes', models.TextField(blank=True)),
                ('follow_up_status', models.CharField(choices=[('pending', 'Pending Response'), ('responded', 'Responded'), ('quoted', 'Quote Received'), ('declined', 'Declined'), ('no_response', 'No Response')], default='pending', max_length=20)),
                ('gmail_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_mappings', to='gmail.email')),
                ('point_of_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_poc_mappings', to=settings.AUTH_USER_MODEL)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_mappings', to='supply.rfq')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_emails_sent', to=settings.AUTH_USER_MODEL)),
                ('vendor_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_mappings', to='supply.vendorcontact')),
            ],
            options={
                'verbose_name': 'RFQ Vendor Mapping',
                'verbose_name_plural': 'RFQ Vendor Mappings',
                'db_table': 'rfq_vendor_mappings',
                'ordering': ['-sent_at'],
                'unique_together': {('rfq', 'vendor_contact')},
            },
        ),
    ]
