# Generated by Django 5.2.9 on 2026-02-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_vendorcontact_is_rfq_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorwarehousedocument',
            name='warehouse_other_legal_docs',
            field=models.JSONField(blank=True, default=dict, help_text='Other legal & compliance documents (multiple files)'),
        ),
        migrations.AddField(
            model_name='vendorwarehousedocument',
            name='warehouse_sla_documents',
            field=models.JSONField(blank=True, default=dict, help_text='SLA documents between Vendor & Godamwale (multiple files)'),
        ),
        migrations.AlterField(
            model_name='vendorwarehousedocument',
            name='warehouse_owner_agreements',
            field=models.JSONField(blank=True, default=dict, help_text='Rent agreements between Owner & Vendor (multiple files)'),
        ),
    ]
