# Generated by Django 5.2.9 on 2026-02-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0002_remove_email_account_link_remove_email_recipients_and_more'),
        ('supply', '0005_add_legal_compliance_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqvendormapping',
            name='gmail_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_mappings', to='gmail.message'),
        ),
    ]
