# Generated by Django 5.2.9 on 2026-02-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0009_add_location_supply_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_active', 'state', 'city'], name='idx_loc_active_state_city'),
        ),
        migrations.AddIndex(
            model_name='vendorcard',
            index=models.Index(fields=['vendor_is_active'], name='idx_vc_is_active'),
        ),
        migrations.AddIndex(
            model_name='vendorcard',
            index=models.Index(fields=['vendor_is_active', 'vendor_short_name'], name='idx_vc_active_name'),
        ),
        migrations.AddIndex(
            model_name='vendorwarehouse',
            index=models.Index(fields=['warehouse_is_active'], name='idx_vw_is_active'),
        ),
        migrations.AddIndex(
            model_name='vendorwarehouse',
            index=models.Index(fields=['warehouse_location_id', 'warehouse_is_active'], name='idx_vw_loc_active'),
        ),
        migrations.AddIndex(
            model_name='vendorwarehouse',
            index=models.Index(fields=['vendor_code', 'warehouse_is_active'], name='idx_vw_vendor_active'),
        ),
    ]
