# Generated by Django 5.2.9 on 2026-02-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callyzer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallyzerSyncLog',
        ),
    ]
