# Generated by Django 5.2.9 on 2026-02-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callyzer', '0002_delete_synclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='neverattendedcall',
            name='call_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='notpickedupcall',
            name='call_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='uniqueclient',
            name='answered_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uniqueclient',
            name='inbound_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uniqueclient',
            name='missed_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uniqueclient',
            name='outbound_calls',
            field=models.IntegerField(default=0),
        ),
    ]
