# Generated by Django 5.2.7 on 2025-10-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('backoffice', 'Back Office'), ('operations', 'Operations Manager'), ('ops_controller', 'Ops Controller'), ('sales', 'Sales Manager'), ('client', 'Client'), ('vendor', 'Vendor')], max_length=20, null=True),
        ),
    ]
