# Generated by Django 5.2.7 on 2025-10-25 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userprojectassignment',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'User Project Assignment', 'verbose_name_plural': 'User Project Assignments'},
        ),
        migrations.AddField(
            model_name='userprojectassignment',
            name='assigned_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprojectassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprojectassignment',
            name='project_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprojectassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
