# Generated by Django 5.2.7 on 2025-11-03 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options_alter_user_managers_and_more'),
        ('operations', '0005_inappalert'),
        ('projects', '0005_alter_projectcode_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('dispute_raised', 'Dispute Raised'), ('dispute_assigned', 'Dispute Assigned'), ('dispute_resolved', 'Dispute Resolved'), ('query_raised', 'Billing Query Raised'), ('query_assigned', 'Query Assigned'), ('query_resolved', 'Query Resolved'), ('data_entry_missing', 'Data Entry Missing'), ('daily_summary', 'Daily Summary'), ('assignment', 'New Assignment'), ('mention', 'Mentioned in Comment'), ('system', 'System Notification')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dispute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='operations.disputelog')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.projectcode')),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='operations.billingquery')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_dde14f_idx'), models.Index(fields=['recipient', 'is_deleted'], name='notificatio_recipie_06a3c1_idx')],
            },
        ),
    ]
