# Generated by Django 5.2.7 on 2025-11-22 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='query',
        ),
    ]
