# Generated by Django 5.2.7 on 2025-12-26 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passwordhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('exception_type', models.CharField(max_length=255)),
                ('exception_message', models.TextField()),
                ('traceback', models.TextField()),
                ('request_path', models.CharField(max_length=500)),
                ('request_method', models.CharField(max_length=10)),
                ('environment', models.CharField(max_length=20)),
                ('revision', models.CharField(blank=True, max_length=50)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('request_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'error_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='error_logs_timesta_72e223_idx'), models.Index(fields=['resolved', '-timestamp'], name='error_logs_resolve_b97978_idx')],
            },
        ),
    ]
