# Generated by Django 5.2.7 on 2026-02-04 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_fix_user_role_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_made', to=settings.AUTH_USER_MODEL)),
                ('impersonated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impersonation Log',
                'verbose_name_plural': 'Impersonation Logs',
                'db_table': 'impersonation_logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
