# Generated by Django 5.2.7 on 2026-02-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_impersonationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('super_user', 'Super User'), ('director', 'Director'), ('finance_manager', 'Finance Manager'), ('operation_controller', 'Operation Controller'), ('operation_manager', 'Operation Manager'), ('sales_manager', 'Sales Manager'), ('supply_manager', 'Supply Manager'), ('operation_coordinator', 'Operation Coordinator'), ('warehouse_manager', 'Warehouse Manager'), ('backoffice', 'Backoffice'), ('crm_executive', 'CRM Executive'), ('digital_marketing', 'Digital Marketing'), ('client', 'Client'), ('vendor', 'Vendor')], default='operation_coordinator', max_length=50),
        ),
    ]
