# Generated by Django 5.2.7 on 2026-02-08 10:12

from django.db import migrations


def update_role_check_constraint(apps, schema_editor):
    """
    Update PostgreSQL CHECK constraint to include digital_marketing role
    """
    if schema_editor.connection.vendor == 'postgresql':
        # Drop old constraint
        schema_editor.execute(
            'ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;'
        )
        # Add new constraint with digital_marketing included
        schema_editor.execute("""
            ALTER TABLE users ADD CONSTRAINT users_role_check
            CHECK (role IN (
                'admin', 'super_user', 'director',
                'finance_manager', 'operation_controller', 'operation_manager',
                'sales_manager', 'supply_manager',
                'operation_coordinator', 'warehouse_manager',
                'backoffice', 'crm_executive', 'digital_marketing',
                'client', 'vendor'
            ));
        """)


def reverse_role_check_constraint(apps, schema_editor):
    """
    Reverse migration - restore old constraint without digital_marketing
    """
    if schema_editor.connection.vendor == 'postgresql':
        # Drop new constraint
        schema_editor.execute(
            'ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;'
        )
        # Add old constraint without digital_marketing
        schema_editor.execute("""
            ALTER TABLE users ADD CONSTRAINT users_role_check
            CHECK (role IN (
                'admin', 'super_user', 'director',
                'finance_manager', 'operation_controller', 'operation_manager',
                'sales_manager', 'supply_manager',
                'operation_coordinator', 'warehouse_manager',
                'backoffice', 'crm_executive',
                'client', 'vendor'
            ));
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(update_role_check_constraint, reverse_role_check_constraint),
    ]
