# Generated by Django 5.2.9 on 2026-02-14 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_update_role_check_constraint'),
        ('operations', '0060_fix_monthly_billing_nullable_columns'),
        ('projects', '0031_remove_billing_start_date_from_projectcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_06a3c1_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_label',
            field=models.CharField(blank=True, help_text="Label for action button (e.g., 'View Billing', 'Resolve Dispute')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('operations', 'Operations'), ('billing', 'Billing'), ('finance', 'Finance'), ('projects', 'Projects'), ('system', 'System'), ('reminder', 'Reminder'), ('alert', 'Alert')], db_index=True, default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='group_key',
            field=models.CharField(blank=True, db_index=True, help_text='Key to group related notifications together', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for notification (JSON)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='monthly_billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='operations.monthlybilling'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('dispute_raised', 'Dispute Raised'), ('dispute_assigned', 'Dispute Assigned'), ('dispute_resolved', 'Dispute Resolved'), ('query_raised', 'Billing Query Raised'), ('query_assigned', 'Query Assigned'), ('query_resolved', 'Query Resolved'), ('billing_corrected', 'Monthly Billing Corrected'), ('data_entry_missing', 'Data Entry Missing'), ('coordinator_reminder', 'Coordinator Reminder'), ('manager_notification', 'Manager Notification'), ('daily_summary', 'Daily Summary'), ('assignment', 'New Assignment'), ('mention', 'Mentioned in Comment'), ('system_alert', 'System Alert'), ('system', 'System Notification')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_deleted', 'is_archived'], name='notificatio_recipie_5769fc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'category', '-created_at'], name='notificatio_recipie_c662de_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'priority', '-created_at'], name='notificatio_recipie_b67aac_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['group_key', '-created_at'], name='notificatio_group_k_b6ec61_idx'),
        ),
    ]
