# Generated by Django 5.2.9 on 2026-03-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_errorlog_severity_source'),
        ('accounts', '0015_add_enterprise_notification_fields'),
    ]

    operations = [
    ]
