# Generated by Django 5.2.9 on 2026-03-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20260311_1558'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='error_logs_severit_5600b8_idx',
            old_name='errorlog_severity_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='error_logs_source_c3353d_idx',
            old_name='errorlog_source_ts_idx',
        ),
    ]
