# Generated by Django 5.2.7 on 2026-02-06 08:04

import django.db.models.deletion
import integrations.adobe_sign.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdobeSignSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('director_name', models.CharField(default='Vivek Tiwari', max_length=200)),
                ('director_email', models.EmailField(help_text='Adobe Sign account email (Vivek Tiwari)', max_length=254)),
                ('director_title', models.CharField(blank=True, default='Director', max_length=100)),
                ('api_base_url', models.CharField(default='https://api.in1.adobesign.com/api/rest/v6', help_text='Adobe Sign API base URL', max_length=500)),
                ('default_expiration_days', models.PositiveIntegerField(default=30, help_text='Default days until agreement expires')),
                ('default_reminder_frequency', models.CharField(default='EVERY_OTHER_DAY', help_text='Default reminder frequency', max_length=20)),
                ('notify_on_signature', models.BooleanField(default=True, help_text='Send notification when document is signed')),
                ('notify_on_completion', models.BooleanField(default=True, help_text='Send notification when all signatures collected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adobe Sign Settings',
                'verbose_name_plural': 'Adobe Sign Settings',
            },
        ),
        migrations.CreateModel(
            name='AdobeAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adobe_agreement_id', models.CharField(blank=True, help_text='Adobe Sign agreement ID', max_length=255, null=True, unique=True)),
                ('agreement_name', models.CharField(help_text='Agreement name visible to signers', max_length=255)),
                ('agreement_message', models.TextField(blank=True, help_text='Custom message shown to signers')),
                ('adobe_status', models.CharField(choices=[('AUTHORING', 'Authoring'), ('DRAFT', 'Draft'), ('OUT_FOR_SIGNATURE', 'Out for Signature'), ('WAITING_FOR_MY_SIGNATURE', 'Waiting for My Signature'), ('SIGNED', 'Signed'), ('APPROVED', 'Approved'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived'), ('PREFILL', 'Prefill'), ('WIDGET', 'Widget'), ('DOCUMENTS_NOT_YET_PROCESSED', 'Documents Not Yet Processed'), ('WAITING_FOR_FAXIN', 'Waiting for Fax In'), ('WAITING_FOR_VERIFICATION', 'Waiting for Verification'), ('OTHER', 'Other')], default='DRAFT', help_text='Current status in Adobe Sign', max_length=50)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Admin Approval'), ('REJECTED', 'Sent Back for Correction'), ('APPROVED_SENT', 'Approved and Sent'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Internal approval workflow status', max_length=20)),
                ('flow_type', models.CharField(choices=[('director_then_client', 'Director Signs First, Then Client'), ('client_only', 'Client Only (Director Already Signed Physically)'), ('parallel', 'Both Sign Simultaneously'), ('custom', 'Custom Signing Order')], default='director_then_client', help_text='Signing flow/order', max_length=30)),
                ('client_name', models.CharField(blank=True, help_text='Client name', max_length=200)),
                ('client_email', models.EmailField(help_text='Client email address', max_length=254)),
                ('cc_emails', models.TextField(blank=True, help_text='Comma-separated CC email addresses')),
                ('days_until_signing_deadline', models.PositiveIntegerField(default=30, help_text='Number of days before agreement expires')),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('reminder_frequency', models.CharField(choices=[('DAILY_UNTIL_SIGNED', 'Daily Until Signed'), ('EVERY_OTHER_DAY', 'Every Other Day'), ('EVERY_THIRD_DAY', 'Every Third Day'), ('EVERY_FIFTH_DAY', 'Every Fifth Day'), ('WEEKLY_UNTIL_SIGNED', 'Weekly Until Signed')], default='EVERY_OTHER_DAY', help_text='How often to remind signers', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejection_notes', models.TextField(blank=True, help_text='Specific corrections needed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_document_url', models.URLField(blank=True, null=True)),
                ('signed_document_file', models.FileField(blank=True, help_text='Downloaded signed document', null=True, upload_to='adobe_sign/signed/')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time status was synced from Adobe', null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Last sync error if any')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this agreement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_agreements', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, help_text='User who prepared this agreement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adobe Agreement',
                'verbose_name_plural': 'Adobe Agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgreementEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Agreement Created'), ('UPLOADED_BY_SENDER', 'Uploaded by Sender'), ('FAXED_BY_SENDER', 'Faxed by Sender'), ('PRESIGNED', 'Pre-signed'), ('SIGNED', 'Signed'), ('ESIGNED', 'E-signed'), ('DIGSIGNED', 'Digitally Signed'), ('APPROVED', 'Approved'), ('OFFLINE_SYNC', 'Offline Sync'), ('FAXIN_RECEIVED', 'Fax Received'), ('SIGNATURE_REQUESTED', 'Signature Requested'), ('APPROVAL_REQUESTED', 'Approval Requested'), ('RECALLED', 'Recalled'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('AUTO_CANCELLED_CONVERSION_PROBLEM', 'Auto-Cancelled (Conversion Problem)'), ('DOCUMENTS_DELETED', 'Documents Deleted'), ('ACTION_DELEGATED', 'Action Delegated'), ('ACTION_REPLACED_SIGNER', 'Signer Replaced'), ('ACTION_SHARED', 'Action Shared'), ('ACTION_COMPLETED', 'Action Completed'), ('OTHER', 'Other')], max_length=100)),
                ('event_date', models.DateTimeField()),
                ('participant_email', models.EmailField(blank=True, max_length=254)),
                ('participant_role', models.CharField(blank=True, max_length=100)),
                ('acting_user_email', models.EmailField(blank=True, max_length=254)),
                ('acting_user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='adobe_sign.adobeagreement')),
            ],
            options={
                'verbose_name': 'Agreement Event',
                'verbose_name_plural': 'Agreement Events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=integrations.adobe_sign.models.document_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=10)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash for deduplication', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adobeagreement',
            name='document',
            field=models.ForeignKey(help_text='Document to be signed', on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='adobe_sign.document'),
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name (e.g., "Standard NDA")', max_length=200)),
                ('template_type', models.CharField(choices=[('nda', 'Non-Disclosure Agreement'), ('service_agreement', 'Service Agreement'), ('lease_agreement', 'Lease Agreement'), ('amendment', 'Amendment'), ('renewal', 'Renewal Agreement'), ('termination', 'Termination Notice'), ('custom', 'Custom Document')], default='custom', max_length=50)),
                ('description', models.TextField(blank=True, help_text='What this template is used for')),
                ('template_file', models.FileField(help_text='PDF with Adobe Text Tags for signature fields', upload_to='adobe_sign/templates/')),
                ('field_definitions', models.JSONField(default=dict, help_text='JSON mapping of field names to text tag patterns')),
                ('default_signer_order', models.JSONField(default=list, help_text='Default signer order: [{"role": "Director", "order": 1}, {"role": "Client", "order": 2}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='adobe_sign.documenttemplate'),
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Signer name', max_length=200)),
                ('email', models.EmailField(help_text='Signer email address', max_length=254)),
                ('role', models.CharField(choices=[('SIGNER', 'Signer'), ('APPROVER', 'Approver'), ('ACCEPTOR', 'Acceptor'), ('CERTIFIED_RECIPIENT', 'Certified Recipient'), ('FORM_FILLER', 'Form Filler'), ('DELEGATE_TO_SIGNER', 'Delegate to Signer'), ('DELEGATE_TO_APPROVER', 'Delegate to Approver')], default='SIGNER', max_length=50)),
                ('role_label', models.CharField(blank=True, help_text='Custom label (e.g., "Director", "Client", "Witness")', max_length=100)),
                ('order', models.PositiveIntegerField(default=1, help_text='Signing order (1 = first)')),
                ('status', models.CharField(choices=[('WAITING_FOR_MY_SIGNATURE', 'Waiting for Signature'), ('WAITING_FOR_MY_APPROVAL', 'Waiting for Approval'), ('WAITING_FOR_MY_ACCEPTANCE', 'Waiting for Acceptance'), ('WAITING_FOR_MY_ACKNOWLEDGEMENT', 'Waiting for Acknowledgement'), ('WAITING_FOR_MY_FORM_FILLING', 'Waiting for Form Filling'), ('WAITING_FOR_MY_DELEGATION', 'Waiting for Delegation'), ('OUT_FOR_SIGNATURE', 'Out for Signature'), ('SIGNED', 'Signed'), ('APPROVED', 'Approved'), ('RECALLED', 'Recalled'), ('HIDDEN', 'Hidden'), ('NOT_YET_VISIBLE', 'Not Yet Visible')], default='NOT_YET_VISIBLE', max_length=50)),
                ('is_director', models.BooleanField(default=False, help_text='True if this is Vivek Tiwari (Director)')),
                ('is_client', models.BooleanField(default=False, help_text='True if this is the client')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signing_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='adobe_sign.adobeagreement')),
            ],
            options={
                'verbose_name': 'Signer',
                'verbose_name_plural': 'Signers',
                'ordering': ['agreement', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='adobeagreement',
            index=models.Index(fields=['approval_status', '-created_at'], name='adobe_sign__approva_066e70_idx'),
        ),
        migrations.AddIndex(
            model_name='adobeagreement',
            index=models.Index(fields=['adobe_status'], name='adobe_sign__adobe_s_617f31_idx'),
        ),
        migrations.AddIndex(
            model_name='adobeagreement',
            index=models.Index(fields=['client_email'], name='adobe_sign__client__25acc9_idx'),
        ),
    ]
