# Generated by Django 5.2.7 on 2026-02-06 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobe_sign', '0002_adobeagreement_created_by_and_more'),
        ('dropdown_master_data', '0013_add_adobe_sign_dropdowns'),
        ('projects', '0031_remove_billing_start_date_from_projectcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adobeagreement',
            name='agreement_category',
            field=models.ForeignKey(blank=True, db_column='agreement_category', help_text='Agreement category: New or Renewal', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.agreementcategory'),
        ),
        migrations.AddField(
            model_name='adobeagreement',
            name='agreement_type',
            field=models.ForeignKey(blank=True, db_column='agreement_type', help_text='Type of agreement: Client Agreement, SLA Agreement, Addendum-Client, Addendum-3PL', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.agreementtype'),
        ),
        migrations.AddField(
            model_name='adobeagreement',
            name='cc_email_list',
            field=models.TextField(blank=True, help_text='CC emails (mirrors cc_emails)'),
        ),
        migrations.AddField(
            model_name='adobeagreement',
            name='contract_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly billable amount from ProjectCard (auto-filled)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='adobeagreement',
            name='gst_status',
            field=models.ForeignKey(blank=True, db_column='gst_status', help_text='GST registration status: Not Registered, Registration Pending, Registered, N/A', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.gststatus'),
        ),
        migrations.AddField(
            model_name='adobeagreement',
            name='location',
            field=models.CharField(blank=True, help_text='Project location from ProjectCode (auto-filled)', max_length=100),
        ),
        migrations.AddField(
            model_name='adobeagreement',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Link to project for auto-filling agreement details', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adobe_agreements', to='projects.projectcode'),
        ),
        migrations.AddField(
            model_name='adobeagreement',
            name='sales_person',
            field=models.CharField(blank=True, help_text='Sales manager from ProjectCode (auto-filled)', max_length=100),
        ),
        migrations.AddField(
            model_name='adobeagreement',
            name='sent_date_client_vendor',
            field=models.DateTimeField(blank=True, help_text='Date when director sent to client/vendor (auto-filled when sent)', null=True),
        ),
        migrations.AddField(
            model_name='adobeagreement',
            name='sent_date_director',
            field=models.DateTimeField(blank=True, help_text='Date when backoffice sent to director (auto-filled on submit)', null=True),
        ),
        migrations.AddField(
            model_name='adobeagreement',
            name='sq_ft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly billable area from ProjectCard (auto-filled)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adobeagreement',
            name='task_undertaken_by',
            field=models.ForeignKey(blank=True, help_text='Backoffice user who submitted this agreement (auto-filled on submit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undertaken_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adobeagreement',
            name='to_email',
            field=models.EmailField(blank=True, help_text='Primary recipient email (mirrors client_email)', max_length=254),
        ),
    ]
