# Generated by Django 5.2.7 on 2026-02-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobe_sign', '0003_add_tracking_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adobeagreement',
            old_name='contract_value',
            new_name='monthly_billable_amount',
        ),
        migrations.RemoveField(
            model_name='adobeagreement',
            name='sq_ft',
        ),
        migrations.AddField(
            model_name='adobeagreement',
            name='minimum_billable_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum billable area from ProjectCard (auto-filled)', max_digits=10, null=True),
        ),
    ]
