# Generated by Django 5.2.7 on 2026-02-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobe_sign', '0005_fix_all_audit_issues'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='signer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='adobesignsettings',
            name='webhook_secret',
        ),
        migrations.RemoveField(
            model_name='agreementevent',
            name='adobe_event_id',
        ),
        migrations.RemoveField(
            model_name='agreementevent',
            name='raw_payload',
        ),
        migrations.AlterField(
            model_name='adobeagreement',
            name='adobe_agreement_id',
            field=models.CharField(blank=True, help_text='Adobe Sign agreement ID', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adobeagreement',
            name='signature_field_data',
            field=models.TextField(blank=True, help_text='JSON data for signature field placements', null=True),
        ),
    ]
