# Generated by Django 5.2.7 on 2026-02-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobe_sign', '0006_alter_signer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adobesignsettings',
            name='integration_key',
            field=models.CharField(blank=True, default='', help_text='Adobe Sign Integration Key — Account > Personal Preferences > Access Tokens', max_length=500),
        ),
        migrations.AlterField(
            model_name='adobesignsettings',
            name='api_base_url',
            field=models.CharField(default='https://api.in1.adobesign.com/api/rest/v6', help_text='Adobe Sign API base URL (India: api.in1.adobesign.com)', max_length=500),
        ),
        migrations.AlterField(
            model_name='adobesignsettings',
            name='director_email',
            field=models.EmailField(blank=True, help_text='Adobe Sign account email used for director signing', max_length=254),
        ),
    ]
