# Generated by Django 5.2.7 on 2026-02-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobe_sign', '0007_add_integration_key_to_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='adobeagreement',
            name='adobe_authoring_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
