# Generated by Django 5.2.9 on 2026-02-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobe_sign', '0009_encrypt_integration_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementevent',
            name='adobe_event_id',
            field=models.CharField(blank=True, help_text='Adobe webhook event ID for idempotency', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='raw_payload',
            field=models.JSONField(blank=True, help_text='Raw webhook payload for debugging', null=True),
        ),
        migrations.AlterField(
            model_name='adobeagreement',
            name='adobe_status',
            field=models.CharField(choices=[('AUTHORING', 'Authoring'), ('DRAFT', 'Draft'), ('OUT_FOR_SIGNATURE', 'Out for Signature'), ('WAITING_FOR_MY_SIGNATURE', 'Waiting for My Signature'), ('SIGNED', 'Signed'), ('APPROVED', 'Approved'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('RECALLED', 'Recalled'), ('ARCHIVED', 'Archived'), ('PREFILL', 'Prefill'), ('WIDGET', 'Widget'), ('DOCUMENTS_NOT_YET_PROCESSED', 'Documents Not Yet Processed'), ('WAITING_FOR_FAXIN', 'Waiting for Fax In'), ('WAITING_FOR_VERIFICATION', 'Waiting for Verification'), ('OTHER', 'Other')], default='DRAFT', help_text='Current status in Adobe Sign', max_length=50),
        ),
        migrations.AlterField(
            model_name='adobeagreement',
            name='flow_type',
            field=models.CharField(choices=[('director_then_client', 'Director Signs First, Then Client'), ('client_only', 'Client Only (Director Already Signed Physically)')], default='director_then_client', help_text='Signing flow/order', max_length=30),
        ),
    ]
