# Generated by Django 5.2.9 on 2026-02-19 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobe_sign', '0010_add_webhook_idempotency_and_recalled_status'),
        ('supply', '0009_add_location_supply_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='adobeagreement',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Link to vendor (select either project or vendor)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adobe_agreements', to='supply.vendorcard'),
        ),
        migrations.AddField(
            model_name='adobeagreement',
            name='vendor_name',
            field=models.CharField(blank=True, help_text='Vendor legal name (auto-filled from VendorCard)', max_length=200),
        ),
    ]
