# Generated by Django 5.2.9 on 2026-02-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adobe_sign', '0011_add_vendor_to_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signer',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='is_director',
        ),
    ]
