# Generated by Django 5.2.7 on 2026-01-08 23:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiginAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BiginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigin_id', models.CharField(db_index=True, max_length=64)),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('raw', models.JSONField()),
                ('created_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('lead_source', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('lead_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('locations', models.CharField(blank=True, max_length=500, null=True)),
                ('area_requirement', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('notes_fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['module', 'modified_time'], name='bigin_bigin_module_3dfb47_idx'), models.Index(fields=['module', 'created_time'], name='bigin_bigin_module_dbe287_idx'), models.Index(fields=['owner', 'status'], name='bigin_bigin_owner_7e7f25_idx')],
                'unique_together': {('bigin_id', 'module')},
            },
        ),
        migrations.CreateModel(
            name='BiginAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Bigin Account',
                'verbose_name_plural': 'Bigin Accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bigin.biginrecord',),
        ),
        migrations.CreateModel(
            name='BiginContact',
            fields=[
            ],
            options={
                'verbose_name': 'Bigin Contact',
                'verbose_name_plural': 'Bigin Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bigin.biginrecord',),
        ),
        migrations.CreateModel(
            name='BiginDeal',
            fields=[
            ],
            options={
                'verbose_name': 'Bigin Deal',
                'verbose_name_plural': 'Bigin Deals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bigin.biginrecord',),
        ),
        migrations.CreateModel(
            name='BiginNote',
            fields=[
            ],
            options={
                'verbose_name': 'Bigin Note',
                'verbose_name_plural': 'Bigin Notes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bigin.biginrecord',),
        ),
        migrations.CreateModel(
            name='BiginProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Bigin Product',
                'verbose_name_plural': 'Bigin Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bigin.biginrecord',),
        ),
    ]
