# Generated by Django 5.2.7 on 2026-01-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigin', '0002_add_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biginrecord',
            name='area_requirement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biginrecord',
            name='lead_stage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='biginrecord',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biginrecord',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
