# Generated by Django 5.2.7 on 2026-01-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigin', '0003_alter_biginrecord_area_requirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biginrecord',
            name='area_requirement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='biginrecord',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='biginrecord',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='biginrecord',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
