# Generated by Django 5.2.7 on 2026-02-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigin', '0005_phase2_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='biginrecord',
            name='idx_incremental_sync',
        ),
        migrations.RemoveIndex(
            model_name='biginrecord',
            name='idx_upsert_check',
        ),
    ]
