# Generated by Django 5.2.9 on 2026-02-12 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigin', '0009_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='biginauthtoken',
            name='encrypted_access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='biginauthtoken',
            name='encrypted_refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='biginauthtoken',
            name='access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='biginauthtoken',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='BiginSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, default='', help_text='Zoho OAuth Client ID (overrides ZOHO_CLIENT_ID env var)', max_length=255)),
                ('client_secret', models.CharField(blank=True, default='', help_text='Zoho OAuth Client Secret — stored encrypted', max_length=500)),
                ('redirect_uri', models.URLField(blank=True, default='', help_text='OAuth redirect URI (overrides ZOHO_REDIRECT_URI env var)')),
                ('auth_url', models.URLField(blank=True, default='https://accounts.zoho.com/oauth/v2/auth', help_text='Zoho OAuth authorization URL')),
                ('token_url', models.URLField(blank=True, default='https://accounts.zoho.com/oauth/v2/token', help_text='Zoho OAuth token URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bigin_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bigin Settings',
                'verbose_name_plural': 'Bigin Settings',
            },
        ),
    ]
