"""
Django settings for minierp project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')  # Required - no default for security

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # Number formatting (intcomma, etc.)


    # Your apps
    'accounts',
    'projects',
    'supply',
    'operations',
    'gmail',  # Gmail OAuth2 integration
    'integrations',
    'integrations.bigin',
    'integrations.tallysync',
    'integrations.gmail_leads',  # Gmail Lead Fetcher
    'integrations.callyzer',  # Callyzer Call Tracking
    'integrations.google_ads',  # Google Ads Integration
    'integrations.apollo',  # Apollo Outreach Integration
    'integrations.adobe_sign',  # Adobe Sign E-Signature Integration
    'integrations.expense_log',  # Google Sheets Expense Log
    'integrations.transport_sheet',  # Transport Sheet Sync
    'dropdown_master_data',
    'activity_logs',
]

MIDDLEWARE = [
    'minierp.middleware.DetailedExceptionLoggingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'minierp.middleware.ImpersonationExpiryMiddleware',  # After auth — needs session + user
    'activity_logs.middleware.ActivityLogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CSRF_COOKIE_SECURE = not DEBUG  # True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False  # Must be False — JS reads CSRF cookie for AJAX requests
SECURE_SSL_REDIRECT = False  # Cloud Run terminates TLS via SECURE_PROXY_SSL_HEADER
SESSION_COOKIE_SECURE = not DEBUG
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=lambda v: [s.strip() for s in v.split(',')] if v else [])

X_FRAME_OPTIONS = 'DENY'
SESSION_COOKIE_AGE = 43200  # 12 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Cloud Run specific settings
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


ROOT_URLCONF = 'minierp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'minierp.context_processors.app_branding',
                'operations.context_processors.notifications',
                'dropdown_master_data.context_processors.dropdowns',
                'integrations.gmail_leads.context_processors.active_syncs',
                'integrations.google_ads.context_processors.active_syncs',
                'integrations.callyzer.context_processors.active_syncs',
                'integrations.tallysync.context_processors.active_syncs',
            ],
        },
    },
]

WSGI_APPLICATION = 'minierp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Cloud SQL connection setup
if config('USE_CLOUD_SQL', default=False, cast=bool):
    # Cloud SQL - Unix socket connection
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='erp'),
            'USER': config('DB_USER', default='admin'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': f"/cloudsql/{config('CLOUD_SQL_CONNECTION_NAME')}",
            'CONN_MAX_AGE': 60,  # Reuse connections for 60 seconds
        }
    }

    # Add staging database for schema comparison (optional)
    if config('STAGING_DB_NAME', default='') and config('STAGING_DB_PASSWORD', default=''):
        DATABASES['staging'] = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('STAGING_DB_NAME'),
            'USER': config('STAGING_DB_USER', default='admin_staging'),
            'PASSWORD': config('STAGING_DB_PASSWORD'),
            'HOST': f"/cloudsql/{config('CLOUD_SQL_CONNECTION_NAME')}",
            'CONN_MAX_AGE': 60,  # Reuse connections for 60 seconds
        }
else:
    # Local PostgreSQL connection
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='erp_local'),
            'USER': config('DB_USER', default='admin'),
            'PASSWORD': config('DB_PASSWORD'),  # Required - no default for security
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
            'CONN_MAX_AGE': 60,  # Reuse connections for 60 seconds
        }
    }


# Cache configuration
# Database cache backend for shared caching across Cloud Run instances
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
        'OPTIONS': {
            'MAX_ENTRIES': 10000,
            'CULL_FREQUENCY': 4,  # Remove 25% when MAX_ENTRIES hit (default is 33%)
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Whitenoise configuration for efficient static file serving
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ==============================
# 📂 MEDIA FILES (USER UPLOADS)
# ==============================
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Increase from default 1000 to handle forms with many fields

# Allowed file extensions (security)
ALLOWED_DOCUMENT_EXTENSIONS = ['.pdf', '.jpg', '.jpeg', '.png', '.doc', '.docx']


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom User Model
AUTH_USER_MODEL = 'accounts.User'


# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Application Branding
APP_NAME = "Saral"
APP_VERSION = "v1.0"
APP_FULL_NAME = f"{APP_NAME} {APP_VERSION}"

# -----------------------------
# Google Cloud Tasks Configuration
# -----------------------------
# Cloud Tasks replaces Celery for async task execution
USE_CLOUD_TASKS = config('USE_CLOUD_TASKS', default=False, cast=bool)
GCP_PROJECT_ID = config('GCP_PROJECT_ID', default=None)
GCP_LOCATION = config('GCP_LOCATION', default='us-central1')
CLOUD_TASKS_QUEUE = config('CLOUD_TASKS_QUEUE', default='default')
CLOUD_TASKS_SERVICE_URL = config('CLOUD_TASKS_SERVICE_URL', default=None)
GCP_SERVICE_ACCOUNT = config('GCP_SERVICE_ACCOUNT', default=None)

# =====================================================
# CLOUD SCHEDULER CONFIGURATION (Replaces Celery Beat)
# =====================================================
# Schedule these Cloud Tasks via Cloud Scheduler:
#
# Bigin Incremental Sync:
#   Schedule: */5 * * * * (every 5 minutes)
#   Target: /integrations/bigin/workers/sync-all-modules/
#   Payload: {"run_full": false}
#
# Bigin Full Sync:
#   Schedule: 0 3 * * * (daily at 3 AM)
#   Target: /integrations/bigin/workers/sync-all-modules/
#   Payload: {"run_full": true}
#
# Bigin Token Refresh:
#   Schedule: 0 * * * * (every hour)
#   Target: /integrations/bigin/workers/refresh-token/
#   Payload: {}
#
# Bigin Stale Lead Check:
#   Schedule: */15 * * * * (every 15 minutes, restrict to 8am–8pm IST in Cloud Scheduler)
#   Target: /integrations/bigin/workers/stale-lead-check/
#   Payload: {}
#   Purpose: Alerts crm_executive users when a new lead has no CRM activity for 45+ minutes
#
# TallySync:
#   Schedule: */30 * * * * (every 30 minutes)
#   Target: /integrations/tallysync/workers/sync-tally-data/
#   Payload: {"days": 7}
#
# Gmail Leads Sync:
#   Schedule: */15 * * * * (every 15 minutes)
#   Target: /integrations/gmail-leads/workers/sync-all-accounts/
#   Payload: {"force_full": false}
#
# Callyzer Daily Sync:
#   Schedule: 0 2 * * * (daily at 2 AM)
#   Target: /integrations/callyzer/workers/sync-all-accounts/
#   Payload: {"days_back": 150}
#
# Google Ads Daily Sync:
#   Schedule: 0 2 * * * (daily at 2 AM)
#   Target: /integrations/google-ads/workers/sync-all-accounts/
#   Payload: {"sync_yesterday": true, "sync_current_month_search_terms": true}
#
# Gmail Sync:
#   Schedule: */15 * * * * (every 15 minutes)
#   Target: /gmail/workers/sync-all-accounts/
#   Payload: {"force_full": false}
#
# Transport Sheet Sync — hourly (production only)
# Cloud Scheduler job:
#   Name: transport-sheet-sync-hourly
#   Schedule: 0 * * * *  (every hour)
#   Target: POST {APP_URL}/transport-sheet/worker/sync/
#   Body: {"triggered_by_user": "scheduler"}
#   Auth: OIDC token (same service account as other schedulers)
# =====================================================

# =====================================================
# JOB MONITORING & CREDITS CONFIGURATION
# =====================================================
JOB_CREDITS_CONFIG = {
    # Cloud Run execution cost (per second of wall-clock time)
    'COST_PER_VCPU_SECOND': 0.000024,       # Cloud Run: $0.00002400/vCPU-second
    'COST_PER_GIB_SECOND': 0.0000025,       # Cloud Run: $0.00000250/GiB-second
    # Cloud Tasks dispatch (per million tasks ~ $0.40)
    'COST_PER_TASK_DISPATCH': 0.0000004,

    # API credits consumed per call, per integration (from official API docs)
    'API_CREDITS_PER_CALL': {
        'bigin': 1,              # Zoho Bigin: 1 credit/call (standard ops)
        'gmail_leads': 5,        # Gmail API: 5 quota units per messages.list/get
        'gmail': 5,              # Gmail API: same
        'google_ads': 1,         # Google Ads: 1 operation per SearchStream call
        'callyzer': 1,           # Callyzer: rate-limited 1 req/2s, no credit system
        'apollo': 1,             # Apollo: one credit per API request (tracked as request count)
        'tallysync': 0,          # Tally: local XML server, no API credits
        'expense_log': 0,        # Internal: no external API
    },

    # Daily API quota limits per integration (for % usage tracking)
    'DAILY_API_QUOTA': {
        'bigin': 100000,         # Zoho Bigin: max 100K credits/day (paid plan)
        'gmail_leads': 1200000,  # Gmail: 1.2M quota units/min (project-level)
        'gmail': 1200000,        # Gmail: same
        'google_ads': 15000,     # Google Ads: 15K ops/day (Basic access)
        'callyzer': 43200,       # Callyzer: ~30 req/min x 1440 min theoretical max
        'apollo': None,          # Apollo plan-dependent; monitor raw call counts
        'tallysync': None,       # No limit (local server)
        'expense_log': None,     # No external API
    },
}

# =========================================
# APOLLO API CONFIGURATION
# =========================================
APOLLO_API_KEY = config('APOLLO_API_KEY', default='')
APOLLO_BASE_URL = config('APOLLO_BASE_URL', default='https://api.apollo.io/api/v1')
APOLLO_REQUEST_TIMEOUT = config('APOLLO_REQUEST_TIMEOUT', default=30, cast=int)
APOLLO_INCREMENTAL_LOOKBACK_DAYS = config('APOLLO_INCREMENTAL_LOOKBACK_DAYS', default=30, cast=int)
APOLLO_ACTIVITY_DELAY_MS = config('APOLLO_ACTIVITY_DELAY_MS', default=100, cast=int)
APOLLO_CALL_LIMIT = config('APOLLO_CALL_LIMIT', default=350, cast=int)

# =========================================
# 🔐 ZOHO BIGIN API CREDENTIALS
# =========================================
# These will be used by integrations/bigin/token_manager.py
# Keep them in environment variables in production.

ZOHO_CLIENT_ID = config('ZOHO_CLIENT_ID')  # Required - no default for security
ZOHO_CLIENT_SECRET = config('ZOHO_CLIENT_SECRET')  # Required - no default for security
ZOHO_REDIRECT_URI = config('ZOHO_REDIRECT_URI', default="http://localhost:8000/oauth2callback/")
ZOHO_TOKEN_URL = "https://accounts.zoho.com/oauth/v2/token"
ZOHO_BASE_URL = "https://accounts.zoho.com/oauth/v2"
ZOHO_API_DOMAIN = "https://www.zohoapis.com"
BIGIN_API_BASE = "https://www.zohoapis.com/bigin/v2/"

# Disable Bigin auto-sync in local development mode
# Set to True to prevent Cloud Scheduler triggers from running syncs locally
DISABLE_BIGIN_SYNC_LOCAL = config('DISABLE_BIGIN_SYNC_LOCAL', default=True, cast=bool)

# ============================================================================
# GOOGLE CLOUD STORAGE CONFIGURATION
# ============================================================================

# Determine if running in production (Cloud Run)
RUNNING_IN_PRODUCTION = os.getenv('K_SERVICE') is not None

if RUNNING_IN_PRODUCTION:
    # Production: Use Google Cloud Storage for media files
    GS_BUCKET_NAME = 'saral-erp-media-prod'
    GS_PROJECT_ID = 'saral-erp-479508'
    
    # Load credentials from mounted secret (environment variable)
    import json
    from google.oauth2 import service_account
    
    try:
        # Get credentials from environment variable (mounted from Secret Manager)
        credentials_json = os.getenv('GCS_CREDENTIALS')
        
        if credentials_json:
            credentials_dict = json.loads(credentials_json)
            GS_CREDENTIALS = service_account.Credentials.from_service_account_info(
                credentials_dict
            )
            print("✅ GCS credentials loaded from environment")
        else:
            print("⚠️ Warning: GCS_CREDENTIALS environment variable not set")
            GS_CREDENTIALS = None
    except Exception as e:
        print(f"⚠️ Warning: Could not load GCS credentials: {e}")
        GS_CREDENTIALS = None
    
    # File URL settings
    GS_DEFAULT_ACL = None  # Private files (use signed URLs)
    GS_FILE_OVERWRITE = False  # Don't overwrite files with same name
    GS_MAX_MEMORY_SIZE = 5242880  # 5MB - files larger than this use disk
    
    print(f"📦 Storage backend: GCS (Production)")
else:
    # Local development: Use local filesystem
    print(f"📦 Storage backend: Local (Development)")

# ============================================================================
# STORAGE BACKENDS CONFIGURATION (Django 4.2+)
# ============================================================================

# Whitenoise configuration for efficient static file serving
if RUNNING_IN_PRODUCTION:
    # Production: GCS for media files, Whitenoise for static files
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # Local: FileSystem for both
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }


import sys

# Use same database for testing (safe - auto rollback after each test)
if 'test' in sys.argv or 'pytest' in sys.modules:
    DATABASES['default']['TEST'] = {
        'NAME': DATABASES['default']['NAME'],  # Use same DB name
    }



# ============================================================================
# COMPREHENSIVE LOGGING CONFIGURATION
# ============================================================================
import logging.config

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    # ========================================================================
    # FORMATTERS - How log messages are formatted
    # ========================================================================
    'formatters': {
        'detailed': {
            'format': '[{levelname}] {asctime} | {name} | {module}.{funcName}:{lineno} | Process:{process} Thread:{thread} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {asctime} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    
    # ========================================================================
    # HANDLERS - Where logs are sent
    # ========================================================================
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'detailed',
            'level': 'DEBUG',
        },
        'console_simple': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'INFO',
        },
        'error_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'detailed',
            'level': 'ERROR',
        },
    },
    
    # ========================================================================
    # LOGGERS - What to log from where
    # ========================================================================
    'loggers': {
        # Root logger - catches everything
        '': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        
        # Django core logging
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Django request/response logging (CRITICAL for debugging 500 errors)
        'django.request': {
            'handlers': ['error_console'],
            'level': 'ERROR',
            'propagate': False,
        },
        
        # Django server errors (exceptions in views)
        'django.server': {
            'handlers': ['error_console'],
            'level': 'ERROR',
            'propagate': False,
        },
        
        # Database query logging (enable for debugging slow queries)
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',  # Change to 'DEBUG' to see all SQL queries
            'propagate': False,
        },
        
        # Django security logging (failed login attempts, CSRF, etc.)
        'django.security': {
            'handlers': ['error_console'],
            'level': 'WARNING',
            'propagate': False,
        },
        
        # Django template rendering errors
        'django.template': {
            'handlers': ['error_console'],
            'level': 'WARNING',
            'propagate': False,
        },
        
        # Your application logging
        'accounts': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'projects': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'operations': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'integrations': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        
        # Third-party library logging
        'gunicorn.error': {
            'handlers': ['error_console'],
            'level': 'INFO',
            'propagate': False,
        },
        'gunicorn.access': {
            'handlers': ['console_simple'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ============================================================================
# EXCEPTION LOGGING MIDDLEWARE
# ============================================================================
# Add this to MIDDLEWARE list (find MIDDLEWARE in your settings and add this line)
# 'django.middleware.common.BrokenLinkEmailsMiddleware',  # Logs 404s

# ============================================================================
# ADMIN ERROR EMAILS (Optional - for production alerts)
# ============================================================================
if not DEBUG:
    ADMINS = [
        ('Admin', 'saral@godamwale.com'), 
    ]
    MANAGERS = ADMINS
    
    # Email settings for error notifications
    # SERVER_EMAIL = 'errors@yourdomain.com'
    # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'




# ============================================================================
# TALLY ERP INTEGRATION SETTINGS
# ============================================================================
# Tally server connection settings (from environment variables)
# Documentation: https://tallysolutions.com/tally-developer/
TALLY_HOST = config('TALLY_HOST', default='localhost')
TALLY_PORT = config('TALLY_PORT', default=2245, cast=int)
TALLY_TIMEOUT = config('TALLY_TIMEOUT', default=30, cast=int)
TALLY_COMPANY_NAME = config('TALLY_COMPANY_NAME', default='')

# Future features (not implemented yet)
TALLY_USE_HTTPS = config('TALLY_USE_HTTPS', default=False, cast=bool)
TALLY_API_KEY = config('TALLY_API_KEY', default='')
# ============================================================================
# GMAIL INTEGRATION SETTINGS (gmail app)
# ============================================================================
# Gmail OAuth2 credentials file path (credentials.json from Google Cloud Console)
# Download from: https://console.cloud.google.com/apis/credentials
GMAIL_CREDENTIALS_FILE = BASE_DIR / 'credentials.json'

# Gmail encryption key (auto-generated from SECRET_KEY if not set)
# For production, set a dedicated encryption key in environment variables
# GMAIL_ENCRYPTION_KEY = os.getenv('GMAIL_ENCRYPTION_KEY')

# ============================================================================
# GMAIL LEADS INTEGRATION SETTINGS (integrations.gmail_leads app)
# ============================================================================
# Gmail Leads OAuth2 credentials for fetching leads from Gmail
GMAIL_LEADS_CLIENT_ID = config('GMAIL_LEADS_CLIENT_ID', default='')
GMAIL_LEADS_CLIENT_SECRET = config('GMAIL_LEADS_CLIENT_SECRET', default='')
GMAIL_LEADS_REDIRECT_URI = config('GMAIL_LEADS_REDIRECT_URI', default='http://localhost:8000/integrations/gmail-leads/oauth2callback/')

# ============================================================================
# GOOGLE ADS INTEGRATION SETTINGS
# ============================================================================
# Google Ads API v19 credentials
# Get these from: https://console.cloud.google.com/apis/credentials
GOOGLE_ADS_CUSTOMER_ID = config('GOOGLE_ADS_CUSTOMER_ID', default='')
GOOGLE_ADS_CLIENT_ID = config('GOOGLE_ADS_CLIENT_ID', default='')
GOOGLE_ADS_CLIENT_SECRET = config('GOOGLE_ADS_CLIENT_SECRET', default='')  # SECURITY: Required in production
GOOGLE_ADS_DEVELOPER_TOKEN = config('GOOGLE_ADS_DEVELOPER_TOKEN', default='')  # SECURITY: Required in production
GOOGLE_ADS_REDIRECT_URI = config('GOOGLE_ADS_REDIRECT_URI', default='http://localhost:8000/integrations/google-ads/oauth2callback/')

# ADOBE SIGN E-SIGNATURE INTEGRATION SETTINGS
ADOBE_CLIENT_ID = config('ADOBE_CLIENT_ID', default='')
ADOBE_CLIENT_SECRET = config('ADOBE_CLIENT_SECRET', default='' if DEBUG else None)  # SECURITY: Required in production
ADOBE_INGESTION_KEY = config('ADOBE_INGESTION_KEY', default='')
ADOBE_SIGN_INTEGRATION_KEY = config('ADOBE_SIGN_INTEGRATION_KEY', default='')
ADOBE_SIGN_BASE_URL = config('ADOBE_SIGN_BASE_URL', default='https://api.in1.adobesign.com/api/rest/v6')
ADOBE_SIGN_DIRECTOR_EMAIL = config('ADOBE_SIGN_DIRECTOR_EMAIL', default='')
ADOBE_SIGN_WEBHOOK_SECRET = config('ADOBE_SIGN_WEBHOOK_SECRET', default='')
ADOBE_SIGN_ENCRYPTION_KEY = config('ADOBE_SIGN_ENCRYPTION_KEY', default='')


# ============================================================================
# SECURITY VALIDATION (Startup Checks)
# ============================================================================
# Validates critical security configurations at application startup
# Prevents deployment with insecure settings

import sys
import logging

startup_logger = logging.getLogger('django.security.startup')

def validate_security_config():
    """
    Validate critical security configurations at startup

    SECURITY: Enforces production-ready settings before the app starts.
    This prevents accidental deployment with insecure configurations.
    """
    import sys

    # Skip validation if running management commands that don't need it
    # (check, migrate, makemigrations, collectstatic, etc.)
    if len(sys.argv) > 1 and sys.argv[1] in ['check', 'migrate', 'makemigrations', 'showmigrations', 'sqlmigrate', 'collectstatic']:
        return

    errors = []
    warnings = []

    # 1. HTTPS Enforcement in Production
    if not DEBUG:
        # Check redirect URIs are HTTPS in production
        redirect_uris = {
            'ZOHO_REDIRECT_URI': ZOHO_REDIRECT_URI,
            'GMAIL_LEADS_REDIRECT_URI': GMAIL_LEADS_REDIRECT_URI,
            'GOOGLE_ADS_REDIRECT_URI': GOOGLE_ADS_REDIRECT_URI,
        }

        for name, uri in redirect_uris.items():
            if uri.startswith('http://') and 'localhost' not in uri:
                errors.append(
                    f"SECURITY ERROR: {name} must use HTTPS in production. "
                    f"Current value: {uri}"
                )

    # 2. SECRET_KEY Strength
    if DEBUG and SECRET_KEY == 'django-insecure-dev-key':
        warnings.append(
            "WARNING: Using default SECRET_KEY in DEBUG mode. "
            "This is OK for development but NEVER for production."
        )
    elif not DEBUG:
        if SECRET_KEY == 'django-insecure-dev-key':
            errors.append(
                "SECURITY ERROR: Using default SECRET_KEY in production. "
                "Set a unique SECRET_KEY in your .env file."
            )
        elif len(SECRET_KEY) < 50:
            errors.append(
                "SECURITY ERROR: SECRET_KEY is too short for production. "
                "Must be at least 50 characters. Generate a strong key and set it in your .env file."
            )

    # 3. Optional Integration Credentials Check
    # These are optional - features will be disabled if not provided
    optional_settings = {
        'GMAIL_LEADS_CLIENT_SECRET': GMAIL_LEADS_CLIENT_SECRET,
        'GOOGLE_ADS_CLIENT_SECRET': GOOGLE_ADS_CLIENT_SECRET,
        'GOOGLE_ADS_DEVELOPER_TOKEN': GOOGLE_ADS_DEVELOPER_TOKEN,
        'ADOBE_CLIENT_SECRET': ADOBE_CLIENT_SECRET,
    }

    for name, value in optional_settings.items():
        if not value or value.strip() == '':
            warnings.append(
                f"WARNING: {name} is not set. "
                f"Related features will be disabled. Add it to your .env file for full functionality."
            )

    # 4. ALLOWED_HOSTS in Production
    if not DEBUG and not ALLOWED_HOSTS:
        errors.append(
            "SECURITY ERROR: ALLOWED_HOSTS must be set in production. "
            "Current value is empty."
        )

    # 5. CSRF Protection
    if not DEBUG and not CSRF_TRUSTED_ORIGINS:
        warnings.append(
            "WARNING: CSRF_TRUSTED_ORIGINS is empty. "
            "Set this to your production domain."
        )

    # Report validation results
    if errors:
        startup_logger.error("\n" + "="*80)
        startup_logger.error("SECURITY CONFIGURATION ERRORS - STARTUP BLOCKED")
        startup_logger.error("="*80)
        for error in errors:
            startup_logger.error(f"❌ {error}")
        startup_logger.error("="*80)
        startup_logger.error("Fix these errors before deploying to production!")
        startup_logger.error("="*80 + "\n")

        # Block startup if in production with errors
        if not DEBUG:
            sys.exit(1)

    if warnings:
        startup_logger.warning("\n" + "="*80)
        startup_logger.warning("SECURITY CONFIGURATION WARNINGS")
        startup_logger.warning("="*80)
        for warning in warnings:
            startup_logger.warning(f"⚠️  {warning}")
        startup_logger.warning("="*80 + "\n")

    if not errors and not warnings:
        startup_logger.info("✅ Security configuration validation passed")


# Run validation at startup
try:
    validate_security_config()
except Exception as e:
    startup_logger.error(f"❌ Security validation failed: {e}")
    if not DEBUG:
        sys.exit(1)

# Activity Log settings
ACTIVITY_LOG_RETENTION_DAYS = 365
