# Generated by Django 5.2.7 on 2026-01-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallysync', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tallyvoucher',
            unique_together={('company', 'guid')},
        ),
        migrations.AlterField(
            model_name='tallyvoucher',
            name='voucher_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
