# Generated by Django 5.2.7 on 2026-01-09 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_projectcodechangelog_alter_location_unique_together_and_more'),
        ('tallysync', '0002_alter_tallyvoucher_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalespersonSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesperson_name', models.CharField()),
                ('snapshot_month', models.DateField()),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('avg_margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rank', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('tally_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tally_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tally_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tally_margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('revenue_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_billed', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_received', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('outstanding', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectcode')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'snapshot_date'], name='tallysync_p_project_d30177_idx')],
                'unique_together': {('project', 'snapshot_date')},
            },
        ),
    ]
