# Generated by Django 5.2.7 on 2026-01-19 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_alter_clientcard_client_created_at_and_more'),
        ('tallysync', '0003_salespersonsnapshot_projectfinancialsnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfinancialsnapshot',
            options={'ordering': ['-snapshot_date', 'project']},
        ),
        migrations.AlterModelOptions(
            name='salespersonsnapshot',
            options={'ordering': ['-snapshot_month', 'salesperson_name']},
        ),
        migrations.RenameIndex(
            model_name='projectfinancialsnapshot',
            new_name='tallysync_p_project_bf8636_idx',
            old_name='tallysync_p_project_d30177_idx',
        ),
        migrations.AlterUniqueTogether(
            name='salespersonsnapshot',
            unique_together={('salesperson_name', 'snapshot_month')},
        ),
        migrations.AddField(
            model_name='projectfinancialsnapshot',
            name='contracted_area',
            field=models.DecimalField(decimal_places=2, default=0, help_text='From ProjectCard billable_area', max_digits=10),
        ),
        migrations.AddField(
            model_name='projectfinancialsnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfinancialsnapshot',
            name='payment_count',
            field=models.IntegerField(default=0, help_text='Number of Payment vouchers'),
        ),
        migrations.AddField(
            model_name='projectfinancialsnapshot',
            name='purchase_count',
            field=models.IntegerField(default=0, help_text='Number of Purchase vouchers'),
        ),
        migrations.AddField(
            model_name='projectfinancialsnapshot',
            name='receipt_count',
            field=models.IntegerField(default=0, help_text='Number of Receipt vouchers'),
        ),
        migrations.AddField(
            model_name='projectfinancialsnapshot',
            name='sales_count',
            field=models.IntegerField(default=0, help_text='Number of Sales vouchers'),
        ),
        migrations.AddField(
            model_name='salespersonsnapshot',
            name='active_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salespersonsnapshot',
            name='avg_profit_per_project',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salespersonsnapshot',
            name='avg_revenue_per_project',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salespersonsnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salespersonsnapshot',
            name='total_outstanding',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salespersonsnapshot',
            name='total_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectcostcentremapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectfinancialsnapshot',
            name='outstanding',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Billed - Received', max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectfinancialsnapshot',
            name='profit_per_sqft',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profit / Contracted Area', max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectfinancialsnapshot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_snapshots', to='projects.projectcode'),
        ),
        migrations.AlterField(
            model_name='projectfinancialsnapshot',
            name='revenue_per_sqft',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Revenue / Contracted Area', max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectfinancialsnapshot',
            name='snapshot_date',
            field=models.DateField(help_text='Date of this snapshot'),
        ),
        migrations.AlterField(
            model_name='projectfinancialsnapshot',
            name='tally_expenses',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total expenses from Tally Purchase vouchers', max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectfinancialsnapshot',
            name='tally_margin_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profit / Revenue * 100', max_digits=5),
        ),
        migrations.AlterField(
            model_name='projectfinancialsnapshot',
            name='tally_profit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Revenue - Expenses', max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectfinancialsnapshot',
            name='tally_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total revenue from Tally Sales vouchers', max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectfinancialsnapshot',
            name='total_billed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total Sales vouchers', max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectfinancialsnapshot',
            name='total_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total Receipt vouchers', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salespersonsnapshot',
            name='avg_margin_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salespersonsnapshot',
            name='salesperson_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='salespersonsnapshot',
            name='snapshot_month',
            field=models.DateField(help_text='First day of the month'),
        ),
        migrations.AlterField(
            model_name='salespersonsnapshot',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='salespersonsnapshot',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='salespersonsnapshot',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tallybillreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tallycompany',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tallycostcentre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tallygroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tallyledger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tallyvoucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tallyvouchercostcentreallocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tallyvoucherledgerentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='variancealert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name='projectfinancialsnapshot',
            index=models.Index(fields=['snapshot_date'], name='tallysync_p_snapsho_a55f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfinancialsnapshot',
            index=models.Index(fields=['last_updated'], name='tallysync_p_last_up_e47b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='salespersonsnapshot',
            index=models.Index(fields=['salesperson_name', 'snapshot_month'], name='tallysync_s_salespe_7266ab_idx'),
        ),
        migrations.AddIndex(
            model_name='salespersonsnapshot',
            index=models.Index(fields=['snapshot_month'], name='tallysync_s_snapsho_26b040_idx'),
        ),
        migrations.AlterModelTable(
            name='projectfinancialsnapshot',
            table='tallysync_project_financial_snapshot',
        ),
        migrations.AlterModelTable(
            name='salespersonsnapshot',
            table='tallysync_salesperson_snapshot',
        ),
        migrations.RemoveField(
            model_name='salespersonsnapshot',
            name='percentile',
        ),
        migrations.RemoveField(
            model_name='salespersonsnapshot',
            name='rank',
        ),
    ]
