# Generated by Django 5.2.9 on 2026-02-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallysync', '0004_alter_projectfinancialsnapshot_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SyncLog',
        ),
    ]
