# Generated by Django 5.2.9 on 2026-02-13 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallysync', '0005_delete_synclog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TallySyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.CharField(blank=True, help_text='Tally server IP address (e.g., 192.168.1.100)', max_length=255)),
                ('server_port', models.CharField(blank=True, default='9000', help_text='Tally XML API port (default: 9000)', max_length=10)),
                ('company_name', models.CharField(blank=True, help_text='Default Tally company name to sync', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable TallySync integration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tallysync_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TallySync Settings',
                'verbose_name_plural': 'TallySync Settings',
                'db_table': 'tallysync_settings',
            },
        ),
    ]
