# Generated by Django 5.2.9 on 2026-03-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0064_fix_monthly_billing_unique_constraint'),
        ('tallysync', '0006_add_tallysync_settings'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tallygroup',
            index=models.Index(fields=['parent'], name='tallysync_g_parent_6ee839_idx'),
        ),
        migrations.AddIndex(
            model_name='tallygroup',
            index=models.Index(fields=['company', 'parent'], name='tallysync_g_company_2d48c6_idx'),
        ),
        migrations.AddIndex(
            model_name='tallyvoucher',
            index=models.Index(fields=['company', 'date'], name='tallysync_v_company_58155f_idx'),
        ),
        migrations.AddIndex(
            model_name='tallyvoucher',
            index=models.Index(fields=['company', 'voucher_type', 'date'], name='tallysync_v_company_f9844c_idx'),
        ),
        migrations.AddIndex(
            model_name='tallyvouchercostcentreallocation',
            index=models.Index(fields=['cost_centre'], name='tallysync_c_cost_ce_32e08f_idx'),
        ),
        migrations.AddIndex(
            model_name='tallyvouchercostcentreallocation',
            index=models.Index(fields=['ledger_entry'], name='tallysync_c_ledger__183358_idx'),
        ),
        migrations.AddIndex(
            model_name='tallyvoucherledgerentry',
            index=models.Index(fields=['voucher'], name='tallysync_v_voucher_733421_idx'),
        ),
        migrations.AddIndex(
            model_name='tallyvoucherledgerentry',
            index=models.Index(fields=['ledger_name'], name='tallysync_v_ledger__4abab8_idx'),
        ),
        migrations.AddIndex(
            model_name='tallyvoucherledgerentry',
            index=models.Index(fields=['ledger'], name='tallysync_v_ledger__eb475f_idx'),
        ),
    ]
