# Generated by Django 5.2.9 on 2026-03-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallysync', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyvoucher',
            name='need_to_pay',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tallyvoucher',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
