# Generated by Django 5.2.9 on 2026-03-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallysync', '0008_add_need_to_pay_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyvoucher',
            name='credit_period',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tallyvoucher',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tallyvoucher',
            name='utr_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
