# Generated by Django 5.2.9 on 2026-03-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallysync', '0009_add_transaction_type_utr_credit_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyvoucher',
            name='billing_month_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
