# Generated by Django 5.2.9 on 2026-03-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallysync', '0010_add_billing_month_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallysyncsettings',
            name='server_port',
            field=models.CharField(blank=True, default='2245', help_text='Tally XML API port', max_length=10),
        ),
    ]
