# Generated by Django 5.2.9 on 2026-03-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallysync', '0011_alter_tallysyncsettings_server_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallysyncsettings',
            name='tunnel_url',
            field=models.URLField(blank=True, default='', help_text='ngrok/tunnel URL (e.g., https://xxx.ngrok-free.dev). When set, overrides server_ip:port for production.', max_length=500),
        ),
    ]
