# Generated by Django 5.2.7 on 2026-02-03 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='Friendly name for this account', max_length=255)),
                ('customer_id', models.CharField(help_text='Google Ads Customer ID (e.g., 3867069282)', max_length=50)),
                ('encrypted_token', models.TextField(help_text='Encrypted OAuth2 token (access_token, refresh_token, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Ads Token',
                'verbose_name_plural': 'Google Ads Tokens',
                'db_table': 'google_ads_tokens',
                'ordering': ['-created_at'],
                'unique_together': {('customer_id',)},
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.BigIntegerField(help_text='Google Ads Campaign ID')),
                ('campaign_name', models.CharField(max_length=500)),
                ('campaign_status', models.CharField(max_length=50)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bidding_strategy', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='google_ads.googleadstoken')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'google_ads_campaigns',
                'ordering': ['campaign_name'],
            },
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('search_term', models.CharField(max_length=500)),
                ('ad_group_id', models.BigIntegerField(blank=True, null=True)),
                ('ad_group_name', models.CharField(blank=True, max_length=500, null=True)),
                ('keyword_id', models.BigIntegerField(blank=True, null=True)),
                ('keyword_text', models.CharField(blank=True, max_length=500, null=True)),
                ('match_type', models.CharField(blank=True, max_length=50, null=True)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('conversions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ctr', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('avg_cpc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cost_per_conversion', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_terms', to='google_ads.campaign')),
            ],
            options={
                'verbose_name': 'Search Term',
                'verbose_name_plural': 'Search Terms',
                'db_table': 'google_ads_search_terms',
                'ordering': ['-year', '-month', '-clicks'],
            },
        ),
        migrations.CreateModel(
            name='CampaignPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the performance data')),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('conversions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ctr', models.DecimalField(decimal_places=4, default=0, help_text='Click-through rate', max_digits=10)),
                ('avg_cpc', models.DecimalField(decimal_places=2, default=0, help_text='Average cost per click', max_digits=15)),
                ('avg_cpm', models.DecimalField(decimal_places=2, default=0, help_text='Average cost per mille', max_digits=15)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cost_per_conversion', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='google_ads.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Performance',
                'verbose_name_plural': 'Campaign Performance',
                'db_table': 'google_ads_campaign_performance',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='google_ads__date_0645e3_idx'), models.Index(fields=['campaign', 'date'], name='google_ads__campaig_57a4ab_idx')],
                'unique_together': {('campaign', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DevicePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the performance data')),
                ('device', models.CharField(choices=[('MOBILE', 'Mobile'), ('DESKTOP', 'Desktop'), ('TABLET', 'Tablet'), ('OTHER', 'Other')], max_length=20)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('conversions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctr', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('avg_cpc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_performance', to='google_ads.campaign')),
            ],
            options={
                'verbose_name': 'Device Performance',
                'verbose_name_plural': 'Device Performance',
                'db_table': 'google_ads_device_performance',
                'ordering': ['-date', 'device'],
                'indexes': [models.Index(fields=['date', 'device'], name='google_ads__date_f0a154_idx'), models.Index(fields=['campaign', 'date'], name='google_ads__campaig_202c2c_idx')],
                'unique_together': {('campaign', 'date', 'device')},
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='google_ads.googleadstoken')),
            ],
            options={
                'verbose_name': 'Google Ads Sync Log',
                'verbose_name_plural': 'Google Ads Sync Logs',
                'db_table': 'google_ads_sync_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', '-created_at'], name='google_ads__level_4b9d9d_idx'), models.Index(fields=['token', '-created_at'], name='google_ads__token_i_8c9a80_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_id'], name='google_ads__campaig_89aa48_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_status'], name='google_ads__campaig_8d8e2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('token', 'campaign_id')},
        ),
        migrations.AddIndex(
            model_name='searchterm',
            index=models.Index(fields=['year', 'month'], name='google_ads__year_a848bd_idx'),
        ),
        migrations.AddIndex(
            model_name='searchterm',
            index=models.Index(fields=['campaign', 'year', 'month'], name='google_ads__campaig_c15c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='searchterm',
            index=models.Index(fields=['search_term'], name='google_ads__search__5d6a62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='searchterm',
            unique_together={('campaign', 'year', 'month', 'search_term', 'ad_group_id')},
        ),
    ]
