# Generated by Django 5.2.7 on 2026-02-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bidding_strategy_type',
            field=models.CharField(blank=True, help_text='Bidding strategy type from API', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget_delivery_method',
            field=models.CharField(blank=True, help_text='STANDARD or ACCELERATED', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='daily_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily budget amount', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly budget (daily * days in month)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='budget_utilization',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cost / Daily Budget ratio', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='impression_share',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Search impression share (0-1)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='searchterm',
            name='status',
            field=models.CharField(blank=True, choices=[('ADDED', 'Added'), ('EXCLUDED', 'Excluded'), ('NONE', 'None')], help_text='Search term status (added as keyword or excluded)', max_length=50, null=True),
        ),
    ]
