# Generated by Django 5.2.9 on 2026-02-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0002_add_missing_google_ads_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleAdsSyncLog',
        ),
    ]
