# Generated by Django 5.2.9 on 2026-02-12 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0003_delete_synclog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, default='', help_text='Google OAuth 2.0 Client ID (overrides GOOGLE_ADS_CLIENT_ID env var)', max_length=255)),
                ('client_secret', models.CharField(blank=True, default='', help_text='Google OAuth 2.0 Client Secret — stored encrypted', max_length=500)),
                ('developer_token', models.CharField(blank=True, default='', help_text='Google Ads Developer Token — stored encrypted', max_length=500)),
                ('customer_id', models.CharField(blank=True, default='', help_text='Default Google Ads Customer ID (e.g., 3867069282)', max_length=50)),
                ('api_version', models.CharField(blank=True, default='v19', help_text='Google Ads API version (e.g., v19)', max_length=10)),
                ('redirect_uri', models.URLField(blank=True, default='', help_text='OAuth redirect URI (overrides GOOGLE_ADS_REDIRECT_URI env var)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_ads_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Ads Settings',
                'verbose_name_plural': 'Google Ads Settings',
            },
        ),
    ]
