# Generated by Django 5.2.9 on 2026-02-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0004_add_google_ads_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleadssettings',
            name='account_name',
            field=models.CharField(blank=True, default='', help_text='Friendly name for the Google Ads account', max_length=255),
        ),
        migrations.AlterField(
            model_name='googleadssettings',
            name='customer_id',
            field=models.CharField(blank=True, default='', help_text='Google Ads Customer ID (e.g., 123-456-7890 or 1234567890)', max_length=50),
        ),
    ]
