# Generated by Django 5.2.7 on 2026-02-03 09:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailLeadsToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_account', models.EmailField(max_length=254, unique=True)),
                ('encrypted_token_data', models.TextField(help_text='Encrypted OAuth2 token JSON')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_leads_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gmail Leads Token',
                'verbose_name_plural': 'Gmail Leads Tokens',
                'db_table': 'gmail_leads_tokens',
            },
        ),
        migrations.CreateModel(
            name='DuplicateCheckCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('CONTACT_US', 'Contact Us'), ('SAAS_INVENTORY', 'SAAS Inventory')], max_length=20)),
                ('cache_key', models.CharField(db_index=True, help_text='email|date|name', max_length=500)),
                ('message_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_cache', to='gmail_leads.gmailleadstoken')),
            ],
            options={
                'verbose_name': 'Duplicate Check Cache',
                'verbose_name_plural': 'Duplicate Check Cache',
                'db_table': 'gmail_leads_duplicate_cache',
                'indexes': [models.Index(fields=['cache_key'], name='gmail_leads_cache_k_f0399b_idx'), models.Index(fields=['message_id'], name='gmail_leads_message_514da7_idx')],
                'unique_together': {('account_link', 'lead_type', 'cache_key')},
            },
        ),
        migrations.CreateModel(
            name='LastProcessedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('CONTACT_US', 'Contact Us'), ('SAAS_INVENTORY', 'SAAS Inventory')], max_length=20)),
                ('last_processed_time', models.DateTimeField()),
                ('account_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lpt_records', to='gmail_leads.gmailleadstoken')),
            ],
            options={
                'verbose_name': 'Last Processed Time',
                'verbose_name_plural': 'Last Processed Times',
                'db_table': 'gmail_leads_lpt',
                'unique_together': {('account_link', 'lead_type')},
            },
        ),
        migrations.CreateModel(
            name='LeadEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('CONTACT_US', 'Contact Us'), ('SAAS_INVENTORY', 'SAAS Inventory')], db_index=True, max_length=20)),
                ('month_year', models.CharField(help_text="e.g. 'February 2026'", max_length=20)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('reply_to_name', models.CharField(blank=True, max_length=255)),
                ('reply_to_email', models.EmailField(blank=True, max_length=254)),
                ('to_addresses', models.TextField(help_text='Comma-separated email addresses')),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('subject', models.TextField()),
                ('date_received', models.DateField(db_index=True)),
                ('time_received', models.TimeField()),
                ('datetime_received', models.DateTimeField(db_index=True, help_text='Combined date+time for sorting')),
                ('form_name', models.CharField(blank=True, max_length=255)),
                ('form_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('form_phone', models.CharField(blank=True, max_length=50)),
                ('form_address', models.TextField(blank=True)),
                ('form_company_name', models.CharField(blank=True, max_length=255)),
                ('message_preview', models.TextField(blank=True, help_text='Extracted form data or message body')),
                ('processed_timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.CharField(db_index=True, help_text='Gmail message ID', max_length=50, unique=True)),
                ('account_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_emails', to='gmail_leads.gmailleadstoken')),
            ],
            options={
                'verbose_name': 'Lead Email',
                'verbose_name_plural': 'Lead Emails',
                'db_table': 'gmail_lead_emails',
                'ordering': ['-datetime_received'],
                'indexes': [models.Index(fields=['lead_type', '-datetime_received'], name='gmail_lead__lead_ty_f984ba_idx'), models.Index(fields=['utm_campaign', '-datetime_received'], name='gmail_lead__utm_cam_441fec_idx'), models.Index(fields=['form_email', '-datetime_received'], name='gmail_lead__form_em_f35821_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('CRITICAL_DEBUG', 'Critical Debug')], db_index=True, max_length=20)),
                ('operation', models.CharField(help_text="e.g. 'Quota', 'Gmail API Fetch', 'Batch Start'", max_length=100)),
                ('details', models.TextField()),
                ('duration_ms', models.IntegerField(blank=True, help_text='Operation duration in milliseconds', null=True)),
                ('lead_type', models.CharField(blank=True, max_length=20)),
                ('account_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='gmail_leads.gmailleadstoken')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'db_table': 'gmail_leads_sync_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'level'], name='gmail_leads_timesta_0b4042_idx'), models.Index(fields=['account_link', '-timestamp'], name='gmail_leads_account_8d8999_idx')],
            },
        ),
    ]
