# Generated by Django 5.2.7 on 2026-02-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leademail',
            name='full_message_body',
            field=models.TextField(blank=True, help_text='Complete email message body (HTML/plain text)'),
        ),
    ]
