# Generated by Django 5.2.7 on 2026-02-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_leads', '0002_leademail_full_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailleadstoken',
            name='excluded_emails',
            field=models.TextField(blank=True, help_text='Comma-separated list of email addresses to exclude from sync (e.g., spam@example.com, test@domain.com)'),
        ),
    ]
