# Generated by Django 5.2.7 on 2026-02-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_leads', '0003_gmailleadstoken_excluded_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='leademail',
            name='gclid',
            field=models.CharField(blank=True, help_text='Google Click Identifier', max_length=255),
        ),
    ]
