# Generated by Django 5.2.7 on 2026-01-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('bigin_full', 'Bigin Full Sync'), ('bigin_incremental', 'Bigin Incremental Sync'), ('bigin_module', 'Bigin Module Sync'), ('tally_full', 'Tally Full Sync'), ('tally_incremental', 'Tally Incremental Sync'), ('google_ads', 'Google Ads Sync')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], db_index=True, default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('total_records_synced', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('module_results', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('triggered_by', models.CharField(blank=True, max_length=100, null=True)),
                ('triggered_by_user', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at', 'status'], name='integration_started_22e43b_idx'), models.Index(fields=['sync_type', '-started_at'], name='integration_sync_ty_828862_idx')],
            },
        ),
    ]
