# Generated by Django 5.2.7 on 2026-01-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='current_module',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='current_module_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='current_module_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='overall_progress_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='stop_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed'), ('stopping', 'Stopping'), ('stopped', 'Stopped')], db_index=True, default='running', max_length=20),
        ),
    ]
