# Generated by Django 5.2.7 on 2026-02-09 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigin', '0009_add_performance_indexes'),
        ('gmail_leads', '0004_leademail_gclid'),
        ('integrations', '0002_synclog_current_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_confidence', models.CharField(choices=[('exact_email', 'Exact Email Match'), ('fuzzy_email', 'Fuzzy Email Match'), ('temporal', 'Temporal Proximity Match')], max_length=20)),
                ('match_score', models.FloatField(help_text='0-100 confidence score')),
                ('matched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('gclid', models.CharField(blank=True, help_text='Google Click Identifier', max_length=255)),
                ('gmail_received_at', models.DateTimeField(db_index=True, help_text='When lead was received')),
                ('bigin_created_at', models.DateTimeField(help_text='When contact was created in Bigin')),
                ('time_to_contact_hours', models.FloatField(help_text='Hours between lead and contact creation')),
                ('bigin_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='bigin.bigincontact')),
                ('gmail_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='gmail_leads.leademail')),
            ],
            options={
                'verbose_name': 'Lead Attribution',
                'verbose_name_plural': 'Lead Attributions',
                'db_table': 'integrations_lead_attribution',
                'ordering': ['-matched_at'],
                'indexes': [models.Index(fields=['bigin_contact', '-matched_at'], name='integration_bigin_c_76c1e0_idx'), models.Index(fields=['utm_campaign', '-matched_at'], name='integration_utm_cam_cb83ee_idx'), models.Index(fields=['match_confidence'], name='integration_match_c_6eec69_idx'), models.Index(fields=['-gmail_received_at'], name='integration_gmail_r_27ccfa_idx')],
                'unique_together': {('gmail_lead', 'bigin_contact')},
            },
        ),
    ]
