# Generated by Django 5.2.9 on 2026-02-12 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_leadattribution'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='synclog',
            name='integration_started_22e43b_idx',
        ),
        migrations.AddField(
            model_name='synclog',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='integrations.synclog'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='synclog',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='integration',
            field=models.CharField(blank=True, choices=[('bigin', 'Bigin CRM'), ('gmail_leads', 'Gmail Leads'), ('google_ads', 'Google Ads'), ('callyzer', 'Callyzer'), ('tallysync', 'TallySync')], db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='level',
            field=models.CharField(blank=True, choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='log_kind',
            field=models.CharField(choices=[('batch', 'Batch Run'), ('operation', 'Operation')], db_index=True, default='batch', max_length=20),
        ),
        migrations.AddField(
            model_name='synclog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='operation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='records_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='sub_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='current_module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='sync_type',
            field=models.CharField(choices=[('bigin_full', 'Bigin Full Sync'), ('bigin_incremental', 'Bigin Incremental Sync'), ('bigin_module', 'Bigin Module Sync'), ('gmail_leads_full', 'Gmail Leads Full Sync'), ('gmail_leads_incremental', 'Gmail Leads Incremental Sync'), ('google_ads', 'Google Ads Sync'), ('google_ads_historical', 'Google Ads Historical Sync'), ('callyzer', 'Callyzer Sync'), ('tally_full', 'Tally Full Sync'), ('tally_incremental', 'Tally Incremental Sync'), ('tally_companies', 'Tally Companies Sync'), ('tally_ledgers', 'Tally Ledgers Sync'), ('tally_vouchers', 'Tally Vouchers Sync')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['integration', '-started_at'], name='integration_integra_5f1235_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['integration', 'log_kind', '-started_at'], name='integration_integra_a18a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['status', '-started_at'], name='integration_status_099af2_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['level', '-started_at'], name='integration_level_aad8ff_idx'),
        ),
    ]
