# Generated by Django 5.2.9 on 2026-02-20 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_add_synclog_cleanup_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='api_calls_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='scheduled_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='integrations.scheduledjob'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['scheduled_job', '-started_at'], name='integration_schedul_74354f_idx'),
        ),
    ]
