# Generated by Django 5.2.8 on 2026-01-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0005_decimal_money_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("rate_card", models.JSONField(help_text="Full rate card logic (JSON)")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "couriers",
                "ordering": ["name"],
            },
        ),
    ]
