# Generated by Django 5.2.8 on 2026-01-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0006_courier"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="add_z_a",
            field=models.FloatField(default=0.0, verbose_name="Add Zone A"),
        ),
        migrations.AddField(
            model_name="courier",
            name="add_z_b",
            field=models.FloatField(default=0.0, verbose_name="Add Zone B"),
        ),
        migrations.AddField(
            model_name="courier",
            name="add_z_c",
            field=models.FloatField(default=0.0, verbose_name="Add Zone C"),
        ),
        migrations.AddField(
            model_name="courier",
            name="add_z_d",
            field=models.FloatField(default=0.0, verbose_name="Add Zone D"),
        ),
        migrations.AddField(
            model_name="courier",
            name="add_z_e",
            field=models.FloatField(default=0.0, verbose_name="Add Zone E"),
        ),
        migrations.AddField(
            model_name="courier",
            name="add_z_f",
            field=models.FloatField(default=0.0, verbose_name="Add Zone F"),
        ),
        migrations.AddField(
            model_name="courier",
            name="carrier_mode",
            field=models.CharField(
                choices=[("Surface", "Surface"), ("Air", "Air")], default="Surface", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="courier",
            name="carrier_type",
            field=models.CharField(
                choices=[("Courier", "Courier"), ("PTL", "PTL")], default="Courier", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="courier",
            name="cod_charge_fixed",
            field=models.FloatField(default=0.0, verbose_name="COD Fixed Fee"),
        ),
        migrations.AddField(
            model_name="courier",
            name="cod_charge_percent",
            field=models.FloatField(default=0.0, verbose_name="COD % (ratio, e.g. 0.015)"),
        ),
        migrations.AddField(
            model_name="courier",
            name="fuel_surcharge_percent",
            field=models.FloatField(default=0.0, verbose_name="Fuel Surcharge % (ratio)"),
        ),
        migrations.AddField(
            model_name="courier",
            name="fwd_z_a",
            field=models.FloatField(default=0.0, verbose_name="Fwd Zone A"),
        ),
        migrations.AddField(
            model_name="courier",
            name="fwd_z_b",
            field=models.FloatField(default=0.0, verbose_name="Fwd Zone B"),
        ),
        migrations.AddField(
            model_name="courier",
            name="fwd_z_c",
            field=models.FloatField(default=0.0, verbose_name="Fwd Zone C"),
        ),
        migrations.AddField(
            model_name="courier",
            name="fwd_z_d",
            field=models.FloatField(default=0.0, verbose_name="Fwd Zone D"),
        ),
        migrations.AddField(
            model_name="courier",
            name="fwd_z_e",
            field=models.FloatField(default=0.0, verbose_name="Fwd Zone E"),
        ),
        migrations.AddField(
            model_name="courier",
            name="fwd_z_f",
            field=models.FloatField(default=0.0, verbose_name="Fwd Zone F"),
        ),
        migrations.AddField(
            model_name="courier",
            name="min_weight",
            field=models.FloatField(default=0.5, help_text="Min weight in kg"),
        ),
        migrations.AddField(
            model_name="courier",
            name="rate_logic",
            field=models.CharField(
                choices=[("Zonal", "Zonal"), ("city_to_city", "City Specific")],
                default="Zonal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="courier",
            name="volumetric_divisor",
            field=models.IntegerField(default=5000, help_text="e.g. 5000 or 4500"),
        ),
        migrations.AlterField(
            model_name="courier",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="courier",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Carrier Name"),
        ),
        migrations.AlterField(
            model_name="courier",
            name="rate_card",
            field=models.JSONField(
                blank=True, default=dict, help_text="Full rate card logic (JSON)"
            ),
        ),
    ]
