# Generated by Django 5.2.8 on 2026-01-05 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0007_courier_add_z_a_courier_add_z_b_courier_add_z_c_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courier",
            name="add_z_a",
            field=models.FloatField(blank=True, default=0.0, verbose_name="Add Zone A"),
        ),
        migrations.AlterField(
            model_name="courier",
            name="add_z_b",
            field=models.FloatField(blank=True, default=0.0, verbose_name="Add Zone B"),
        ),
        migrations.AlterField(
            model_name="courier",
            name="add_z_c",
            field=models.FloatField(blank=True, default=0.0, verbose_name="Add Zone C"),
        ),
        migrations.AlterField(
            model_name="courier",
            name="add_z_d",
            field=models.FloatField(blank=True, default=0.0, verbose_name="Add Zone D"),
        ),
        migrations.AlterField(
            model_name="courier",
            name="add_z_e",
            field=models.FloatField(blank=True, default=0.0, verbose_name="Add Zone E"),
        ),
        migrations.AlterField(
            model_name="courier",
            name="add_z_f",
            field=models.FloatField(blank=True, default=0.0, verbose_name="Add Zone F"),
        ),
        migrations.AlterField(
            model_name="courier",
            name="fwd_z_a",
            field=models.FloatField(blank=True, default=0.0, verbose_name="Fwd Zone A"),
        ),
        migrations.AlterField(
            model_name="courier",
            name="fwd_z_b",
            field=models.FloatField(blank=True, default=0.0, verbose_name="Fwd Zone B"),
        ),
        migrations.AlterField(
            model_name="courier",
            name="fwd_z_c",
            field=models.FloatField(blank=True, default=0.0, verbose_name="Fwd Zone C"),
        ),
        migrations.AlterField(
            model_name="courier",
            name="fwd_z_d",
            field=models.FloatField(blank=True, default=0.0, verbose_name="Fwd Zone D"),
        ),
        migrations.AlterField(
            model_name="courier",
            name="fwd_z_e",
            field=models.FloatField(blank=True, default=0.0, verbose_name="Fwd Zone E"),
        ),
        migrations.AlterField(
            model_name="courier",
            name="fwd_z_f",
            field=models.FloatField(blank=True, default=0.0, verbose_name="Fwd Zone F"),
        ),
        migrations.AlterField(
            model_name="courier",
            name="rate_logic",
            field=models.CharField(
                choices=[
                    ("Zonal_Standard", "Zonal (Standard A-F Zones)"),
                    ("Zonal_Custom", "Zonal (Custom Zone Matrix)"),
                    ("City_To_City", "City to City Routes"),
                ],
                default="Zonal_Standard",
                help_text="Select the routing logic type",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CityRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("city_name", models.CharField(max_length=100, verbose_name="City/Destination")),
                ("rate_per_kg", models.FloatField(verbose_name="Rate (per kg)")),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="city_routes",
                        to="courier.courier",
                    ),
                ),
            ],
            options={
                "db_table": "city_routes",
                "ordering": ["city_name"],
                "unique_together": {("courier", "city_name")},
            },
        ),
        migrations.CreateModel(
            name="CustomZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "location_name",
                    models.CharField(help_text="State/City/Region name", max_length=100),
                ),
                (
                    "zone_code",
                    models.CharField(help_text="Zone code (e.g. CTL, E1, MH1)", max_length=20),
                ),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_zones",
                        to="courier.courier",
                    ),
                ),
            ],
            options={
                "db_table": "custom_zones",
                "ordering": ["zone_code", "location_name"],
                "unique_together": {("courier", "location_name")},
            },
        ),
        migrations.CreateModel(
            name="CustomZoneRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("from_zone", models.CharField(max_length=20, verbose_name="From Zone")),
                ("to_zone", models.CharField(max_length=20, verbose_name="To Zone")),
                ("rate_per_kg", models.FloatField(verbose_name="Rate (per kg)")),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_zone_rates",
                        to="courier.courier",
                    ),
                ),
            ],
            options={
                "db_table": "custom_zone_rates",
                "ordering": ["from_zone", "to_zone"],
                "unique_together": {("courier", "from_zone", "to_zone")},
            },
        ),
    ]
