# Generated by Django 5.2.8 on 2026-01-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0008_alter_courier_add_z_a_alter_courier_add_z_b_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="max_weight",
            field=models.FloatField(default=99999.0, help_text="Max weight in kg"),
        ),
    ]
