# Generated by Django 5.2.8 on 2026-01-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0009_courier_max_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courier",
            name="rate_logic",
            field=models.CharField(
                choices=[
                    ("Zonal_Standard", "Zonal (Standard A-F Zones)"),
                    ("Zonal_Custom", "Zonal (Custom Zone Matrix)"),
                    ("City_To_City", "City to City Routes"),
                    ("Region_CSV", "Regional (CSV Based)"),
                ],
                default="Zonal_Standard",
                help_text="Select the routing logic type",
                max_length=20,
            ),
        ),
    ]
