# Generated by Django 5.2.8 on 2026-01-07 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0010_alter_courier_rate_logic"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="courier.courier",
            ),
        ),
    ]
