# Generated by Django 5.2.8 on 2026-01-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0012_populate_order_carrier_fk"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="orders_selecte_ce0cbe_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="selected_carrier",
        ),
    ]
