# Generated by Django 5.2.8 on 2026-01-07 09:23

from django.db import migrations

def populate_columns(apps, schema_editor):
    Courier = apps.get_model('courier', 'Courier')
    DeliverySlab = apps.get_model('courier', 'DeliverySlab')
    
    for c in Courier.objects.all():
        rc = c.rate_card
        if not rc: continue
        
        # Fuel
        fc = rc.get('fuel_config', {})
        c.fuel_surcharge_percent = float(fc.get('flat_percent') or 0.0)
        c.fuel_is_dynamic = bool(fc.get('is_dynamic', False))
        c.fuel_base_price = float(fc.get('base_diesel_price') or 0.0)
        c.fuel_ratio = float(fc.get('diesel_ratio') or 0.0)
        
        # Fixed Fees
        ff = rc.get('fixed_fees', {})
        c.docket_fee = float(ff.get('docket_fee') or 0.0)
        c.eway_bill_fee = float(ff.get('eway_bill_fee') or 0.0)
        c.appointment_delivery_fee = float(ff.get('appointment_delivery') or 0.0)
        
        # Variable Fees
        vf = rc.get('variable_fees', {})
        c.hamali_per_kg = float(vf.get('hamali_per_kg') or 0.0)
        c.min_hamali = float(vf.get('min_hamali') or 0.0)
        c.fov_min = float(vf.get('fov_min') or 0.0)
        c.fov_insured_percent = float(vf.get('fov_insured_percent') or 0.0)
        c.fov_uninsured_percent = float(vf.get('fov_uninsured_percent') or 0.0)
        c.damage_claim_percent = float(vf.get('damage_claim_percent') or 0.0)
        
        c.save()
        
        # Delivery Slabs for CityRoutes
        rl = rc.get('routing_logic', {})
        slabs = rl.get('door_delivery_slabs', [])
        if slabs:
            for s in slabs:
                DeliverySlab.objects.create(
                    courier=c,
                    min_weight=float(s.get('min')),
                    max_weight=float(s.get('max')) if s.get('max') is not None else None,
                    rate=float(s.get('rate'))
                )

class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0014_courier_appointment_delivery_fee_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_columns),
    ]
