# Generated by Django 5.2.8 on 2026-01-07 09:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0015_populate_rates_from_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "diesel_price_current",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("90.00"),
                        help_text="Used for dynamic fuel surcharge calculation",
                        max_digits=10,
                        verbose_name="Current Diesel Price",
                    ),
                ),
                (
                    "base_diesel_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("90.00"),
                        help_text="Benchmark price for fuel surcharge",
                        max_digits=10,
                        verbose_name="Base Diesel Price",
                    ),
                ),
                (
                    "fuel_surcharge_ratio",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.625"),
                        help_text="Ratio for fuel surcharge calculation",
                        max_digits=5,
                        verbose_name="Fuel Surcharge Ratio",
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.18"),
                        help_text="18% = 0.18",
                        max_digits=5,
                        verbose_name="GST Rate",
                    ),
                ),
                (
                    "escalation_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.15"),
                        help_text="Margin/Escalation 15% = 0.15",
                        max_digits=5,
                        verbose_name="Escalation Rate",
                    ),
                ),
                (
                    "default_servicable_csv",
                    models.CharField(
                        default="BlueDart_Servicable Pincodes.csv",
                        help_text="Filename in config directory",
                        max_length=255,
                        verbose_name="Default Serviceable CSV",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configuration",
                "db_table": "system_config",
            },
        ),
    ]
