# Generated by Django 5.2.8 on 2026-01-07 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0016_systemconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourierZoneRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "zone_code",
                    models.CharField(
                        help_text="Zone Code (e.g. z_a, z_b, north, south)", max_length=20
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[("forward", "Forward Rate"), ("additional", "Additional Rate")],
                        default="forward",
                        max_length=20,
                    ),
                ),
                ("rate", models.FloatField(default=0.0, verbose_name="Rate (₹)")),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_rates",
                        to="courier.courier",
                    ),
                ),
            ],
            options={
                "db_table": "courier_zone_rates",
                "ordering": ["zone_code", "rate_type"],
                "unique_together": {("courier", "zone_code", "rate_type")},
            },
        ),
    ]
