# Generated by Django 5.2.8 on 2026-01-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0017_courierzonerate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courier",
            name="add_z_a",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="add_z_b",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="add_z_c",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="add_z_d",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="add_z_e",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="add_z_f",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="appointment_delivery_fee",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="damage_claim_percent",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="docket_fee",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="eway_bill_fee",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fov_insured_percent",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fov_min",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fov_uninsured_percent",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fuel_base_price",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fuel_is_dynamic",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fuel_ratio",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fwd_z_a",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fwd_z_b",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fwd_z_c",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fwd_z_d",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fwd_z_e",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fwd_z_f",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="hamali_per_kg",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="min_hamali",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="rate_card",
        ),
        migrations.AddField(
            model_name="courier",
            name="legacy_rate_card_backup",
            field=models.JSONField(
                blank=True, default=dict, help_text="Backup of legacy JSON logic"
            ),
        ),
    ]
