# Generated by Django 5.2.8 on 2026-01-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0018_remove_courier_add_z_a_remove_courier_add_z_b_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="appointment_delivery_fee",
            field=models.FloatField(default=0.0, verbose_name="Appointment Delivery Fee"),
        ),
        migrations.AddField(
            model_name="courier",
            name="damage_claim_percent",
            field=models.FloatField(default=0.0, verbose_name="Damage Claim %"),
        ),
        migrations.AddField(
            model_name="courier",
            name="docket_fee",
            field=models.FloatField(default=0.0, verbose_name="Docket Fee"),
        ),
        migrations.AddField(
            model_name="courier",
            name="eway_bill_fee",
            field=models.FloatField(default=0.0, verbose_name="E-Way Bill Fee"),
        ),
        migrations.AddField(
            model_name="courier",
            name="fov_insured_percent",
            field=models.FloatField(default=0.0, verbose_name="FOV Insured %"),
        ),
        migrations.AddField(
            model_name="courier",
            name="fov_min",
            field=models.FloatField(default=0.0, verbose_name="Min FOV"),
        ),
        migrations.AddField(
            model_name="courier",
            name="fov_uninsured_percent",
            field=models.FloatField(default=0.0, verbose_name="FOV Uninsured %"),
        ),
        migrations.AddField(
            model_name="courier",
            name="fuel_base_price",
            field=models.FloatField(default=0.0, verbose_name="Base Diesel Price"),
        ),
        migrations.AddField(
            model_name="courier",
            name="fuel_is_dynamic",
            field=models.BooleanField(default=False, verbose_name="Dynamic Fuel Surcharge"),
        ),
        migrations.AddField(
            model_name="courier",
            name="fuel_ratio",
            field=models.FloatField(default=0.0, verbose_name="Diesel Ratio"),
        ),
        migrations.AddField(
            model_name="courier",
            name="hamali_per_kg",
            field=models.FloatField(default=0.0, verbose_name="Hamali (per kg)"),
        ),
        migrations.AddField(
            model_name="courier",
            name="min_hamali",
            field=models.FloatField(default=0.0, verbose_name="Min Hamali"),
        ),
    ]
