# Generated by Django 5.2.8 on 2026-01-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0019_courier_appointment_delivery_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="hub_city",
            field=models.CharField(
                blank=True,
                help_text="Hub city for City-to-City logic",
                max_length=100,
                null=True,
                verbose_name="Hub City",
            ),
        ),
        migrations.AddField(
            model_name="courier",
            name="required_source_city",
            field=models.CharField(
                blank=True,
                help_text="Restrict service to this city only",
                max_length=100,
                null=True,
                verbose_name="Required Source City",
            ),
        ),
        migrations.AddField(
            model_name="courier",
            name="serviceable_pincode_csv",
            field=models.CharField(
                blank=True,
                help_text="Filename for CSV-based logic (e.g. BlueDart_...csv)",
                max_length=255,
                null=True,
                verbose_name="Serviceable CSV",
            ),
        ),
    ]
