# Generated by Django 5.2.8 on 2026-01-07
# Fixes hardcoded LEGACY_HUB_PINCODE_PREFIXES in engine.py

from django.db import migrations, models


def populate_hub_prefixes(apps, schema_editor):
    """
    Populate hub_pincode_prefixes for carriers that need it.
    
    Currently only ACPL uses Bhiwandi hub with 4213 prefix.
    This replaces the hardcoded LEGACY_HUB_PINCODE_PREFIXES dict in engine.py.
    """
    Courier = apps.get_model('courier', 'Courier')
    
    # ACPL Surface 50kg uses Bhiwandi hub
    try:
        acpl = Courier.objects.filter(name__icontains='ACPL').first()
        if acpl and acpl.hub_city == 'bhiwandi':
            # Store as list of prefixes for forward compatibility
            acpl.hub_pincode_prefixes = ['4213']
            acpl.save()
            print(f"[SUCCESS] Set hub_pincode_prefixes for {acpl.name}: {acpl.hub_pincode_prefixes}")
    except Exception as e:
        print(f"[WARNING] Could not populate hub prefixes for ACPL: {e}")


def reverse_hub_prefixes(apps, schema_editor):
    """Clear hub_pincode_prefixes on rollback."""
    Courier = apps.get_model('courier', 'Courier')
    Courier.objects.update(hub_pincode_prefixes=None)


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0021_fix_carrier_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='hub_pincode_prefixes',
            field=models.JSONField(
                blank=True,
                null=True,
                help_text="List of pincode prefixes for hub city validation (e.g. ['4213'] for Bhiwandi)",
                verbose_name="Hub Pincode Prefixes"
            ),
        ),
        migrations.RunPython(
            populate_hub_prefixes,
            reverse_code=reverse_hub_prefixes
        ),
    ]
