# Generated by Django 5.2.8 on 2026-01-07 12:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0022_add_hub_pincode_prefixes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cityroute",
            name="rate_per_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Rate (per kg)",
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="appointment_delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Appointment Delivery Fee",
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="cod_charge_fixed",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="COD Fixed Fee",
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="cod_charge_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=7,
                verbose_name="COD % (ratio, e.g. 0.015)",
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="damage_claim_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=7,
                verbose_name="Damage Claim %",
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="docket_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12, verbose_name="Docket Fee"
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="eway_bill_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="E-Way Bill Fee",
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="fov_insured_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=7,
                verbose_name="FOV Insured %",
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="fov_min",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12, verbose_name="Min FOV"
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="fov_uninsured_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=7,
                verbose_name="FOV Uninsured %",
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="fuel_base_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Base Diesel Price",
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="fuel_ratio",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=7,
                verbose_name="Diesel Ratio",
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="fuel_surcharge_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=7,
                verbose_name="Fuel Surcharge % (ratio)",
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="hamali_per_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Hamali (per kg)",
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="min_hamali",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12, verbose_name="Min Hamali"
            ),
        ),
        migrations.AlterField(
            model_name="courierzonerate",
            name="rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12, verbose_name="Rate (₹)"
            ),
        ),
        migrations.AlterField(
            model_name="customzonerate",
            name="rate_per_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Rate (per kg)",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryslab",
            name="rate",
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Flat Rate"),
        ),
    ]
