# Generated by Django 5.2.8 on 2026-01-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0023_alter_cityroute_rate_per_kg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ftlorder",
            name="destination_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ftlorder",
            name="source_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
