# Generated by Django 5.2.8 on 2026-01-08 10:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0024_ftl_address_updates"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "docket_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Docket Fee",
                    ),
                ),
                (
                    "eway_bill_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="E-Way Bill Fee",
                    ),
                ),
                (
                    "appointment_delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Appointment Delivery Fee",
                    ),
                ),
                (
                    "cod_fixed",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="COD Fixed Fee",
                    ),
                ),
                (
                    "cod_percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=7,
                        verbose_name="COD %",
                    ),
                ),
                (
                    "hamali_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Hamali (per kg)",
                    ),
                ),
                (
                    "min_hamali",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Min Hamali",
                    ),
                ),
                (
                    "fov_min",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Min FOV",
                    ),
                ),
                (
                    "fov_insured_percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=7,
                        verbose_name="FOV Insured %",
                    ),
                ),
                (
                    "fov_uninsured_percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=7,
                        verbose_name="FOV Uninsured %",
                    ),
                ),
                (
                    "damage_claim_percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=7,
                        verbose_name="Damage Claim %",
                    ),
                ),
            ],
            options={
                "db_table": "courier_fee_structures",
            },
        ),
        migrations.CreateModel(
            name="FuelConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_dynamic", models.BooleanField(default=False)),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "ratio",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=7),
                ),
                (
                    "surcharge_percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=7,
                        verbose_name="Flat Surcharge %",
                    ),
                ),
            ],
            options={
                "db_table": "courier_fuel_configs",
            },
        ),
        migrations.CreateModel(
            name="RoutingLogic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "logic_type",
                    models.CharField(
                        choices=[
                            ("Zonal_Standard", "Zonal (Standard A-F)"),
                            ("Zonal_Custom", "Zonal (Custom Matrix)"),
                            ("City_To_City", "City to City"),
                            ("Region_CSV", "Regional CSV"),
                        ],
                        default="Zonal_Standard",
                        max_length=20,
                    ),
                ),
                (
                    "serviceable_pincode_csv",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("hub_city", models.CharField(blank=True, max_length=100, null=True)),
                ("hub_pincode_prefixes", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "courier_routing_logics",
            },
        ),
        migrations.CreateModel(
            name="ServiceConstraints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("min_weight", models.FloatField(default=0.5, help_text="Min weight in kg")),
                ("max_weight", models.FloatField(default=99999.0, help_text="Max weight in kg")),
                ("volumetric_divisor", models.IntegerField(default=5000)),
                ("required_source_city", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "courier_service_constraints",
            },
        ),
        migrations.AddField(
            model_name="courier",
            name="fees",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courier",
                to="courier.feestructure",
            ),
        ),
        migrations.AddField(
            model_name="courier",
            name="fuel_config",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courier",
                to="courier.fuelconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="courier",
            name="routing",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courier",
                to="courier.routinglogic",
            ),
        ),
        migrations.AddField(
            model_name="courier",
            name="constraints",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courier",
                to="courier.serviceconstraints",
            ),
        ),
    ]
