# Generated by Django 5.2.8 on 2026-01-08 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0025_feestructure_fuelconfiguration_routinglogic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courier",
            name="constraints",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fees",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fuel_config",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="routing",
        ),
        migrations.AddField(
            model_name="feestructure",
            name="courier_link",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fees_config",
                to="courier.courier",
            ),
        ),
        migrations.AddField(
            model_name="fuelconfiguration",
            name="courier_link",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fuel_config_obj",
                to="courier.courier",
            ),
        ),
        migrations.AddField(
            model_name="routinglogic",
            name="courier_link",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routing_config",
                to="courier.courier",
            ),
        ),
        migrations.AddField(
            model_name="serviceconstraints",
            name="courier_link",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constraints_config",
                to="courier.courier",
            ),
        ),
    ]
