# Generated by Django 5.2.8 on 2026-01-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0026_remove_courier_constraints_remove_courier_fees_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courier",
            name="appointment_delivery_fee",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="cod_charge_fixed",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="cod_charge_percent",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="damage_claim_percent",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="docket_fee",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="eway_bill_fee",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fov_insured_percent",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fov_min",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fov_uninsured_percent",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fuel_base_price",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fuel_is_dynamic",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fuel_ratio",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="fuel_surcharge_percent",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="hamali_per_kg",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="hub_city",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="hub_pincode_prefixes",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="max_weight",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="min_hamali",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="min_weight",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="rate_logic",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="required_source_city",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="serviceable_pincode_csv",
        ),
        migrations.RemoveField(
            model_name="courier",
            name="volumetric_divisor",
        ),
    ]
