# Generated by Django 5.2.8 on 2026-01-10 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0027_remove_courier_appointment_delivery_fee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pincode",
            fields=[
                ("pincode", models.IntegerField(primary_key=True, serialize=False)),
                ("office_name", models.CharField(db_index=True, max_length=100)),
                ("pincode_type", models.CharField(blank=True, max_length=50, null=True)),
                ("district", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("is_serviceable", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pincode_master",
                "indexes": [
                    models.Index(fields=["state", "district"], name="pincode_mas_state_5df53e_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceablePincode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pincode", models.IntegerField(db_index=True)),
                ("region_code", models.CharField(blank=True, max_length=50, null=True)),
                ("is_edl", models.BooleanField(default=False)),
                (
                    "edl_distance",
                    models.FloatField(default=0.0, help_text="Distance for EDL calculation"),
                ),
                ("is_cod_available", models.BooleanField(default=True)),
                ("is_prepaid_available", models.BooleanField(default=True)),
                ("is_pickup_available", models.BooleanField(default=True)),
                (
                    "is_embargo",
                    models.BooleanField(
                        default=False, help_text="If true, service is blocked (embargo)"
                    ),
                ),
                (
                    "city_name",
                    models.CharField(
                        blank=True,
                        help_text="Mapped City for City-to-City logic",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serviceable_pincodes",
                        to="courier.courier",
                    ),
                ),
            ],
            options={
                "db_table": "serviceable_pincodes",
                "indexes": [
                    models.Index(
                        fields=["courier", "pincode"], name="serviceable_courier_f3f003_idx"
                    ),
                    models.Index(
                        fields=["courier", "city_name"], name="serviceable_courier_e96149_idx"
                    ),
                ],
                "unique_together": {("courier", "pincode")},
            },
        ),
    ]
