# Generated by Django 5.2.8 on 2026-01-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0028_pincode_serviceablepincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="aggregator",
            field=models.CharField(
                choices=[
                    ("Shipdaak", "Shipdaak"),
                    ("RapidShyp", "RapidShyp"),
                    ("Standalone", "Standalone"),
                ],
                default="Shipdaak",
                help_text="The aggregator providing this service.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="courier",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Clean name (e.g. 'Shadowfax'). Combined with aggregator for full name.",
                max_length=100,
            ),
        ),
    ]
