# Generated by Django 5.2.8 on 2026-01-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0029_courier_aggregator_courier_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="service_category",
            field=models.CharField(
                choices=[
                    ("Surface", "Surface"),
                    ("Air", "Air"),
                    ("Heavy Surface", "Heavy Surface"),
                    ("Documents", "Documents"),
                    ("NDD Surface", "NDD Surface"),
                    ("NDD Heavy Surface", "NDD Heavy Surface"),
                    ("RVP", "RVP (Reverse Pickup)"),
                ],
                default="Surface",
                help_text="Service category (Surface, Air, Heavy, Documents, NDD, RVP)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="courierzonerate",
            name="rate_type",
            field=models.CharField(
                choices=[
                    ("forward", "Forward Rate"),
                    ("additional", "Additional Rate"),
                    ("rto", "RTO Rate"),
                    ("rto_additional", "RTO Additional Rate"),
                    ("reverse", "Reverse Rate"),
                    ("reverse_additional", "Reverse Additional Rate"),
                ],
                default="forward",
                max_length=20,
            ),
        ),
    ]
