# Generated by Django 5.2.8 on 2026-01-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0030_courier_service_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FTLRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_city", models.CharField(db_index=True, max_length=100)),
                ("destination_city", models.CharField(db_index=True, max_length=100)),
                (
                    "truck_type",
                    models.CharField(
                        choices=[
                            ("20FT", "20FT"),
                            ("32 FT SXL 7MT", "32 FT SXL 7MT"),
                            ("32 FT SXL 9MT", "32 FT SXL 9MT"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Rate (₹)"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FTL Rate",
                "verbose_name_plural": "FTL Rates",
                "db_table": "ftl_rates",
                "ordering": ["source_city", "destination_city"],
            },
        ),
        migrations.RemoveIndex(
            model_name="ftlorder",
            name="ftl_orders_order_n_a2381b_idx",
        ),
        migrations.RemoveIndex(
            model_name="ftlorder",
            name="ftl_orders_status_2a0853_idx",
        ),
        migrations.RemoveIndex(
            model_name="ftlorder",
            name="ftl_orders_created_5a45a3_idx",
        ),
        migrations.AlterUniqueTogether(
            name="ftlrate",
            unique_together={("source_city", "destination_city", "truck_type")},
        ),
    ]
