# Generated by Django 5.2.8 on 2026-01-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0031_ftlrate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoneRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="City or State name (lowercase)", max_length=100),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("metro_city", "Metro City (Zone A)"),
                            ("special_state", "Special State (Zone E)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Zone Rule",
                "verbose_name_plural": "Zone Rules (Metros & Special States)",
                "db_table": "zone_rules",
                "unique_together": {("name", "rule_type")},
            },
        ),
    ]
