# Generated by Django 5.2.8 on 2026-01-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0032_zonerule"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        db_index=True,
                        help_text="The variation (e.g. 'blr', 'bombay')",
                        max_length=100,
                    ),
                ),
                (
                    "standard_name",
                    models.CharField(
                        help_text="The standard name (e.g. 'bangalore', 'mumbai')", max_length=100
                    ),
                ),
                (
                    "category",
                    models.CharField(choices=[("city", "City"), ("state", "State")], max_length=50),
                ),
            ],
            options={
                "verbose_name": "Location Alias",
                "verbose_name_plural": "Location Aliases",
                "db_table": "location_aliases",
                "indexes": [
                    models.Index(fields=["alias", "category"], name="location_al_alias_bd0c39_idx")
                ],
                "unique_together": {("alias", "category")},
            },
        ),
    ]
