# Generated by Django 5.2.8 on 2026-02-27 10:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0033_locationalias"),
    ]

    operations = [
        migrations.AddField(
            model_name="feestructure",
            name="other_charges",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Other Charges",
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="carrier_type",
            field=models.CharField(
                choices=[("B2C", "B2C"), ("B2B", "B2B")], default="B2C", max_length=20
            ),
        ),
    ]
