# Generated by Django 5.2.8 on 2026-03-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0034_feestructure_other_charges_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="shipdaak_courier_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Shipdaak v2 courier ID used for booking payloads.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("contact_name", models.CharField(max_length=150)),
                ("contact_no", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("address_2", models.TextField(blank=True, null=True)),
                ("pincode", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("gst_number", models.CharField(blank=True, max_length=30, null=True)),
                ("shipdaak_pickup_id", models.IntegerField(blank=True, null=True)),
                ("shipdaak_rto_id", models.IntegerField(blank=True, null=True)),
                ("shipdaak_synced_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "warehouses",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="external_order_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="External WMS order ID used by Shipdaak v2 booking.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipdaak_label_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipdaak_shipment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="courier.warehouse",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["external_order_id"], name="orders_external_order_id_idx"),
        ),
    ]
