# Generated by Django 5.2.8 on 2026-03-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0035_shipdaak_warehouse_and_order_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="order",
            new_name="orders_externa_1cd7d5_idx",
            old_name="orders_external_order_id_idx",
        ),
        migrations.AddField(
            model_name="order",
            name="shipdaak_order_id",
            field=models.IntegerField(
                blank=True,
                help_text="ShipDaak orderId set when the order is registered in ShipDaak (before AWB).",
                null=True,
            ),
        ),
    ]
