# Generated by Django 5.2.7 on 2025-10-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20)),
                ('billing_month', models.DateField()),
                ('v_fixed_storage_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('v_additional_storage_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('v_storage_type', models.CharField(blank=True, choices=[('Sq Ft', 'Square Feet'), ('Lumpsum', 'Lumpsum')], max_length=20, null=True)),
                ('v_storage_days', models.IntegerField(blank=True, null=True)),
                ('v_storage_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('v_storage_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('v_storage_remarks', models.TextField(blank=True, null=True)),
                ('v_handling_in_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('v_handling_in_unit', models.CharField(blank=True, choices=[('Boxes', 'Boxes'), ('Tons', 'Tons'), ('Pieces', 'Pieces')], max_length=20, null=True)),
                ('v_handling_in_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('v_handling_in_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('v_handling_in_remarks', models.TextField(blank=True, null=True)),
                ('v_handling_out_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('v_handling_out_unit', models.CharField(blank=True, choices=[('Boxes', 'Boxes'), ('Tons', 'Tons'), ('Pieces', 'Pieces')], max_length=20, null=True)),
                ('v_handling_out_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('v_handling_out_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('v_handling_out_remarks', models.TextField(blank=True, null=True)),
                ('v_transport_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('v_transport_remarks', models.TextField(blank=True, null=True)),
                ('v_misc_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('v_misc_remarks', models.TextField(blank=True, null=True)),
                ('v_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('c_fixed_storage_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('c_additional_storage_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('c_storage_type', models.CharField(blank=True, choices=[('Sq Ft', 'Square Feet'), ('Lumpsum', 'Lumpsum')], max_length=20, null=True)),
                ('c_storage_days', models.IntegerField(blank=True, null=True)),
                ('c_storage_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('c_storage_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('c_storage_remarks', models.TextField(blank=True, null=True)),
                ('c_handling_in_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('c_handling_in_unit', models.CharField(blank=True, choices=[('Boxes', 'Boxes'), ('Tons', 'Tons'), ('Pieces', 'Pieces')], max_length=20, null=True)),
                ('c_handling_in_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('c_handling_in_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('c_handling_in_remarks', models.TextField(blank=True, null=True)),
                ('c_handling_out_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('c_handling_out_unit', models.CharField(blank=True, choices=[('Boxes', 'Boxes'), ('Tons', 'Tons'), ('Pieces', 'Pieces')], max_length=20, null=True)),
                ('c_handling_out_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('c_handling_out_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('c_handling_out_remarks', models.TextField(blank=True, null=True)),
                ('c_transport_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('c_transport_remarks', models.TextField(blank=True, null=True)),
                ('c_misc_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('c_misc_remarks', models.TextField(blank=True, null=True)),
                ('c_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('margin_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('margin_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('mis_link', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_statements',
                'ordering': ['-billing_month'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OperationsDailyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20)),
                ('operation_date', models.DateField()),
                ('space_utilization', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (0-100)', max_digits=5, null=True)),
                ('inventory_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('outstanding_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'operations_daily_update',
                'ordering': ['-operation_date'],
                'managed': True,
            },
        ),
    ]
