# Generated by Django 5.2.7 on 2025-10-29 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period', models.CharField(max_length=20)),
                ('escalation_date', models.DateField()),
                ('dispute_type', models.CharField(choices=[('storage_space', 'Storage Space'), ('manpower_ot', 'Manpower/OT'), ('handling', 'Handling'), ('other', 'Other')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('work_in_progress', 'Work in Progress'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('dec_bills_sent_to_accounts', models.BooleanField(default=False)),
                ('mail_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_queries_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_queries', to='projects.projectcode')),
                ('to_be_resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_queries_assigned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-escalation_date'],
            },
        ),
        migrations.CreateModel(
            name='DailySpaceUtilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('space_utilized', models.DecimalField(decimal_places=2, help_text="Space used based on project's billing unit", max_digits=10)),
                ('inventory_value', models.DecimalField(decimal_places=2, help_text='Total inventory value in ₹', max_digits=15)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_entries_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_entries_modified', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='projects.projectcode')),
            ],
            options={
                'verbose_name': 'Daily Space Utilization',
                'verbose_name_plural': 'Daily Space Utilizations',
                'ordering': ['-entry_date', 'project'],
            },
        ),
        migrations.CreateModel(
            name='DailyEntryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated')], max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField()),
                ('change_reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('daily_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='operations.dailyspaceutilization')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('dispute_type', models.CharField(choices=[('storage_space', 'Storage Space'), ('mis_stock_issue', 'MIS / Stock Issue'), ('operations', 'Operations'), ('manpower_ot', 'Manpower/OT'), ('handling', 'Handling'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('work_in_progress', 'Work in Progress'), ('dispute', 'Dispute'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('tat_days', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
                ('operation_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_handled', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='projects.projectcode')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=200)),
                ('holiday_date', models.DateField()),
                ('holiday_name', models.CharField(max_length=200)),
                ('is_national', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-holiday_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyMISLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('mis_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_logs', to='projects.projectcode')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_logs_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-log_date'],
                'unique_together': {('project', 'log_date')},
            },
        ),
        migrations.AddIndex(
            model_name='dailyspaceutilization',
            index=models.Index(fields=['project', 'entry_date'], name='operations__project_f94d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyspaceutilization',
            index=models.Index(fields=['entry_date'], name='operations__entry_d_748901_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouseholiday',
            unique_together={('warehouse_name', 'holiday_date')},
        ),
    ]
