# Generated by Django 5.2.7 on 2025-10-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_billingquery_dailyspaceutilization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingquery',
            options={'ordering': ['-escalation_date'], 'verbose_name': 'Billing Query', 'verbose_name_plural': 'Billing Queries'},
        ),
        migrations.AlterModelOptions(
            name='dailyentryauditlog',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Daily Entry Audit Log', 'verbose_name_plural': 'Daily Entry Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='dailymislog',
            options={'ordering': ['-log_date', 'project'], 'verbose_name': 'Daily MIS Log', 'verbose_name_plural': 'Daily MIS Logs'},
        ),
        migrations.AlterModelOptions(
            name='disputelog',
            options={'ordering': ['-issue_date'], 'verbose_name': 'Dispute Log', 'verbose_name_plural': 'Dispute Logs'},
        ),
        migrations.AlterModelOptions(
            name='warehouseholiday',
            options={'ordering': ['-holiday_date'], 'verbose_name': 'Warehouse Holiday', 'verbose_name_plural': 'Warehouse Holidays'},
        ),
        migrations.AlterField(
            model_name='billingquery',
            name='billing_period',
            field=models.CharField(help_text="e.g., Oct'24, Nov'24", max_length=20),
        ),
        migrations.AlterField(
            model_name='billingquery',
            name='dispute_type',
            field=models.CharField(choices=[('storage_space', 'Storage Space'), ('manpower_ot', 'Manpower/OT'), ('handling', 'Handling'), ('workstation', 'Work station'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='tat_days',
            field=models.IntegerField(blank=True, help_text='Turn Around Time in days', null=True),
        ),
        migrations.AlterField(
            model_name='warehouseholiday',
            name='holiday_name',
            field=models.CharField(help_text='e.g., Diwali, Christmas', max_length=200),
        ),
        migrations.AlterField(
            model_name='warehouseholiday',
            name='is_national',
            field=models.BooleanField(default=False, help_text='Applies to all warehouses'),
        ),
        migrations.AlterField(
            model_name='warehouseholiday',
            name='warehouse_name',
            field=models.CharField(help_text='Warehouse/Location name', max_length=200),
        ),
    ]
