# Generated by Django 5.2.7 on 2025-10-30 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_billingquery_options_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingquery',
            options={'ordering': ['-raised_at'], 'verbose_name': 'Billing Query', 'verbose_name_plural': 'Billing Queries'},
        ),
        migrations.AlterModelOptions(
            name='disputelog',
            options={'ordering': ['-raised_at'], 'verbose_name': 'Dispute Log', 'verbose_name_plural': 'Dispute Logs'},
        ),
        migrations.AlterUniqueTogether(
            name='warehouseholiday',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='billingquery',
            name='id',
        ),
        migrations.RemoveField(
            model_name='disputelog',
            name='id',
        ),
        migrations.AddField(
            model_name='billingquery',
            name='actual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='billingquery',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_queries_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingquery',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description'),
        ),
        migrations.AddField(
            model_name='billingquery',
            name='expected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='billingquery',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='billingquery',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingquery',
            name='query_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='billingquery',
            name='query_type',
            field=models.CharField(choices=[('invoice_discrepancy', 'Invoice Discrepancy'), ('rate_clarification', 'Rate Clarification'), ('space_calculation', 'Space Calculation'), ('payment_status', 'Payment Status'), ('other', 'Other')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingquery',
            name='raised_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='billingquery',
            name='raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_queries_raised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingquery',
            name='resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='billingquery',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingquery',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_queries_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingquery',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Brief subject', max_length=200),
        ),
        migrations.AddField(
            model_name='disputelog',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputelog',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description'),
        ),
        migrations.AddField(
            model_name='disputelog',
            name='dispute_date',
            field=models.DateField(blank=True, help_text='When the issue occurred', null=True),
        ),
        migrations.AddField(
            model_name='disputelog',
            name='dispute_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='disputelog',
            name='disputed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in dispute (if applicable)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='disputelog',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='disputelog',
            name='raised_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='disputelog',
            name='raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes_raised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputelog',
            name='resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disputelog',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disputelog',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputelog',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Brief summary of dispute', max_length=200),
        ),
        migrations.AddField(
            model_name='warehouseholiday',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='holidays_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouseholiday',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='warehouseholiday',
            name='holiday_type',
            field=models.CharField(choices=[('national', 'National Holiday'), ('regional', 'Regional Holiday'), ('warehouse_closure', 'Warehouse Closure'), ('project_specific', 'Project Specific')], default='national', max_length=20),
        ),
        migrations.AddField(
            model_name='warehouseholiday',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Leave blank for warehouse-wide holidays', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='projects.projectcode'),
        ),
        migrations.AddField(
            model_name='warehouseholiday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billingquery',
            name='billing_period',
            field=models.DateField(blank=True, help_text='Billing month', null=True),
        ),
        migrations.AlterField(
            model_name='billingquery',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_queries_created_legacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billingquery',
            name='dispute_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='billingquery',
            name='escalation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingquery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingquery',
            name='to_be_resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_queries_assigned_legacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='dispute_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes_resolved_legacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='operation_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes_handled_legacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='severity',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='tat_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseholiday',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holidays_added_legacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehouseholiday',
            name='holiday_name',
            field=models.CharField(help_text='e.g., Diwali, Christmas, Maintenance Day', max_length=200),
        ),
        migrations.AlterField(
            model_name='warehouseholiday',
            name='is_national',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Use holiday_type instead'),
        ),
        migrations.AlterField(
            model_name='warehouseholiday',
            name='warehouse_name',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use project instead', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='dailyspaceutilization',
            unique_together={('project', 'entry_date')},
        ),
        migrations.CreateModel(
            name='BillingQueryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='operations.billingquery')),
            ],
            options={
                'ordering': ['commented_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='operations.disputelog')),
            ],
            options={
                'ordering': ['commented_at'],
            },
        ),
    ]
