# Generated by Django 5.2.7 on 2025-11-01 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_billingquery_options_alter_disputelog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('coordinator_reminder', 'Coordinator Reminder'), ('manager_notification', 'Manager Notification'), ('system_alert', 'System Alert')], db_index=True, max_length=30)),
                ('title', models.CharField(help_text='Brief alert title', max_length=200)),
                ('message', models.TextField(help_text='Detailed alert message')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether user has read this alert')),
                ('related_url', models.CharField(blank=True, help_text='Optional link to relevant page', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When user marked alert as read', null=True)),
                ('user', models.ForeignKey(help_text='User who receives this alert', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'In-App Alert',
                'verbose_name_plural': 'In-App Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='operations__user_id_2d42b4_idx'), models.Index(fields=['user', '-created_at'], name='operations__user_id_7987fc_idx')],
            },
        ),
    ]
