# Generated by Django 5.2.7 on 2025-11-06 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_inappalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingquerycomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='disputecomment',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='billingquerycomment',
            old_name='commented_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='disputecomment',
            old_name='commented_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='billingquerycomment',
            name='commented_by',
        ),
        migrations.RemoveField(
            model_name='disputecomment',
            name='commented_by',
        ),
        migrations.AddField(
            model_name='billingquerycomment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='query_attachments/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='billingquerycomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='billingquerycomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='query_comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disputecomment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='dispute_attachments/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='disputecomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='disputecomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dispute_comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='billingquerycomment',
            table='billing_query_comments',
        ),
        migrations.AlterModelTable(
            name='disputecomment',
            table='dispute_comments',
        ),
        migrations.CreateModel(
            name='BillingQueryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('commented', 'Commented'), ('attachment_added', 'Attachment Added'), ('resolved', 'Resolved')], max_length=50)),
                ('description', models.TextField()),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='operations.billingquery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Billing Query Activities',
                'db_table': 'billing_query_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('priority_changed', 'Priority Changed'), ('commented', 'Commented'), ('attachment_added', 'Attachment Added'), ('resolved', 'Resolved')], max_length=50)),
                ('description', models.TextField()),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='operations.disputelog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dispute Activities',
                'db_table': 'dispute_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
