# Generated by Django 5.2.7 on 2025-11-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_billingquerycomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyspaceutilization',
            name='gw_inventory',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Auto-calculated: inventory_value * 1.30 (GW markup)', max_digits=15, null=True),
        ),
    ]
