# Generated by Django 5.2.7 on 2025-11-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_add_gw_inventory_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputelog',
            name='category',
            field=models.CharField(choices=[('storage_space', 'Storage Space'), ('handling', 'Handling'), ('manpower_ot', 'Manpower/OT'), ('operations', 'Operations'), ('mis_stock', 'MIS / Stock Issue'), ('billing', 'Billing Issue')], default='operations', help_text='Type of dispute', max_length=30),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('dispute', 'Dispute')], default='open', max_length=20),
        ),
    ]
