# Generated by Django 5.2.7 on 2025-11-09 10:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_update_dispute_categories_and_status'),
        ('projects', '0008_add_notice_period_duration_and_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('weight_based', 'Weight-Based'), ('unit_based', 'Unit-Based (Box, Pallet, etc)'), ('container', 'Container-Based'), ('service', 'Service-Based (Labour, Equipment)')], max_length=20, unique=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Handling Type Category',
                'verbose_name_plural': 'Handling Type Categories',
                'ordering': ['display_order', 'category_name'],
            },
        ),
        migrations.CreateModel(
            name='HandlingTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(help_text="Unique code for this handling type (e.g., '0_10_kg_b2b')", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text="Display name shown in UI (e.g., '0-10 KG B2B')", max_length=100)),
                ('min_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum weight in KG (for weight-based types)', max_digits=10, null=True)),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight in KG (for weight-based types)', max_digits=10, null=True)),
                ('applicable_to', models.CharField(choices=[('b2b', 'B2B Only'), ('b2c', 'B2C Only'), ('both', 'Both B2B & B2C'), ('na', 'Not Applicable')], default='na', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handling_types', to='operations.handlingtypecategory')),
            ],
            options={
                'verbose_name': 'Handling Type Master',
                'verbose_name_plural': 'Handling Types Master',
                'ordering': ['category__display_order', 'min_weight_kg', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_start_date', models.DateField(help_text='Client agreement start date')),
                ('agreement_end_date', models.DateField(help_text='Client agreement end date')),
                ('yearly_escalation_date', models.DateField(help_text='Annual escalation date')),
                ('annual_escalation_percent', models.DecimalField(decimal_places=2, help_text='Annual escalation percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('security_deposit', models.DecimalField(decimal_places=2, help_text='Security deposit amount in ₹', max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_cards_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rate_cards_modified', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='projects.projectcode')),
            ],
            options={
                'verbose_name': 'Rate Card',
                'verbose_name_plural': 'Rate Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValueAddedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_for', models.CharField(choices=[('client', 'Client Commercial'), ('vendor', 'Vendor Commercial')], max_length=10)),
                ('service_name', models.CharField(help_text="Service name (e.g., 'Labelling', 'Repacking', 'QC')", max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate in ₹', max_digits=10)),
                ('unit', models.CharField(help_text="Unit (e.g., 'per piece', 'per roll', 'per day')", max_length=50)),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vas_rates', to='operations.ratecard')),
            ],
            options={
                'verbose_name': 'Value Added Service',
                'verbose_name_plural': 'Value Added Services',
                'ordering': ['service_name'],
            },
        ),
        migrations.CreateModel(
            name='HandlingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_for', models.CharField(choices=[('client', 'Client Commercial'), ('vendor', 'Vendor Commercial')], max_length=10)),
                ('direction', models.CharField(choices=[('inbound', 'Inward/Unloading'), ('outbound', 'Outward/Loading')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate in ₹', max_digits=10)),
                ('handling_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.handlingtypemaster')),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handling_rates', to='operations.ratecard')),
            ],
            options={
                'verbose_name': 'Handling Rate',
                'verbose_name_plural': 'Handling Rates',
                'ordering': ['handling_type__category', 'handling_type__display_name'],
                'unique_together': {('rate_card', 'handling_type', 'direction', 'rate_for')},
            },
        ),
        migrations.CreateModel(
            name='StorageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_for', models.CharField(choices=[('client', 'Client Commercial'), ('vendor', 'Vendor Commercial')], max_length=10)),
                ('minimum_billable_area', models.DecimalField(decimal_places=2, help_text='Minimum billable area/units', max_digits=10)),
                ('space_type', models.CharField(choices=[('sqft', 'Sq. Ft.'), ('pallet', 'Pallet'), ('lumpsum', 'Lumpsum')], max_length=10)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, help_text='Rate per unit (Sq.Ft/Pallet/Lumpsum)', max_digits=10)),
                ('monthly_billable_amount', models.DecimalField(decimal_places=2, help_text='Monthly billable amount', max_digits=15)),
                ('saas_minimum_area', models.DecimalField(blank=True, decimal_places=2, help_text='SAAS minimum billable area (if different)', max_digits=10, null=True)),
                ('saas_rate', models.DecimalField(blank=True, decimal_places=2, help_text='SAAS rate per unit (if applicable)', max_digits=10, null=True)),
                ('saas_monthly_amount', models.DecimalField(blank=True, decimal_places=2, help_text='SAAS monthly amount (if applicable)', max_digits=15, null=True)),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_rates', to='operations.ratecard')),
            ],
            options={
                'verbose_name': 'Storage Rate',
                'verbose_name_plural': 'Storage Rates',
                'unique_together': {('rate_card', 'rate_for')},
            },
        ),
    ]
