# Generated by Django 5.2.7 on 2025-11-09 15:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_add_rate_card_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handlingtypemaster',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='handlingrate',
            options={'ordering': ['direction', 'channel', 'base_type', 'min_weight_kg'], 'verbose_name': 'Handling Rate', 'verbose_name_plural': 'Handling Rates'},
        ),
        migrations.AlterModelOptions(
            name='valueaddedservice',
            options={'ordering': ['service_type'], 'verbose_name': 'Value Added Service', 'verbose_name_plural': 'Value Added Services'},
        ),
        migrations.AlterUniqueTogether(
            name='handlingrate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='storagerate',
            name='rate_per_unit',
        ),
        migrations.RemoveField(
            model_name='storagerate',
            name='saas_monthly_amount',
        ),
        migrations.RemoveField(
            model_name='valueaddedservice',
            name='service_name',
        ),
        migrations.AddField(
            model_name='handlingrate',
            name='base_type',
            field=models.CharField(choices=[('weight_slab', 'Weight Slab (KG)'), ('per_kg', 'Per KG'), ('per_tonne', 'Per Tonne/MT'), ('per_box', 'Per Box/Unit'), ('per_pallet', 'Per Pallet'), ('per_panel', 'Per Panel'), ('per_roll', 'Per Roll'), ('per_piece', 'Per Piece'), ('per_bag', 'Per Bag'), ('per_item', 'Per Item'), ('per_drum', 'Per Drum'), ('per_bundle', 'Per Bundle'), ('per_case', 'Per Case'), ('20ft_container', '20FT Container'), ('40ft_container', '40FT Container'), ('per_container', 'Per Container'), ('per_order', 'Per Order'), ('per_line_item', 'Per Line Item'), ('per_unit_in_order', 'Per Unit in Order')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handlingrate',
            name='channel',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('both', 'Both'), ('na', 'N/A')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handlingrate',
            name='condition',
            field=models.CharField(blank=True, choices=[('', 'No Condition'), ('upto_weight', 'Up to Weight'), ('loose_handling', 'Loose Handling'), ('visible_qc', 'With Visible QC'), ('putaway_included', 'Putaway Included'), ('pick_pack_included', 'Pick & Pack Included'), ('additional_item', 'Additional Item'), ('post_n_units', 'Post N Units'), ('if_required', 'If Required'), ('per_activity', 'Per Activity'), ('with_qc', 'With QC')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='handlingrate',
            name='condition_value',
            field=models.CharField(blank=True, help_text="Additional condition details (e.g., '20 units', '3 line items')", max_length=100),
        ),
        migrations.AddField(
            model_name='handlingrate',
            name='max_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight in KG', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='handlingrate',
            name='min_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum weight in KG', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='has_fixed_escalation',
            field=models.BooleanField(default=True, help_text='True = Fixed %, False = Mutually Agreed'),
        ),
        migrations.AddField(
            model_name='storagerate',
            name='flat_rate_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flat rate per unit (for non-slab pricing)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='storagerate',
            name='is_slab_based',
            field=models.BooleanField(default=False, help_text='True = Slab pricing (10-15% cases), False = Flat rate (85-90% cases)'),
        ),
        migrations.AddField(
            model_name='valueaddedservice',
            name='service_description',
            field=models.CharField(blank=True, help_text='Additional service details', max_length=200),
        ),
        migrations.AddField(
            model_name='valueaddedservice',
            name='service_type',
            field=models.CharField(choices=[('forklift', 'Forklift'), ('hydra', 'Hydra'), ('equipment_rental', 'Equipment Rental'), ('kitting', 'Kitting'), ('repacking', 'Repacking'), ('labelling', 'Labelling/Stickering'), ('barcoding', 'Barcoding'), ('scanning', 'Scanning'), ('qc_inspection', 'QC/Inspection'), ('knitting', 'Knitting'), ('wrapping', 'Bubble Wrapping/Shrink Wrapping'), ('order_processing', 'Order Processing'), ('pick_pack', 'Pick & Pack'), ('fba_prep', 'FBA Preparation'), ('wms', 'WMS Charges'), ('oms', 'OMS/Order Management'), ('inciflo', 'Inciflo'), ('scan_software', 'Scan-Based Software'), ('crossing', 'Vehicle to Vehicle Crossing'), ('adhoc_labour', 'Adhoc Labour'), ('documentation', 'Documentation'), ('thank_you_note', 'Thank You Note Insertion')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Unloading/Inward'), ('outbound', 'Loading/Outward'), ('both', 'Both (Per Activity)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ratecard',
            name='annual_escalation_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual escalation percentage (if fixed)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='minimum_billable_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum billable area/units (for flat rate)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='monthly_billable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly billable amount (for flat rate)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='saas_minimum_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='SAAS minimum billable area', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='saas_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='SAAS rate per unit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Rate in ₹ (leave blank for 'At Actual')", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='rate_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vas_services', to='operations.ratecard'),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='unit',
            field=models.CharField(choices=[('per_hour', 'Per Hour'), ('per_day', 'Per Day'), ('per_month', 'Per Month'), ('per_unit', 'Per Unit'), ('per_piece', 'Per Piece'), ('per_box', 'Per Box'), ('per_order', 'Per Order'), ('per_label', 'Per Label'), ('per_scan', 'Per Scan'), ('per_item', 'Per Item'), ('per_person', 'Per Person'), ('lumpsum', 'Lump Sum'), ('at_actual', 'At Actual')], max_length=20),
        ),
        migrations.CreateModel(
            name='InfrastructureCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_for', models.CharField(choices=[('client', 'Client Commercial'), ('vendor', 'Vendor Commercial')], max_length=10)),
                ('cost_type', models.CharField(choices=[('rent', 'Rent & Infrastructure'), ('security', 'Security Guard'), ('management_fee', 'Management Fees'), ('manpower_fixed', 'Manpower (Fixed)'), ('desk_sitting', 'Desk Sitting Charges'), ('electricity', 'Electricity'), ('broadband', 'Broadband/Telephone'), ('housekeeping', 'House Keeping'), ('stationery', 'Stationery/PPE'), ('table_equipment', 'Table/Equipment (Amortized)'), ('pallet_cost', 'Pallet Cost'), ('monthly_project_cost', 'Monthly Project Cost'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(help_text="Cost description (e.g., 'Security - Day & Night', 'Manpower - One')", max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monthly cost in ₹', max_digits=15)),
                ('is_at_actual', models.BooleanField(default=False, help_text="True if cost is 'At Actual' (amount is estimate)")),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_costs', to='operations.ratecard')),
            ],
            options={
                'verbose_name': 'Infrastructure Cost',
                'verbose_name_plural': 'Infrastructure Costs',
                'ordering': ['cost_type'],
            },
        ),
        migrations.CreateModel(
            name='StorageRateSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_area', models.DecimalField(decimal_places=2, help_text='From area (e.g., 0, 1001, 1501)', max_digits=10)),
                ('to_area', models.DecimalField(blank=True, decimal_places=2, help_text="To area (e.g., 1000, 1500, 2000). Leave blank for '2001+'", max_digits=10, null=True)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, help_text='Rate per unit for this slab', max_digits=10)),
                ('storage_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='operations.storagerate')),
            ],
            options={
                'verbose_name': 'Storage Rate Slab',
                'verbose_name_plural': 'Storage Rate Slabs',
                'ordering': ['from_area'],
            },
        ),
        migrations.DeleteModel(
            name='HandlingTypeCategory',
        ),
        migrations.RemoveField(
            model_name='handlingrate',
            name='handling_type',
        ),
        migrations.DeleteModel(
            name='HandlingTypeMaster',
        ),
    ]
