# Generated by Django 5.2.7 on 2025-11-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_complete_rate_card_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagerate',
            name='saas_minimum_area',
        ),
        migrations.RemoveField(
            model_name='storagerate',
            name='saas_rate',
        ),
        migrations.AddField(
            model_name='handlingrate',
            name='remarks',
            field=models.CharField(blank=True, help_text='Additional remarks to explain the condition or special terms', max_length=200),
        ),
        migrations.AddField(
            model_name='storagerate',
            name='saas_monthly_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='SAAS fixed monthly charge (software charge, not area-based)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='channel',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C')], max_length=10),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Unloading/Inward'), ('outbound', 'Loading/Outward')], max_length=10),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='service_type',
            field=models.CharField(choices=[('forklift', 'Forklift'), ('hydra', 'Hydra'), ('equipment_rental', 'Equipment Rental'), ('kitting', 'Kitting'), ('repacking', 'Repacking'), ('labelling', 'Labelling/Stickering'), ('barcoding', 'Barcoding'), ('scanning', 'Scanning'), ('qc_inspection', 'QC/Inspection'), ('knitting', 'Knitting'), ('wrapping', 'Bubble Wrapping/Shrink Wrapping'), ('order_processing', 'Order Processing'), ('pick_pack', 'Pick & Pack'), ('fba_prep', 'FBA Preparation'), ('wms', 'WMS Charges'), ('oms', 'OMS/Order Management'), ('inciflo', 'Inciflo'), ('scan_software', 'Scan-Based Software'), ('crossing', 'Vehicle to Vehicle Crossing'), ('adhoc_labour', 'Adhoc Labour'), ('documentation', 'Documentation')], max_length=30),
        ),
    ]
