# Generated by Django 5.2.7 on 2025-11-10 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_fix_saas_and_add_remarks'),
        ('projects', '0008_add_notice_period_duration_and_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhocBillingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('extra_storage', 'Extra Storage Space'), ('extra_manpower', 'Extra Manpower'), ('extra_handling', 'Extra Handling Charges'), ('vas', 'Value Added Services'), ('transport', 'Transport Charges'), ('equipment', 'Equipment Rental'), ('other', 'Other')], max_length=20)),
                ('event_date', models.DateField(help_text='Date when the chargeable event occurred')),
                ('description', models.TextField(help_text='Detailed description of the charge')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Quantity (if applicable)', max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, help_text='Unit (e.g., sq.ft., hours, boxes, trips)', max_length=50)),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated amount in ₹ (optional)', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending (To Be Billed)'), ('billed', 'Billed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('billing_month', models.DateField(help_text='Month for which this should be billed (YYYY-MM-01 format)')),
                ('billing_remarks', models.TextField(blank=True, help_text='Remarks for billing team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhoc_entries_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_billing_entries', to='projects.projectcode')),
            ],
            options={
                'verbose_name': 'Adhoc Billing Entry',
                'verbose_name_plural': 'Adhoc Billing Entries',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdhocBillingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='adhoc_billing/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='operations.adhocbillingentry')),
            ],
            options={
                'verbose_name': 'Adhoc Billing Attachment',
                'verbose_name_plural': 'Adhoc Billing Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='adhocbillingentry',
            index=models.Index(fields=['project', 'event_date'], name='operations__project_ea6c70_idx'),
        ),
        migrations.AddIndex(
            model_name='adhocbillingentry',
            index=models.Index(fields=['billing_month', 'status'], name='operations__billing_5c4958_idx'),
        ),
    ]
