# Generated by Django 5.2.7 on 2025-11-11 18:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_add_adhoc_billing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementRenewalTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_email_sent', models.DateField(blank=True, null=True)),
                ('first_reminder_sent', models.DateField(blank=True, null=True)),
                ('second_reminder_sent', models.DateField(blank=True, null=True)),
                ('third_reminder_sent', models.DateField(blank=True, null=True)),
                ('final_intimation_sent', models.DateField(blank=True, null=True)),
                ('sales_manager_informed_1_date', models.DateField(blank=True, null=True)),
                ('sales_manager_informed_1_notes', models.TextField(blank=True)),
                ('sales_manager_informed_2_date', models.DateField(blank=True, null=True)),
                ('sales_manager_informed_2_notes', models.TextField(blank=True)),
                ('client_responded', models.BooleanField(default=False)),
                ('client_response_date', models.DateField(blank=True, null=True)),
                ('client_response_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending - Not Started'), ('in_progress', 'In Progress - Reminders Sent'), ('client_responded', 'Client Responded'), ('renewed', 'Renewed'), ('not_renewed', 'Not Renewed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Internal notes about renewal process')),
                ('renewal_completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_trackers_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal_trackers_updated', to=settings.AUTH_USER_MODEL)),
                ('new_rate_card', models.ForeignKey(blank=True, help_text='Link to new rate card if renewed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_renewal_tracker', to='operations.ratecard')),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_trackers', to='operations.ratecard')),
            ],
            options={
                'verbose_name': 'Agreement Renewal Tracker',
                'verbose_name_plural': 'Agreement Renewal Trackers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgreementRenewalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('tracker_created', 'Tracker Created'), ('initial_email', 'Initial Email Sent'), ('reminder_1', '1st Reminder Sent'), ('reminder_2', '2nd Reminder Sent'), ('reminder_3', '3rd Reminder Sent'), ('final_intimation', 'Final Intimation Sent'), ('sales_informed_1', 'Sales Manager Informed (1st)'), ('sales_informed_2', 'Sales Manager Informed (2nd)'), ('client_response', 'Client Responded'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added'), ('renewed', 'Agreement Renewed'), ('cancelled', 'Tracker Cancelled')], max_length=30)),
                ('action_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('email_sent_to', models.CharField(blank=True, help_text='Email addresses', max_length=500)),
                ('email_subject', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='operations.agreementrenewaltracker')),
            ],
            options={
                'verbose_name': 'Renewal Log Entry',
                'verbose_name_plural': 'Renewal Log Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscalationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_year', models.IntegerField(help_text='Year when escalation is due')),
                ('escalation_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Escalation % (if fixed)', max_digits=5, null=True)),
                ('initial_intimation_sent', models.DateField(blank=True, null=True)),
                ('first_reminder_sent', models.DateField(blank=True, null=True)),
                ('second_reminder_sent', models.DateField(blank=True, null=True)),
                ('final_notice_sent', models.DateField(blank=True, null=True)),
                ('sales_manager_informed_date', models.DateField(blank=True, null=True)),
                ('sales_manager_notes', models.TextField(blank=True)),
                ('finance_team_informed_date', models.DateField(blank=True, null=True)),
                ('finance_team_notes', models.TextField(blank=True)),
                ('client_acknowledged', models.BooleanField(default=False)),
                ('client_acknowledgment_date', models.DateField(blank=True, null=True)),
                ('client_response_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending - Not Started'), ('in_progress', 'In Progress - Reminders Sent'), ('client_acknowledged', 'Client Acknowledged'), ('escalation_applied', 'Escalation Applied'), ('disputed', 'Client Disputed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('escalation_applied_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalation_trackers_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalation_trackers_updated', to=settings.AUTH_USER_MODEL)),
                ('new_rate_card', models.ForeignKey(blank=True, help_text='Link to new rate card with escalated rates', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_escalation_tracker', to='operations.ratecard')),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_trackers', to='operations.ratecard')),
            ],
            options={
                'verbose_name': 'Escalation Tracker',
                'verbose_name_plural': 'Escalation Trackers',
                'ordering': ['-escalation_year', '-created_at'],
                'unique_together': {('rate_card', 'escalation_year')},
            },
        ),
        migrations.CreateModel(
            name='EscalationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('tracker_created', 'Tracker Created'), ('initial_intimation', 'Initial Intimation Sent'), ('reminder_1', '1st Reminder Sent'), ('reminder_2', '2nd Reminder Sent'), ('final_notice', 'Final Notice Sent'), ('sales_informed', 'Sales Manager Informed'), ('finance_informed', 'Finance Team Informed'), ('client_acknowledged', 'Client Acknowledged'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added'), ('escalation_applied', 'Escalation Applied'), ('disputed', 'Client Disputed'), ('cancelled', 'Tracker Cancelled')], max_length=30)),
                ('action_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('email_sent_to', models.CharField(blank=True, max_length=500)),
                ('email_subject', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='operations.escalationtracker')),
            ],
            options={
                'verbose_name': 'Escalation Log Entry',
                'verbose_name_plural': 'Escalation Log Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
