# Generated by Django 5.2.7 on 2025-11-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_add_agreement_escalation_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputelog',
            name='opened_at',
            field=models.DateTimeField(blank=True, help_text="When dispute status first became 'open'", null=True),
        ),
    ]
