from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_add_notice_period_duration_and_end_date'),
        ('operations', '0015_remove_billing_query_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField(help_text='First day of billing month (e.g., 2025-10-01)')),
                ('rate_card_missing', models.BooleanField(default=False, help_text='True if no rate card was available')),
                ('storage_min_space', models.DecimalField(decimal_places=2, default=0, help_text='Minimum billable space', max_digits=12)),
                ('storage_additional_space', models.DecimalField(decimal_places=2, default=0, help_text='Additional space used', max_digits=12)),
                ('storage_unit_type', models.CharField(choices=[('sqft', 'Sq Ft'), ('pallet', 'Pallet'), ('lumpsum', 'Lumpsum')], default='sqft', max_length=20)),
                ('storage_days', models.IntegerField(default=30)),
                ('storage_remarks', models.TextField(blank=True)),
                ('vendor_storage_rate', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('client_storage_rate', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('vendor_storage_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('client_storage_billing', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('handling_in_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Inbound handling quantity', max_digits=12)),
                ('handling_in_unit_type', models.CharField(blank=True, help_text='Unit type (boxes, tons, units, etc) - auto from rate card', max_length=50)),
                ('handling_in_remarks', models.TextField(blank=True)),
                ('vendor_handling_in_rate', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('client_handling_in_rate', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('vendor_handling_in_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('client_handling_in_billing', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('handling_out_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Outbound handling quantity', max_digits=12)),
                ('handling_out_unit_type', models.CharField(blank=True, help_text='Unit type - auto from rate card', max_length=50)),
                ('handling_out_remarks', models.TextField(blank=True)),
                ('vendor_handling_out_rate', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('client_handling_out_rate', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('vendor_handling_out_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('client_handling_out_billing', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('vendor_transport_vehicle_type', models.CharField(blank=True, choices=[('local_transport', 'Local Transport'), ('bike', 'Bike'), ('pick_up', 'Pick Up'), ('14_ft', '14 FT'), ('20_ft', '20 FT'), ('32_ft', '32 FT'), ('tata_ace', 'TATA Ace'), ('max_2mp', 'MAX 2MP'), ('tata_407', 'TATA 407'), ('tata_709', 'TATA 709'), ('tata_909', 'TATA 909'), ('ftl_1109', 'FTL/1109'), ('17_ft', '17 FT'), ('3_wheeler', '3 Wheeler'), ('porter', 'Porter')], max_length=30)),
                ('vendor_transport_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vendor_transport_remarks', models.TextField(blank=True)),
                ('client_transport_vehicle_type', models.CharField(blank=True, choices=[('local_transport', 'Local Transport'), ('bike', 'Bike'), ('pick_up', 'Pick Up'), ('14_ft', '14 FT'), ('20_ft', '20 FT'), ('32_ft', '32 FT'), ('tata_ace', 'TATA Ace'), ('max_2mp', 'MAX 2MP'), ('tata_407', 'TATA 407'), ('tata_709', 'TATA 709'), ('tata_909', 'TATA 909'), ('ftl_1109', 'FTL/1109'), ('17_ft', '17 FT'), ('3_wheeler', '3 Wheeler'), ('porter', 'Porter')], max_length=30)),
                ('client_transport_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('client_transport_remarks', models.TextField(blank=True)),
                ('vendor_misc_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vendor_misc_description', models.TextField(blank=True, help_text='Description of VAS/misc charges')),
                ('client_misc_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('client_misc_description', models.TextField(blank=True)),
                ('vendor_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('client_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('margin_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6)),
                ('mis_email_subject', models.CharField(blank=True, max_length=500)),
                ('mis_link', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('controller_review', 'Controller Review'), ('controller_rejected', 'Controller Rejected'), ('finance_review', 'Finance Review'), ('finance_rejected', 'Finance Rejected'), ('approved', 'Approved')], default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('controller_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('controller_remarks', models.TextField(blank=True)),
                ('controller_action', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('finance_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('finance_remarks', models.TextField(blank=True)),
                ('finance_action', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('rejection_deadline', models.DateTimeField(blank=True, help_text='24 hours from rejection time', null=True)),
                ('edit_locked_at', models.DateTimeField(blank=True, help_text='Locked after 7 days or after final approval', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('controller_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_billings_controller_reviewed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_billings_created', to=settings.AUTH_USER_MODEL)),
                ('finance_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_billings_finance_reviewed', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_billings', to='projects.projectcode')),
                ('rate_card_used', models.ForeignKey(blank=True, help_text='Rate card used for calculations', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.ratecard')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_billings_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Billing',
                'verbose_name_plural': 'Monthly Billings',
                'db_table': 'monthly_billings',
                'ordering': ['-billing_month', 'project__project_code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='monthlybilling',
            unique_together={('project', 'billing_month')},
        ),
    ]