# Generated by Django 5.2.7 on 2025-11-22 16:38
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('operations', '0016_monthlybilling'),
    ]

    operations = [
        # These models were already deleted in 0015, so skip them
        # Just add the new fields to RateCard
        migrations.AddField(
            model_name='ratecard',
            name='billing_start_date',
            field=models.DateField(blank=True, help_text='Date when billing starts for this project', null=True),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='operation_start_date',
            field=models.DateField(blank=True, help_text='Date when warehouse operations started', null=True),
        ),
    ]