# Generated by Django 5.2.7 on 2025-11-22 18:13
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_remove_billingqueryactivity_query_and_more'),
    ]

    operations = [
        # Step 1: Rename the RateCard model to ProjectCard
        migrations.RenameModel(
            old_name='RateCard',
            new_name='ProjectCard',
        ),
        
        # Step 2: Rename rate_card field to project_card in AgreementRenewalTracker
        migrations.RenameField(
            model_name='agreementrenewaltracker',
            old_name='rate_card',
            new_name='project_card',
        ),
        migrations.RenameField(
            model_name='agreementrenewaltracker',
            old_name='new_rate_card',
            new_name='new_project_card',
        ),
        
        # Step 3: Rename rate_card field to project_card in EscalationTracker
        migrations.RenameField(
            model_name='escalationtracker',
            old_name='rate_card',
            new_name='project_card',
        ),
        migrations.RenameField(
            model_name='escalationtracker',
            old_name='new_rate_card',
            new_name='new_project_card',
        ),
        
        # Step 4: Rename rate_card_used field to project_card_used in MonthlyBilling
        migrations.RenameField(
            model_name='monthlybilling',
            old_name='rate_card_used',
            new_name='project_card_used',
        ),
        migrations.RenameField(
            model_name='monthlybilling',
            old_name='rate_card_missing',
            new_name='project_card_missing',
        ),
        
        # Step 5: Rename rate_card field to project_card in related models
        migrations.RenameField(
            model_name='handlingrate',
            old_name='rate_card',
            new_name='project_card',
        ),
        migrations.RenameField(
            model_name='infrastructurecost',
            old_name='rate_card',
            new_name='project_card',
        ),
        migrations.RenameField(
            model_name='storagerate',
            old_name='rate_card',
            new_name='project_card',
        ),
        migrations.RenameField(
            model_name='valueaddedservice',
            old_name='rate_card',
            new_name='project_card',
        ),
        
        # Step 6: Add new payment terms fields to ProjectCard
        migrations.AddField(
            model_name='projectcard',
            name='storage_payment_days',
            field=models.IntegerField(
                blank=True,
                help_text='Payment terms for storage (days after invoice)',
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(365)
                ]
            ),
        ),
        migrations.AddField(
            model_name='projectcard',
            name='handling_payment_days',
            field=models.IntegerField(
                blank=True,
                help_text='Payment terms for handling (days after invoice)',
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(365)
                ]
            ),
        ),
    ]