# Generated by Django 5.2.7 on 2025-11-24 14:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_rename_ratecard_to_projectcard'),
        ('projects', '0009_remove_projectcode_operation_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handlingrate',
            options={'ordering': ['direction', 'channel', 'base_type'], 'verbose_name': 'Handling Rate', 'verbose_name_plural': 'Handling Rates'},
        ),
        migrations.AlterModelOptions(
            name='infrastructurecost',
            options={'ordering': ['cost_type', 'rate_for'], 'verbose_name': 'Infrastructure Cost', 'verbose_name_plural': 'Infrastructure Costs'},
        ),
        migrations.AlterModelOptions(
            name='projectcard',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project Card', 'verbose_name_plural': 'Project Cards'},
        ),
        migrations.AlterModelOptions(
            name='storagerate',
            options={'ordering': ['rate_for'], 'verbose_name': 'Storage Rate', 'verbose_name_plural': 'Storage Rates'},
        ),
        migrations.AlterModelOptions(
            name='storagerateslab',
            options={'ordering': ['rate_for', 'min_quantity'], 'verbose_name': 'Storage Rate Slab', 'verbose_name_plural': 'Storage Rate Slabs'},
        ),
        migrations.AlterModelOptions(
            name='valueaddedservice',
            options={'ordering': ['service_type', 'rate_for'], 'verbose_name': 'Value Added Service', 'verbose_name_plural': 'Value Added Services'},
        ),
        migrations.AlterUniqueTogether(
            name='storagerate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='handlingrate',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='handlingrate',
            name='condition_value',
        ),
        migrations.RemoveField(
            model_name='projectcard',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='storagerateslab',
            name='from_area',
        ),
        migrations.RemoveField(
            model_name='storagerateslab',
            name='storage_rate',
        ),
        migrations.RemoveField(
            model_name='storagerateslab',
            name='to_area',
        ),
        migrations.AddField(
            model_name='storagerateslab',
            name='max_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Maximum quantity for this slab (inclusive). Leave blank for 'and above'", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='storagerateslab',
            name='min_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum quantity for this slab (inclusive)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='storagerateslab',
            name='project_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_slabs', to='operations.projectcard'),
        ),
        migrations.AddField(
            model_name='storagerateslab',
            name='rate_for',
            field=models.CharField(blank=True, help_text='What this slab rate applies to', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='storagerateslab',
            name='space_type',
            field=models.CharField(blank=True, help_text="Type of space (e.g., 'Palletized', 'Racked', 'Floor')", max_length=100),
        ),
        migrations.AddField(
            model_name='storagerateslab',
            name='unit',
            field=models.CharField(default='sqft', help_text='Unit of measurement (sqft, pallet, cbm, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='base_type',
            field=models.CharField(choices=[('per_unit', 'Per Unit'), ('per_kg', 'Per KG'), ('per_box', 'Per Box'), ('per_order', 'Per Order'), ('per_line_item', 'Per Line Item')], default='per_unit', max_length=50),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='channel',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('d2c', 'D2C'), ('marketplace', 'Marketplace'), ('all', 'All Channels')], default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('both', 'Both')], default='both', max_length=20),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='max_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight for this rate', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='min_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum weight for this rate', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='rate_for',
            field=models.CharField(help_text='What this rate applies to', max_length=200),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks about this rate'),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Cost amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='cost_type',
            field=models.CharField(choices=[('manpower', 'Manpower'), ('equipment', 'Equipment'), ('utilities', 'Utilities'), ('rent', 'Rent'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the cost'),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='is_at_actual',
            field=models.BooleanField(default=False, help_text='Whether this cost is billed at actuals'),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='rate_for',
            field=models.CharField(help_text='What this cost is for', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='agreement_end_date',
            field=models.DateField(blank=True, help_text='Date when agreement ends', null=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='agreement_start_date',
            field=models.DateField(blank=True, help_text='Date when agreement starts', null=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='annual_escalation_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual escalation percentage (e.g., 5.00 for 5%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='billing_start_date',
            field=models.DateField(blank=True, help_text='Date when billing starts (can differ from agreement start)', null=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='handling_payment_days',
            field=models.IntegerField(blank=True, help_text='Payment terms for handling invoices (days after invoice)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='has_fixed_escalation',
            field=models.BooleanField(default=False, help_text='Whether escalation percentage is fixed annually'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_project_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or remarks about this project card'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='project',
            field=models.ForeignKey(help_text='Project this card belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='project_cards', to='projects.projectcode'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Security deposit amount', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='storage_payment_days',
            field=models.IntegerField(blank=True, help_text='Payment terms for storage invoices (days after invoice)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='yearly_escalation_date',
            field=models.DateField(blank=True, help_text='Annual escalation date', null=True),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='flat_rate_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per unit (sqft, pallet, etc.)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='minimum_billable_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum billable area/quantity', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='monthly_billable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed monthly billable amount', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='project_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_rates', to='operations.projectcard'),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='rate_for',
            field=models.CharField(help_text="What this rate applies to (e.g., 'Palletized Storage', 'Floor Storage')", max_length=200),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='saas_monthly_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly SaaS/platform charge', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='space_type',
            field=models.CharField(blank=True, help_text="Type of space (e.g., 'Palletized', 'Racked', 'Floor')", max_length=100),
        ),
        migrations.AlterField(
            model_name='storagerateslab',
            name='rate_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per unit in this slab', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate for this service', max_digits=10),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='rate_for',
            field=models.CharField(help_text='What this VAS rate applies to', max_length=200),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='service_description',
            field=models.TextField(blank=True, help_text='Detailed description of the service'),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='service_type',
            field=models.CharField(choices=[('labeling', 'Labeling'), ('kitting', 'Kitting'), ('repacking', 'Repacking'), ('quality_check', 'Quality Check'), ('photography', 'Photography'), ('gift_wrapping', 'Gift Wrapping'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='unit',
            field=models.CharField(default='per_unit', help_text="Unit of measurement (e.g., 'per unit', 'per hour', 'per batch')", max_length=50),
        ),
        migrations.RemoveField(
            model_name='storagerate',
            name='is_slab_based',
        ),
        migrations.CreateModel(
            name='ProjectCardAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('missing_card', 'Missing Project Card'), ('incomplete_card', 'Incomplete Project Card'), ('missing_payment_terms', 'Missing Payment Terms'), ('missing_dates', 'Missing Operational Dates'), ('no_storage_rates', 'No Storage Rates'), ('no_handling_rates', 'No Handling Rates')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectcard_alerts', to='projects.projectcode')),
                ('project_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='operations.projectcard')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_resolved', 'severity'], name='operations__is_reso_fc15d0_idx')],
            },
        ),
    ]
