# Generated by Django 5.2.7 on 2025-11-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_alter_handlingrate_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectCardAlert',
        ),
    ]
