# Generated by Django 5.2.7 on 2025-11-24 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_remove_projectcardalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal_trackers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalation_trackers_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
