# Generated by Django 5.2.7 on 2025-11-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_allow_null_created_by_trackers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingstatement',
            options={'managed': False, 'ordering': ['-billing_month']},
        ),
        migrations.AlterModelOptions(
            name='operationsdailyupdate',
            options={'managed': False, 'ordering': ['-operation_date']},
        ),
    ]
