# Generated by Django 5.2.7 on 2025-12-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_alter_billingstatement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhocbillingattachment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='adhocbillingentry',
            options={'ordering': ['-event_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='adhocbillingentry',
            name='estimated_amount',
        ),
        migrations.RemoveField(
            model_name='adhocbillingentry',
            name='quantity',
        ),
        migrations.AddField(
            model_name='adhocbillingattachment',
            name='attachment_type',
            field=models.CharField(choices=[('client_approval', 'Client Approval/Mail'), ('vendor_bill', 'Vendor Bill/Proof'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='adhocbillingentry',
            name='client_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total Amount (Qty * Rate)', max_digits=15),
        ),
        migrations.AddField(
            model_name='adhocbillingentry',
            name='client_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Qty billable to client', max_digits=10),
        ),
        migrations.AddField(
            model_name='adhocbillingentry',
            name='client_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate per unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='adhocbillingentry',
            name='vendor_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total Cost (Qty * Rate)', max_digits=15),
        ),
        migrations.AddField(
            model_name='adhocbillingentry',
            name='vendor_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Qty payable to vendor', max_digits=10),
        ),
        migrations.AddField(
            model_name='adhocbillingentry',
            name='vendor_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='adhocbillingentry',
            name='billing_month',
            field=models.DateField(help_text='Auto-calculated from event_date (YYYY-MM-01)'),
        ),
        migrations.AlterField(
            model_name='adhocbillingentry',
            name='billing_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adhocbillingentry',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit (e.g., sq.ft., hours, boxes)', max_length=50),
        ),
    ]
