# Generated by Django 5.2.7 on 2025-12-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_alter_adhocbillingattachment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhocbillingentry',
            options={'ordering': ['-event_date', '-created_at'], 'verbose_name': 'Adhoc Billing Entry', 'verbose_name_plural': 'Adhoc Billing Entries'},
        ),
        migrations.AddField(
            model_name='dailyspaceutilization',
            name='unit',
            field=models.CharField(choices=[('Sq. Ft.', 'Sq. Ft.'), ('Pallet', 'Pallet'), ('Unit', 'Unit'), ('Order', 'Order'), ('Lumpsum', 'Lumpsum')], default='Sq. Ft.', max_length=20),
        ),
    ]
