# Generated by Django 5.2.7 on 2025-12-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_alter_adhocbillingentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocbillingentry',
            name='charge_type',
            field=models.CharField(choices=[('extra_storage', 'Extra Storage Space'), ('extra_manpower', 'Extra Manpower'), ('extra_handling', 'Extra Handling Charges'), ('overtime', 'Overtime'), ('vas', 'Value Added Services'), ('transport', 'Transport Charges'), ('equipment', 'Equipment Rental'), ('other', 'Other')], max_length=20),
        ),
    ]
