# Generated by Django 5.2.7 on 2025-12-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_alter_adhocbillingentry_charge_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handlingrate',
            options={'ordering': ['rate_for', 'direction', 'channel'], 'verbose_name': 'Handling Rate', 'verbose_name_plural': 'Handling Rates'},
        ),
        migrations.AlterModelOptions(
            name='infrastructurecost',
            options={'ordering': ['rate_for', 'cost_type'], 'verbose_name': 'Infrastructure Cost', 'verbose_name_plural': 'Infrastructure Costs'},
        ),
        migrations.AlterModelOptions(
            name='valueaddedservice',
            options={'ordering': ['rate_for', 'service_type'], 'verbose_name': 'Value Added Service', 'verbose_name_plural': 'Value Added Services'},
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='base_type',
            field=models.CharField(choices=[('per_unit', 'Per Unit'), ('per_kg', 'Per KG'), ('per_tonne', 'Per Tonne'), ('per_box', 'Per Box'), ('per_pallet', 'Per Pallet'), ('per_order', 'Per Order'), ('per_line_item', 'Per Line Item'), ('per_roll', 'Per Roll'), ('weight_slab', 'Weight Slab')], default='per_unit', max_length=20),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='channel',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('d2c', 'D2C'), ('rto', 'RTO'), ('rtv', 'RTV'), ('both', 'Both'), ('na', 'N/A')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='rate_for',
            field=models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor')], help_text='Client or Vendor rate', max_length=20),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='cost_type',
            field=models.CharField(choices=[('equipment', 'Equipment'), ('utilities', 'Utilities'), ('rent', 'Rent'), ('insurance', 'Insurance'), ('security', 'Security Guard'), ('management_fee', 'Management Fee'), ('manpower_fixed', 'Manpower (Fixed)'), ('electricity', 'Electricity'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='rate_for',
            field=models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor')], help_text='Client or Vendor rate', max_length=20),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='rate_for',
            field=models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor')], help_text='Client or Vendor rate', max_length=20),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='space_type',
            field=models.CharField(blank=True, choices=[('sqft', 'Square Feet'), ('pallet', 'Pallet'), ('lumpsum', 'Lumpsum')], help_text='Type of space measurement', max_length=20),
        ),
        migrations.AlterField(
            model_name='storagerateslab',
            name='rate_for',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('vendor', 'Vendor')], help_text='Client or Vendor rate', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='storagerateslab',
            name='space_type',
            field=models.CharField(blank=True, choices=[('sqft', 'Square Feet'), ('pallet', 'Pallet'), ('cbm', 'Cubic Meter')], help_text='Type of space measurement', max_length=20),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate for this service', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='rate_for',
            field=models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor')], help_text='Client or Vendor rate', max_length=20),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='service_type',
            field=models.CharField(choices=[('labeling', 'Labeling'), ('kitting', 'Kitting'), ('repacking', 'Repacking'), ('quality_check', 'Quality Check'), ('photography', 'Photography'), ('gift_wrapping', 'Gift Wrapping'), ('manpower', 'Manpower'), ('forklift', 'Forklift'), ('hydra', 'Hydra'), ('barcoding', 'Barcoding'), ('qc_inspection', 'QC Inspection'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='unit',
            field=models.CharField(choices=[('per_hour', 'Per Hour'), ('per_day', 'Per Day'), ('per_month', 'Per Month'), ('per_unit', 'Per Unit'), ('lumpsum', 'Lumpsum'), ('at_actual', 'At Actual')], default='per_unit', help_text='Unit of measurement', max_length=20),
        ),
    ]
