# Generated by Django 5.2.7 on 2025-12-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0026_alter_handlingrate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingrate',
            name='base_type',
            field=models.CharField(choices=[('per_unit', 'Per Unit'), ('per_kg', 'Per KG'), ('per_tonne', 'Per Tonne'), ('per_box', 'Per Box'), ('per_pallet', 'Per Pallet'), ('per_order', 'Per Order'), ('per_line_item', 'Per Line Item'), ('per_roll', 'Per Roll')], default='per_unit', max_length=20),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='channel',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('d2c', 'D2C'), ('rto', 'RTO'), ('rtv', 'RTV')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='cost_type',
            field=models.CharField(choices=[('equipment', 'Equipment'), ('utilities', 'Utilities'), ('rent', 'Rent'), ('insurance', 'Insurance'), ('security', 'Security Guard'), ('management_fee', 'Management Fee'), ('electricity', 'Electricity'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
