# Generated by Django 5.2.7 on 2025-12-09 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_alter_handlingrate_base_type_and_more'),
        ('projects', '0014_alter_clientcontact_client_contact_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcard',
            name='client_card',
            field=models.ForeignKey(blank=True, db_column='client_card_code', help_text='Link to Client Card master data', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_cards', to='projects.clientcard'),
        ),
        migrations.AddField(
            model_name='projectcard',
            name='vendor_warehouse',
            field=models.ForeignKey(blank=True, db_column='vendor_warehouse_code', help_text='Link to Warehouse master data', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_cards', to='projects.vendorwarehouse'),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='both', max_length=20),
        ),
    ]
