# Generated by Django 5.2.7 on 2025-12-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0029_adhoc_billing_line_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhocbillingattachment',
            options={'ordering': ['uploaded_at']},
        ),
    ]
