# Generated by Django 5.2.7 on 2025-12-16 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0030_alter_adhocbillingattachment_options'),
        ('projects', '0018_alter_vendorwarehouse_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcard',
            name='vendor_warehouse',
            field=models.ForeignKey(blank=True, db_column='vendor_warehouse_code', help_text='Link to Warehouse master data', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_cards', to='projects.vendorwarehouse', to_field='warehouse_code'),
        ),
    ]
