# Generated by Django 5.2.7 on 2025-12-24 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0031_alter_projectcard_vendor_warehouse'),
        ('projects', '0023_projectdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCardAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('missing_storage_rates', 'Missing Storage Rates'), ('missing_handling_rates', 'Missing Handling Rates'), ('missing_vas', 'Missing Value Added Services'), ('incomplete_project_card', 'Incomplete Project Card'), ('outdated_rates', 'Outdated Rates'), ('missing_infrastructure', 'Missing Infrastructure Costs')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('message', models.TextField(help_text='Detailed description of the alert')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_card_alerts', to='projects.projectcode')),
                ('project_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='operations.projectcard')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'is_resolved'], name='operations__project_2f03e6_idx'), models.Index(fields=['alert_type', 'severity'], name='operations__alert_t_7117af_idx')],
            },
        ),
    ]
