# Generated by Django 5.2.7 on 2026-01-05 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown_master_data', '0005_fill_missing_from_old_004'),
        ('operations', '0032_projectcardalert'),
        ('projects', '0025_update_vendor_warehouse_fields'),
        ('supply', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementrenewallog',
            options={'ordering': ['-action_date', '-created_at'], 'verbose_name': 'Agreement Renewal Log', 'verbose_name_plural': 'Agreement Renewal Logs'},
        ),
        migrations.AlterModelOptions(
            name='escalationlog',
            options={'ordering': ['-action_date', '-created_at'], 'verbose_name': 'Escalation Log', 'verbose_name_plural': 'Escalation Logs'},
        ),
        migrations.AlterModelOptions(
            name='monthlybilling',
            options={'managed': False, 'ordering': ['-billing_month', '-created_at'], 'verbose_name': 'Monthly Billing', 'verbose_name_plural': 'Monthly Billings'},
        ),
        migrations.AlterModelOptions(
            name='projectcard',
            options={'ordering': ['-version', '-created_at'], 'verbose_name': 'Project Card', 'verbose_name_plural': 'Project Cards'},
        ),
        migrations.AddField(
            model_name='projectcard',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Only one version can be active at a time"),
        ),
        migrations.AlterField(
            model_name='adhocbillingentry',
            name='status',
            field=models.ForeignKey(db_column='status', default='pending', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.adhocbillingstatus'),
        ),
        migrations.AlterField(
            model_name='adhocbillinglineitem',
            name='charge_type',
            field=models.ForeignKey(db_column='charge_type', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.adhocchargetype'),
        ),
        migrations.AlterField(
            model_name='adhocbillinglineitem',
            name='side',
            field=models.ForeignKey(db_column='side', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.transactionside'),
        ),
        migrations.AlterField(
            model_name='agreementrenewallog',
            name='action_date',
            field=models.DateField(help_text='Date when action was performed'),
        ),
        migrations.AlterField(
            model_name='agreementrenewallog',
            name='action_type',
            field=models.ForeignKey(db_column='action_type', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.renewalactiontype'),
        ),
        migrations.AlterField(
            model_name='agreementrenewallog',
            name='email_sent_to',
            field=models.CharField(blank=True, help_text='Email recipients (comma-separated)', max_length=500),
        ),
        migrations.AlterField(
            model_name='agreementrenewallog',
            name='email_subject',
            field=models.CharField(blank=True, help_text='Email subject line', max_length=500),
        ),
        migrations.AlterField(
            model_name='agreementrenewallog',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the action'),
        ),
        migrations.AlterField(
            model_name='agreementrenewallog',
            name='performed_by',
            field=models.ForeignKey(help_text='User who performed this action', on_delete=django.db.models.deletion.PROTECT, related_name='renewal_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='client_responded',
            field=models.BooleanField(default=False, help_text='Whether client has responded to renewal'),
        ),
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='client_response_date',
            field=models.DateField(blank=True, help_text='Date when client responded', null=True),
        ),
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='client_response_summary',
            field=models.TextField(blank=True, help_text="Summary of client's response"),
        ),
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='final_intimation_sent',
            field=models.DateField(blank=True, help_text='Date when final intimation was sent', null=True),
        ),
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='first_reminder_sent',
            field=models.DateField(blank=True, help_text='Date when 1st reminder was sent', null=True),
        ),
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='initial_email_sent',
            field=models.DateField(blank=True, help_text='Date when initial renewal email was sent', null=True),
        ),
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='project_card',
            field=models.ForeignKey(help_text='Project card being renewed', on_delete=django.db.models.deletion.CASCADE, related_name='renewal_trackers', to='operations.projectcard'),
        ),
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='remarks',
            field=models.TextField(blank=True, help_text='Internal remarks'),
        ),
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='renewal_completed_date',
            field=models.DateField(blank=True, help_text='Date when renewal was completed', null=True),
        ),
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='sales_manager_informed_1_date',
            field=models.DateField(blank=True, help_text='Date when sales manager was informed (1st time)', null=True),
        ),
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='sales_manager_informed_1_notes',
            field=models.TextField(blank=True, help_text='Notes from first sales manager interaction'),
        ),
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='sales_manager_informed_2_date',
            field=models.DateField(blank=True, help_text='Date when sales manager was informed (2nd time)', null=True),
        ),
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='sales_manager_informed_2_notes',
            field=models.TextField(blank=True, help_text='Notes from second sales manager interaction'),
        ),
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='second_reminder_sent',
            field=models.DateField(blank=True, help_text='Date when 2nd reminder was sent', null=True),
        ),
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='status',
            field=models.ForeignKey(db_column='status', default='pending', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.renewalstatus'),
        ),
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='third_reminder_sent',
            field=models.DateField(blank=True, help_text='Date when 3rd reminder was sent', null=True),
        ),
        migrations.AlterField(
            model_name='dailyspaceutilization',
            name='unit',
            field=models.ForeignKey(db_column='unit', default='sqft', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.storageunit'),
        ),
        migrations.AlterField(
            model_name='disputeactivity',
            name='activity_type',
            field=models.ForeignKey(db_column='activity_type', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.activitytype'),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='category',
            field=models.ForeignKey(db_column='category', default='operations', help_text='Type of dispute', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.disputecategory'),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='priority',
            field=models.ForeignKey(db_column='priority', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.priority'),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='severity',
            field=models.ForeignKey(blank=True, db_column='severity', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.severity'),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='status',
            field=models.ForeignKey(db_column='status', default='open', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.disputestatus'),
        ),
        migrations.AlterField(
            model_name='escalationlog',
            name='action_date',
            field=models.DateField(help_text='Date when action was performed'),
        ),
        migrations.AlterField(
            model_name='escalationlog',
            name='action_type',
            field=models.ForeignKey(db_column='action_type', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.escalationactiontype'),
        ),
        migrations.AlterField(
            model_name='escalationlog',
            name='email_sent_to',
            field=models.CharField(blank=True, help_text='Email recipients (comma-separated)', max_length=500),
        ),
        migrations.AlterField(
            model_name='escalationlog',
            name='email_subject',
            field=models.CharField(blank=True, help_text='Email subject line', max_length=500),
        ),
        migrations.AlterField(
            model_name='escalationlog',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the action'),
        ),
        migrations.AlterField(
            model_name='escalationlog',
            name='performed_by',
            field=models.ForeignKey(help_text='User who performed this action', on_delete=django.db.models.deletion.PROTECT, related_name='escalation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='client_acknowledged',
            field=models.BooleanField(default=False, help_text='Whether client has acknowledged the escalation'),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='client_acknowledgment_date',
            field=models.DateField(blank=True, help_text='Date when client acknowledged', null=True),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='client_response_notes',
            field=models.TextField(blank=True, help_text="Client's response or feedback"),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='escalation_applied_date',
            field=models.DateField(blank=True, help_text='Date when escalation was actually applied', null=True),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='escalation_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Escalation % (if fixed). NULL if mutually agreed.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='escalation_year',
            field=models.IntegerField(help_text='Which escalation (1 = 1st escalation after 1 year, 2 = 2nd after 2 years, etc.)'),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='final_notice_sent',
            field=models.DateField(blank=True, help_text='Date when final notice was sent', null=True),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='finance_team_informed_date',
            field=models.DateField(blank=True, help_text='Date when finance team was informed', null=True),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='finance_team_notes',
            field=models.TextField(blank=True, help_text='Notes from finance team interaction'),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='first_reminder_sent',
            field=models.DateField(blank=True, help_text='Date when 1st reminder was sent', null=True),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='initial_intimation_sent',
            field=models.DateField(blank=True, help_text='Date when initial intimation email was sent', null=True),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='project_card',
            field=models.ForeignKey(help_text='Project card being escalated', on_delete=django.db.models.deletion.CASCADE, related_name='escalation_trackers', to='operations.projectcard'),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='remarks',
            field=models.TextField(blank=True, help_text='Internal remarks'),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='sales_manager_informed_date',
            field=models.DateField(blank=True, help_text='Date when sales manager was informed', null=True),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='sales_manager_notes',
            field=models.TextField(blank=True, help_text='Notes from sales manager interaction'),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='second_reminder_sent',
            field=models.DateField(blank=True, help_text='Date when 2nd reminder was sent', null=True),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='status',
            field=models.ForeignKey(db_column='status', default='pending', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.escalationstatus'),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='base_type',
            field=models.ForeignKey(db_column='base_type', default='per_unit', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.handlingbasetype'),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='channel',
            field=models.ForeignKey(blank=True, db_column='channel', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.saleschannel'),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='max_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='min_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='cost_type',
            field=models.ForeignKey(db_column='cost_type', default='other', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.operationalcosttype'),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='is_at_actual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='rate_for',
            field=models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='vendor_warehouse',
            field=models.ForeignKey(blank=True, db_column='vendor_warehouse_code', help_text='Link to Warehouse master data', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_cards', to='supply.vendorwarehouse', to_field='warehouse_code'),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='space_type',
            field=models.ForeignKey(blank=True, db_column='space_type', help_text='Type of space measurement', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.storageunit'),
        ),
        migrations.AlterField(
            model_name='storagerateslab',
            name='max_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum quantity for this slab (inclusive)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storagerateslab',
            name='space_type',
            field=models.ForeignKey(blank=True, db_column='space_type', help_text='Type of space measurement', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.storageunit'),
        ),
        migrations.AlterField(
            model_name='storagerateslab',
            name='unit',
            field=models.CharField(default='sqft', help_text='Unit of measurement', max_length=50),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='rate_for',
            field=models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='service_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='service_type',
            field=models.ForeignKey(db_column='service_type', default='other', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.vasservicetype'),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='unit',
            field=models.ForeignKey(db_column='unit', default='per_unit', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.vasunit'),
        ),
        migrations.AddIndex(
            model_name='projectcard',
            index=models.Index(fields=['project', 'is_active'], name='operations__project_fd72a6_idx'),
        ),
        migrations.AlterModelTable(
            name='agreementrenewallog',
            table='operations_agreementrenewallog',
        ),
        migrations.AlterModelTable(
            name='agreementrenewaltracker',
            table='operations_agreementrenewaltracker',
        ),
        migrations.AlterModelTable(
            name='escalationlog',
            table='operations_escalationlog',
        ),
        migrations.AlterModelTable(
            name='escalationtracker',
            table='operations_escalationtracker',
        ),
        migrations.AlterModelTable(
            name='handlingrate',
            table='operations_handlingrate',
        ),
        migrations.AlterModelTable(
            name='infrastructurecost',
            table='operations_infrastructurecost',
        ),
        migrations.AlterModelTable(
            name='projectcard',
            table='operations_projectcard',
        ),
        migrations.AlterModelTable(
            name='storagerate',
            table='operations_storagerate',
        ),
        migrations.AlterModelTable(
            name='storagerateslab',
            table='operations_storagerateslab',
        ),
        migrations.AlterModelTable(
            name='valueaddedservice',
            table='operations_valueaddedservice',
        ),
    ]
