# Generated by Django 5.2.7 on 2026-01-06 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown_master_data', '0001_initial'),
        ('operations', '0033_alter_agreementrenewallog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreementrenewaltracker',
            name='new_project_card',
        ),
        migrations.RemoveField(
            model_name='escalationtracker',
            name='new_project_card',
        ),
        migrations.AddField(
            model_name='escalationtracker',
            name='applied_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual % applied (for mutually agreed cases)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='projectcard',
            name='escalation_terms',
            field=models.ForeignKey(blank=True, db_column='escalation_terms', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.escalationterms'),
        ),
        migrations.AddField(
            model_name='projectcard',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='The next version of this rate card (if superseded)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='operations.projectcard'),
        ),
        migrations.AddField(
            model_name='projectcard',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Date from which this rate card version is active', null=True),
        ),
        migrations.AddField(
            model_name='projectcard',
            name='valid_to',
            field=models.DateField(blank=True, help_text='Date until which this rate card version is active (NULL = currently active)', null=True),
        ),
        migrations.AddField(
            model_name='projectcard',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number of this rate card'),
        ),
        migrations.AddIndex(
            model_name='projectcard',
            index=models.Index(fields=['project', 'valid_from', 'valid_to'], name='operations__project_53a732_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcard',
            index=models.Index(fields=['project', 'version'], name='operations__project_b257d3_idx'),
        ),
    ]
