# Generated by Django 5.2.7 on 2026-01-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0034_remove_agreementrenewaltracker_new_project_card_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlybilling',
            options={'managed': True, 'ordering': ['-billing_month', '-created_at'], 'verbose_name': 'Monthly Billing', 'verbose_name_plural': 'Monthly Billings'},
        ),
    ]
