# Generated by Django 5.2.7 on 2026-01-12 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_monthly_billing_columns(apps, schema_editor):
    """Add columns to monthly_billings table if the table exists (managed=False)."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM information_schema.tables "
            "WHERE table_name = 'monthly_billings'"
        )
        if cursor.fetchone() is None:
            return

        alters = [
            "ALTER TABLE monthly_billings ADD COLUMN IF NOT EXISTS handling_in_channel VARCHAR(50) REFERENCES master_sales_channels(code)",
            "ALTER TABLE monthly_billings ADD COLUMN IF NOT EXISTS handling_in_base_type VARCHAR(50) REFERENCES master_handling_base_types(code)",
            "ALTER TABLE monthly_billings ADD COLUMN IF NOT EXISTS handling_out_channel VARCHAR(50) REFERENCES master_sales_channels(code)",
            "ALTER TABLE monthly_billings ADD COLUMN IF NOT EXISTS handling_out_base_type VARCHAR(50) REFERENCES master_handling_base_types(code)",
            "ALTER TABLE monthly_billings ADD COLUMN IF NOT EXISTS vas_service_type VARCHAR(50) REFERENCES master_vas_service_types(code)",
            "ALTER TABLE monthly_billings ADD COLUMN IF NOT EXISTS vas_quantity DECIMAL(12,2) DEFAULT 0",
            "ALTER TABLE monthly_billings ADD COLUMN IF NOT EXISTS vas_unit VARCHAR(50) REFERENCES master_vas_units(code)",
            "ALTER TABLE monthly_billings ADD COLUMN IF NOT EXISTS vendor_vas_rate DECIMAL(10,2)",
            "ALTER TABLE monthly_billings ADD COLUMN IF NOT EXISTS vendor_vas_cost DECIMAL(15,2) DEFAULT 0",
            "ALTER TABLE monthly_billings ADD COLUMN IF NOT EXISTS client_vas_rate DECIMAL(10,2)",
            "ALTER TABLE monthly_billings ADD COLUMN IF NOT EXISTS client_vas_billing DECIMAL(15,2) DEFAULT 0",
            "ALTER TABLE monthly_billings ADD COLUMN IF NOT EXISTS vas_remarks TEXT DEFAULT ''",
        ]
        for sql in alters:
            cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown_master_data', '0002_delete_citycode'),
        ('operations', '0036_noop_placeholder'),
        ('projects', '0026_projectcodechangelog_alter_location_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlybilling',
            options={'managed': False, 'ordering': ['-billing_month', '-created_at'], 'verbose_name': 'Monthly Billing', 'verbose_name_plural': 'Monthly Billings'},
        ),
        migrations.RemoveIndex(
            model_name='adhocbillingentry',
            name='operations__billing_5c4958_idx',
        ),
        migrations.RenameField(
            model_name='adhocbillingentry',
            old_name='billing_month',
            new_name='service_month',
        ),
        migrations.AddIndex(
            model_name='adhocbillingentry',
            index=models.Index(fields=['service_month', 'status'], name='operations__service_2ced60_idx'),
        ),
        migrations.AddField(
        model_name='monthlybilling',
        name='handling_in_channel',
        field=models.ForeignKey(blank=True, db_column='handling_in_channel', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billings_handling_in_channel', to='dropdown_master_data.saleschannel', to_field='code'),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='handling_in_base_type',
            field=models.ForeignKey(blank=True, db_column='handling_in_base_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billings_handling_in_base', to='dropdown_master_data.handlingbasetype', to_field='code'),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='handling_out_channel',
            field=models.ForeignKey(blank=True, db_column='handling_out_channel', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billings_handling_out_channel', to='dropdown_master_data.saleschannel', to_field='code'),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='handling_out_base_type',
            field=models.ForeignKey(blank=True, db_column='handling_out_base_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billings_handling_out_base', to='dropdown_master_data.handlingbasetype', to_field='code'),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='vas_service_type',
            field=models.ForeignKey(blank=True, db_column='vas_service_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billings_vas', to='dropdown_master_data.vasservicetype', to_field='code'),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='vas_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='vas_unit',
            field=models.ForeignKey(blank=True, db_column='vas_unit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billings_vas_unit', to='dropdown_master_data.vasunit', to_field='code'),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='vendor_vas_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='vendor_vas_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='client_vas_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='client_vas_billing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='vas_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(
            add_monthly_billing_columns,
            reverse_code=migrations.RunPython.noop,
        ),
    ]