# Generated by Django 5.2.7 on 2026-01-15 09:56
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('operations', '0037_alter_monthlybilling_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructurecost',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='storagerate',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='storagerateslab',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='valueaddedservice',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adhocbillingentry',
            name='service_month',
            field=models.DateField(blank=True, help_text='Auto-calculated from event_date (YYYY-MM-01 - for matching with monthly billing)', null=True),
        ),
        migrations.CreateModel(
            name='TransportRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_for', models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor')], max_length=20)),
                ('vehicle_type', models.CharField(blank=True, default='', max_length=50)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_rates', to='operations.projectcard')),
            ],
            options={
                'verbose_name': 'Transport Rate',
                'verbose_name_plural': 'Transport Rates',
                'db_table': 'operations_transportrate',
                'ordering': ['rate_for', 'vehicle_type'],
            },
        ),
    ]