# Generated by Django 5.2.7 on 2026-01-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0038_infrastructurecost_remarks_storagerate_remarks_and_more'),
    ]

    operations = [
    ]
