# Generated by Django 5.2.7 on 2026-01-19 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown_master_data', '0002_delete_citycode'),
        ('operations', '0039_auto_20260115_1444'),
        ('projects', '0027_alter_clientcard_client_created_at_and_more'),
        ('supply', '0002_citycode_created_at_citycode_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handlingrate',
            options={'ordering': ['rate_for', 'direction'], 'verbose_name': 'Handling Rate', 'verbose_name_plural': 'Handling Rates'},
        ),
        migrations.AlterModelOptions(
            name='projectcard',
            options={'ordering': ['-version'], 'verbose_name': 'Project Card', 'verbose_name_plural': 'Project Cards'},
        ),
        migrations.RemoveIndex(
            model_name='projectcard',
            name='operations__project_53a732_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectcard',
            name='operations__project_b257d3_idx',
        ),
        # migrations.RemoveField(
        #     model_name='storagerateslab',
        #     name='unit',
        # ),
        migrations.AddField(
            model_name='storagerate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='storagerate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this rate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_storage_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storagerateslab',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='storagerateslab',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this slab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_storage_slabs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagerateslab',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adhocbillingattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='adhocbillingentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='adhocbillinglineitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='agreementrenewallog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='agreementrenewaltracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyentryauditlog',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailymislog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyspaceutilization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='disputeactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='disputecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='escalationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='escalationtracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='base_type',
            field=models.ForeignKey(blank=True, db_column='base_type', help_text='Base type for rate calculation', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.handlingbasetype'),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='channel',
            field=models.ForeignKey(blank=True, db_column='channel', help_text='Sales channel (B2B, B2C, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.saleschannel'),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='direction',
            field=models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], help_text='Inbound or Outbound', max_length=10),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='max_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight in kg for this rate', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='min_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum weight in kg for this rate', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='project_card',
            field=models.ForeignKey(help_text='Project card this rate belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='handling_rates', to='operations.projectcard'),
        ),
        migrations.AlterField(
            model_name='handlingrate',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Cost amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='cost_type',
            field=models.ForeignKey(db_column='cost_type', help_text='Type of infrastructure cost', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.operationalcosttype'),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of the cost'),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='is_at_actual',
            field=models.BooleanField(default=False, help_text='Whether this cost is billed at actual'),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='project_card',
            field=models.ForeignKey(help_text='Project card this cost belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_costs', to='operations.projectcard'),
        ),
        migrations.AlterField(
            model_name='infrastructurecost',
            name='rate_for',
            field=models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor')], help_text='Client or Vendor cost', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='agreement_end_date',
            field=models.DateField(blank=True, help_text='Agreement end date', null=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='agreement_start_date',
            field=models.DateField(blank=True, help_text='Agreement start date', null=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='annual_escalation_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual escalation percentage (e.g., 5.00 for 5%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='billing_start_date',
            field=models.DateField(blank=True, help_text='Date when billing should start', null=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='client_card',
            field=models.ForeignKey(blank=True, db_column='client_card_code', help_text='Link to client master data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_cards', to='projects.clientcard'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='escalation_terms',
            field=models.CharField(choices=[('no_escalation', 'No Escalation'), ('mutually_agreed', 'Mutually Agreed'), ('fixed_percentage', 'Fixed Percentage')], default='no_escalation', help_text='Type of escalation applicable', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='handling_payment_days',
            field=models.PositiveIntegerField(blank=True, help_text='Payment terms for handling (in days)', null=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='has_fixed_escalation',
            field=models.BooleanField(default=False, help_text='Whether this card has a fixed escalation percentage'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one version can be active at a time'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_project_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes or comments'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='operation_start_date',
            field=models.DateField(blank=True, help_text='Date when operations started', null=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='project',
            field=models.ForeignKey(help_text='The project this card belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='project_cards', to='projects.projectcode'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='storage_payment_days',
            field=models.PositiveIntegerField(blank=True, help_text='Payment terms for storage (in days)', null=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='The newer version that replaced this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='operations.projectcard'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='valid_from',
            field=models.DateField(default='2024-01-01', help_text='Date from which this card becomes effective'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='valid_to',
            field=models.DateField(blank=True, help_text='Date until which this card is valid (NULL = ongoing)', null=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='vendor_warehouse',
            field=models.ForeignKey(blank=True, db_column='vendor_warehouse_code', help_text='Link to vendor warehouse master data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_cards', to='supply.vendorwarehouse', to_field='warehouse_code'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number (1, 2, 3, ...)'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='yearly_escalation_date',
            field=models.DateField(blank=True, help_text='Date when yearly escalation should be applied', null=True),
        ),
        migrations.AlterField(
            model_name='projectcardalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='flat_rate_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per unit (sqft, pallet, etc.). Used when NOT using slabs.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='minimum_billable_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum billable area/quantity. Client pays for at least this much.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='monthly_billable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed monthly lumpsum amount. Alternative to flat_rate_per_unit.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='project_card',
            field=models.ForeignKey(blank=True, help_text='Project card this rate belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_rates', to='operations.projectcard'),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='rate_for',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('vendor', 'Vendor')], help_text='Whether this rate applies to client or vendor', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='remarks',
            field=models.TextField(blank=True, default='', help_text='Optional notes about this rate'),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='saas_monthly_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly SaaS/platform charge (added on top of storage cost)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storagerate',
            name='space_type',
            field=models.ForeignKey(blank=True, db_column='space_type', help_text='Type of space measurement (sqft, pallet, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.storageunit'),
        ),
        migrations.AlterField(
            model_name='storagerateslab',
            name='max_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Maximum quantity for this slab (inclusive). Leave NULL for 'above' (last slab).", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storagerateslab',
            name='min_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum quantity for this slab (inclusive). Use 0 for first slab.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storagerateslab',
            name='project_card',
            field=models.ForeignKey(blank=True, help_text='Project card this slab belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_slabs', to='operations.projectcard'),
        ),
        migrations.AlterField(
            model_name='storagerateslab',
            name='rate_for',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('vendor', 'Vendor')], help_text='Whether this slab applies to client or vendor', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='storagerateslab',
            name='remarks',
            field=models.TextField(blank=True, default='', help_text='Optional notes about this slab'),
        ),
        migrations.AlterField(
            model_name='storagerateslab',
            name='space_type',
            field=models.ForeignKey(blank=True, db_column='space_type', help_text='Type of space measurement (sqft, pallet, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.storageunit'),
        ),
        migrations.AlterField(
            model_name='transportrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportrate',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of transport service'),
        ),
        migrations.AlterField(
            model_name='transportrate',
            name='project_card',
            field=models.ForeignKey(help_text='Project card this rate belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transport_rates', to='operations.projectcard'),
        ),
        migrations.AlterField(
            model_name='transportrate',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Transport rate', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transportrate',
            name='rate_for',
            field=models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor')], help_text='Client or Vendor rate', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportrate',
            name='vehicle_type',
            field=models.CharField(blank=True, default='', help_text='Type of vehicle (e.g., Truck, Van, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='project_card',
            field=models.ForeignKey(help_text='Project card this service belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='value_added_services', to='operations.projectcard'),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='rate',
            field=models.DecimalField(decimal_places=2, default='0', help_text='Rate for this service', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='rate_for',
            field=models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor')], help_text='Client or Vendor rate', max_length=20),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='service_description',
            field=models.TextField(blank=True, default='', help_text='Description of the service'),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='service_type',
            field=models.ForeignKey(db_column='service_type', help_text='Type of value-added service', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.vasservicetype'),
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='unit',
            field=models.CharField(default='per unit', help_text='Unit of measurement', max_length=50),
        ),
        migrations.AlterField(
            model_name='warehouseholiday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='projectcard',
            unique_together={('project', 'version')},
        ),
        migrations.AddIndex(
            model_name='projectcard',
            index=models.Index(fields=['valid_from', 'valid_to'], name='operations__valid_f_302b3e_idx'),
        ),
    ]
