# Generated by Django 5.2.7 on 2026-01-19 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0040_alter_handlingrate_options_alter_projectcard_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagerateslab',
            name='unit',
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='project_card',
            field=models.ForeignKey(help_text='Project card this service belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='vas_services', to='operations.projectcard'),
        ),
    ]
