# Generated by Django 5.2.7 on 2026-01-11 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown_master_data', '0002_delete_citycode'),
        ('operations', '0041_remove_storagerateslab_unit_and_more'),
        ('projects', '0027_alter_clientcard_client_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybilling',
            name='handling_in_client_variance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Difference from project card: actual - expected', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='handling_in_override_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='handling_in_vendor_variance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Difference from project card: actual - expected', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='handling_out_client_variance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Difference from project card: actual - expected', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='handling_out_override_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='handling_out_vendor_variance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Difference from project card: actual - expected', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='included_adhoc_ids',
            field=models.TextField(blank=True, default='', help_text='Comma-separated IDs of included adhoc billings'),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='storage_client_variance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Difference from project card: actual - expected', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='storage_override_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='storage_vendor_variance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Difference from project card: actual - expected', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='billing_month',
            field=models.DateField(help_text='First day of billing month'),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='client_handling_in_billing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='client_handling_in_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='client_handling_out_billing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='client_handling_out_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='client_misc_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='client_storage_billing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='client_storage_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='client_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='client_transport_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='client_transport_vehicle_type',
            field=models.ForeignKey(blank=True, db_column='client_transport_vehicle_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billings_client_transport', to='dropdown_master_data.vehicletype', to_field='code'),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='controller_action',
            field=models.ForeignKey(db_column='controller_action', default='pending', on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billings_controller_actions', to='dropdown_master_data.approvalaction', to_field='code'),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='controller_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_billings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='edit_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='finance_action',
            field=models.ForeignKey(db_column='finance_action', default='pending', on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billings_finance_actions', to='dropdown_master_data.approvalaction', to_field='code'),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='finance_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='handling_in_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='handling_in_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='handling_in_unit_type',
            field=models.ForeignKey(blank=True, db_column='handling_in_unit_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billings_handling_in', to='dropdown_master_data.handlingunit', to_field='code'),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='handling_out_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='handling_out_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='handling_out_unit_type',
            field=models.ForeignKey(blank=True, db_column='handling_out_unit_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billings_handling_out', to='dropdown_master_data.handlingunit', to_field='code'),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='margin_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='margin_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='mis_email_subject',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='mis_link',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billings', to='projects.projectcode'),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='project_card_missing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='project_card_used',
            field=models.ForeignKey(blank=True, db_column='project_card_used_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.projectcard'),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='rejection_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='status',
            field=models.ForeignKey(db_column='status', default='draft', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.monthlybillingstatus', to_field='code'),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='storage_additional_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='storage_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='storage_min_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='storage_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='storage_unit_type',
            field=models.ForeignKey(db_column='storage_unit_type', on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.storageunit', to_field='code'),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='vendor_handling_in_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='vendor_handling_in_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='vendor_handling_out_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='vendor_handling_out_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='vendor_misc_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='vendor_storage_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='vendor_storage_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='vendor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='vendor_transport_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='monthlybilling',
            name='vendor_transport_vehicle_type',
            field=models.ForeignKey(blank=True, db_column='vendor_transport_vehicle_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billings_vendor_transport', to='dropdown_master_data.vehicletype', to_field='code'),
        ),
    ]