# Generated by Django 5.2.7 on 2026-01-26 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown_master_data', '0010_populate_handling_unit'),
        ('operations', '0045_make_optional_fields_nullable'),
    ]

    operations = [
    # Fix InfrastructureCost.cost_type to be nullable
    migrations.AlterField(
        model_name='infrastructurecost',
        name='cost_type',
        field=models.ForeignKey(
            blank=True,
            db_column='cost_type',
            help_text='Type of infrastructure cost (optional)',
            null=True,
            on_delete=django.db.models.deletion.PROTECT,
            to='dropdown_master_data.operationalcosttype',
            to_field='code'
        ),
    ),
    
    # Add infrastructure fields to MonthlyBilling
    migrations.AddField(
        model_name='monthlybilling',
        name='client_infrastructure_amount',
        field=models.DecimalField(
            decimal_places=2,
            default=0,
            help_text='Total infrastructure costs billed to client',
            max_digits=15
        ),
    ),
    migrations.AddField(
        model_name='monthlybilling',
        name='vendor_infrastructure_cost',
        field=models.DecimalField(
            decimal_places=2,
            default=0,
            help_text='Total infrastructure costs from vendor',
            max_digits=15
        ),
    ),
    migrations.AddField(
        model_name='monthlybilling',
        name='infrastructure_remarks',
        field=models.TextField(
            blank=True,
            default='',
            help_text='Infrastructure cost details and breakdown'
        ),
    ),
]
