# Generated by Django 5.2.7 on 2026-01-26 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown_master_data', '0010_populate_handling_unit'),
        ('operations', '0046_add_infrastructure_and_fix_nullable_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructurecost',
            name='cost_type',
            field=models.ForeignKey(blank=True, db_column='cost_type', help_text='Type of infrastructure cost (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.operationalcosttype'),
        ),
    ]
