# Generated by Django 5.2.7 on 2026-01-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0048_add_document_uploads_to_monthly_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputelog',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='dispute_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='disputelog',
            name='resolution',
            field=models.TextField(blank=True, default=''),
        ),
    ]
