# Generated by Django 5.2.7 on 2026-02-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0050_add_transport_quantity_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocbillinglineitem',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
