# Generated by Django 5.2.7 on 2026-02-09 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown_master_data', '0014_populate_adobe_sign_dropdowns'),
        ('operations', '0051_update_rate_decimal_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBillingHandlingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=3)),
                ('client_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('client_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('client_billing', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('vendor_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('vendor_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('vendor_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True, default='')),
                ('row_order', models.IntegerField(default=0)),
                ('client_base_type', models.ForeignKey(blank=True, db_column='client_base_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billing_handling_items_client', to='dropdown_master_data.handlingbasetype')),
                ('client_channel', models.ForeignKey(blank=True, db_column='client_channel', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billing_handling_items_client', to='dropdown_master_data.saleschannel')),
                ('client_unit_type', models.ForeignKey(blank=True, db_column='client_unit_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billing_handling_items_client', to='dropdown_master_data.handlingunit')),
                ('monthly_billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handling_items', to='operations.monthlybilling')),
                ('vendor_base_type', models.ForeignKey(blank=True, db_column='vendor_base_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billing_handling_items_vendor', to='dropdown_master_data.handlingbasetype')),
                ('vendor_channel', models.ForeignKey(blank=True, db_column='vendor_channel', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billing_handling_items_vendor', to='dropdown_master_data.saleschannel')),
                ('vendor_unit_type', models.ForeignKey(blank=True, db_column='vendor_unit_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billing_handling_items_vendor', to='dropdown_master_data.handlingunit')),
            ],
            options={
                'verbose_name': 'Monthly Billing Handling Item',
                'verbose_name_plural': 'Monthly Billing Handling Items',
                'db_table': 'monthly_billing_handling_items',
                'ordering': ['direction', 'row_order'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBillingStorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_min_space', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('client_additional_space', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('client_storage_days', models.IntegerField(default=0)),
                ('client_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('client_billing', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('vendor_min_space', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('vendor_additional_space', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('vendor_storage_days', models.IntegerField(default=0)),
                ('vendor_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('vendor_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True, default='')),
                ('row_order', models.IntegerField(default=0)),
                ('client_storage_unit_type', models.ForeignKey(blank=True, db_column='client_storage_unit_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billing_storage_items_client', to='dropdown_master_data.storageunit')),
                ('monthly_billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_items', to='operations.monthlybilling')),
                ('vendor_storage_unit_type', models.ForeignKey(blank=True, db_column='vendor_storage_unit_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billing_storage_items_vendor', to='dropdown_master_data.storageunit')),
            ],
            options={
                'verbose_name': 'Monthly Billing Storage Item',
                'verbose_name_plural': 'Monthly Billing Storage Items',
                'db_table': 'monthly_billing_storage_items',
                'ordering': ['row_order'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBillingTransportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('vendor', 'Vendor'), ('client', 'Client')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True, default='')),
                ('row_order', models.IntegerField(default=0)),
                ('monthly_billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_items', to='operations.monthlybilling')),
                ('vehicle_type', models.ForeignKey(blank=True, db_column='vehicle_type', null=True, on_delete=django.db.models.deletion.PROTECT, to='dropdown_master_data.vehicletype')),
            ],
            options={
                'verbose_name': 'Monthly Billing Transport Item',
                'verbose_name_plural': 'Monthly Billing Transport Items',
                'db_table': 'monthly_billing_transport_items',
                'ordering': ['side', 'row_order'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBillingVASItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('client_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('client_billing', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('vendor_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('vendor_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('vendor_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True, default='')),
                ('row_order', models.IntegerField(default=0)),
                ('client_service_type', models.ForeignKey(blank=True, db_column='client_service_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billing_vas_items_client', to='dropdown_master_data.vasservicetype')),
                ('client_unit', models.ForeignKey(blank=True, db_column='client_unit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billing_vas_items_client', to='dropdown_master_data.vasunit')),
                ('monthly_billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vas_items', to='operations.monthlybilling')),
                ('vendor_service_type', models.ForeignKey(blank=True, db_column='vendor_service_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billing_vas_items_vendor', to='dropdown_master_data.vasservicetype')),
                ('vendor_unit', models.ForeignKey(blank=True, db_column='vendor_unit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billing_vas_items_vendor', to='dropdown_master_data.vasunit')),
            ],
            options={
                'verbose_name': 'Monthly Billing VAS Item',
                'verbose_name_plural': 'Monthly Billing VAS Items',
                'db_table': 'monthly_billing_vas_items',
                'ordering': ['row_order'],
            },
        ),
    ]
