# Generated by Django 5.2.7 on 2026-02-09 13:38

from django.db import migrations


def make_fields_nullable(apps, schema_editor):
    """
    Make old single-value billing fields nullable.

    After migrating to line items (0053), these fields are no longer used
    but Django still tries to save NULL values to them, causing NOT NULL violations.

    Root cause context:
    MonthlyBilling has managed=False. This means Django's AddField migrations
    are no-ops — they update migration state but never touch the actual table.
    Some columns (e.g. transport_quantity fields from migration 0050) exist in
    production (added manually) but not on fresh databases. We must query
    information_schema to determine which columns actually exist, then only
    ALTER those. This is idempotent and works on both fresh and existing databases.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Check if the unmanaged table exists
        cursor.execute("""
            SELECT 1 FROM information_schema.tables
            WHERE table_name = 'monthly_billings'
        """)
        if cursor.fetchone() is None:
            return

        # Get all existing columns on the table
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = 'monthly_billings'
        """)
        existing_columns = {row[0] for row in cursor.fetchall()}

        # Columns we want to make nullable
        target_columns = [
            'storage_min_space', 'storage_additional_space', 'storage_unit_type', 'storage_days',
            'vendor_storage_rate', 'vendor_storage_cost', 'client_storage_rate', 'client_storage_billing',
            'handling_in_quantity', 'handling_in_unit_type', 'handling_in_channel', 'handling_in_base_type',
            'vendor_handling_in_rate', 'vendor_handling_in_cost', 'client_handling_in_rate', 'client_handling_in_billing',
            'handling_out_quantity', 'handling_out_unit_type', 'handling_out_channel', 'handling_out_base_type',
            'vendor_handling_out_rate', 'vendor_handling_out_cost', 'client_handling_out_rate', 'client_handling_out_billing',
            'client_transport_vehicle_type', 'client_transport_quantity', 'client_transport_amount',
            'vendor_transport_vehicle_type', 'vendor_transport_quantity', 'vendor_transport_amount',
            'vas_service_type', 'vendor_vas_service_type', 'vas_quantity', 'vas_unit',
            'client_vas_rate', 'client_vas_billing', 'vendor_vas_rate', 'vendor_vas_cost',
            'client_infrastructure_amount', 'vendor_infrastructure_cost',
        ]

        # Only alter columns that actually exist in the database
        columns_to_alter = [col for col in target_columns if col in existing_columns]

        if not columns_to_alter:
            return

        alter_clauses = ', '.join(
            f'ALTER COLUMN {col} DROP NOT NULL' for col in columns_to_alter
        )
        cursor.execute(f'ALTER TABLE monthly_billings {alter_clauses};')


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0053_migrate_monthly_billing_to_line_items'),
    ]

    operations = [
        migrations.RunPython(make_fields_nullable, migrations.RunPython.noop),
    ]
