# Generated by Django 5.2.7 on 2026-02-09 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown_master_data', '0014_populate_adobe_sign_dropdowns'),
        ('operations', '0054_make_old_billing_fields_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBillingInfrastructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of this infrastructure cost')),
                ('client_billing', models.DecimalField(decimal_places=2, default=0, help_text='Amount charged to client for this infrastructure item', max_digits=15)),
                ('vendor_cost', models.DecimalField(decimal_places=2, default=0, help_text='Amount vendor charges us for this infrastructure item', max_digits=15)),
                ('row_order', models.IntegerField(default=0)),
                ('cost_type', models.ForeignKey(blank=True, db_column='cost_type', help_text='Type of infrastructure cost (Equipment, Facility, Utilities, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_billing_infrastructure_items', to='dropdown_master_data.operationalcosttype')),
                ('monthly_billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_items', to='operations.monthlybilling')),
            ],
            options={
                'verbose_name': 'Monthly Billing Infrastructure Item',
                'verbose_name_plural': 'Monthly Billing Infrastructure Items',
                'db_table': 'monthly_billing_infrastructure_items',
                'ordering': ['row_order'],
            },
        ),
    ]
