# Generated by Django 5.2.7 on 2026-02-09 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0055_add_infrastructure_line_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybillingstorageitem',
            name='client_lumpsum_amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Fixed monthly amount for client (lumpsum pricing)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='monthlybillingstorageitem',
            name='pricing_type',
            field=models.CharField(choices=[('flat', 'Flat Rate'), ('slab', 'Tiered/Slab Based'), ('lumpsum', 'Lumpsum')], default='flat', help_text='Pricing model: flat rate, slab-based, or lumpsum', max_length=10),
        ),
        migrations.AddField(
            model_name='monthlybillingstorageitem',
            name='vendor_lumpsum_amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Fixed monthly cost for vendor (lumpsum pricing)', max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='MonthlyBillingStorageSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor')], help_text='Whether this slab applies to client or vendor', max_length=10)),
                ('min_quantity', models.DecimalField(decimal_places=4, help_text='Minimum quantity for this slab (inclusive). Use 0 for first slab.', max_digits=12)),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=4, help_text="Maximum quantity for this slab (inclusive). Leave NULL for 'above' (last slab).", max_digits=12, null=True)),
                ('rate_per_unit', models.DecimalField(decimal_places=4, help_text='Rate per unit in this slab', max_digits=10)),
                ('remarks', models.TextField(blank=True, default='', help_text='Optional notes about this slab')),
                ('row_order', models.IntegerField(default=0, help_text='Order of slabs (for display)')),
                ('storage_item', models.ForeignKey(help_text='Storage item this slab belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='operations.monthlybillingstorageitem')),
            ],
            options={
                'verbose_name': 'Monthly Billing Storage Slab',
                'verbose_name_plural': 'Monthly Billing Storage Slabs',
                'db_table': 'monthly_billing_storage_slabs',
                'ordering': ['storage_item', 'side', 'row_order'],
                'indexes': [models.Index(fields=['storage_item', 'side'], name='monthly_bil_storage_73cc13_idx')],
            },
        ),
    ]
