# Generated by Django 5.2.7 on 2026-02-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0056_add_storage_slab_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybillingvasitem',
            name='client_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of hours (used when unit is Per Hour)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='monthlybillingvasitem',
            name='vendor_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of hours (used when unit is Per Hour)', max_digits=10, null=True),
        ),
    ]
