# Generated by Django 5.2.7 on 2026-02-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0057_add_vas_hours_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybillinginfrastructureitem',
            name='client_billing',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Amount charged to client for this infrastructure item', max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlybillinginfrastructureitem',
            name='vendor_cost',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Amount vendor charges us for this infrastructure item', max_digits=15),
        ),
    ]
