# Generated by Django 5.2.9 on 2026-02-18 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown_master_data', '0016_seed_regions_states'),
        ('operations', '0060_fix_monthly_billing_nullable_columns'),
        ('projects', '0035_quotationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailymislog',
            index=models.Index(fields=['project', '-log_date'], name='operations__project_8ab9f2_idx'),
        ),
        migrations.AddIndex(
            model_name='disputelog',
            index=models.Index(fields=['project', 'status'], name='operations__project_b7973b_idx'),
        ),
        migrations.AddIndex(
            model_name='disputelog',
            index=models.Index(fields=['status', '-raised_at'], name='operations__status_c9a640_idx'),
        ),
        migrations.AddIndex(
            model_name='disputelog',
            index=models.Index(fields=['assigned_to', 'status'], name='operations__assigne_a8eaf6_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseholiday',
            index=models.Index(fields=['holiday_date'], name='operations__holiday_a28d16_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseholiday',
            index=models.Index(fields=['project', 'holiday_date'], name='operations__project_8fad8c_idx'),
        ),
    ]
