# Generated by Django 5.2.9 on 2026-02-23 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0061_add_performance_indexes'),
        ('projects', '0036_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LorryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lr_number', models.CharField(editable=False, help_text='Auto-generated GW-NNNN', max_length=10, unique=True)),
                ('lr_date', models.DateField(help_text='Date shown on the LR')),
                ('from_location', models.CharField(max_length=200)),
                ('to_location', models.CharField(max_length=200)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=50)),
                ('vehicle_type', models.CharField(blank=True, default='', max_length=100)),
                ('delivery_office_address', models.TextField(blank=True, default='', help_text='Address of Delivery Office')),
                ('consignor_name', models.CharField(blank=True, default='', max_length=200)),
                ('consignor_address', models.TextField(blank=True, default='')),
                ('consignee_name', models.CharField(blank=True, default='', max_length=200)),
                ('consignee_address', models.TextField(blank=True, default='')),
                ('consignor_gst_no', models.CharField(blank=True, default='', max_length=50)),
                ('consignee_gst_no', models.CharField(blank=True, default='', max_length=50)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=100)),
                ('gst_paid_by', models.CharField(choices=[('consignee', 'Consignee'), ('consignor', 'Consignor'), ('transporter', 'Transporter')], default='consignee', max_length=15)),
                ('mode_of_packing', models.CharField(blank=True, default='', max_length=200)),
                ('value', models.CharField(blank=True, default='', help_text='Declared value of goods', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('insurance_company', models.CharField(blank=True, default='', max_length=200)),
                ('insurance_policy_no', models.CharField(blank=True, default='', max_length=100)),
                ('insurance_date', models.CharField(blank=True, default='', max_length=50)),
                ('insurance_amount', models.CharField(blank=True, default='', max_length=50)),
                ('insurance_risk', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lr_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lr_modified', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='project_id', help_text='For record-keeping only; NOT printed on LR', on_delete=django.db.models.deletion.PROTECT, related_name='lorry_receipts', to='projects.projectcode')),
            ],
            options={
                'verbose_name': 'Lorry Receipt',
                'verbose_name_plural': 'Lorry Receipts',
                'ordering': ['-lr_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LRAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted')], max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField()),
                ('change_reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='operations.lorryreceipt')),
            ],
            options={
                'verbose_name': 'LR Audit Log',
                'verbose_name_plural': 'LR Audit Logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='LRLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packages', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('actual_weight', models.CharField(blank=True, default='', max_length=50)),
                ('charged_weight', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='operations.lorryreceipt')),
            ],
            options={
                'verbose_name': 'LR Line Item',
                'verbose_name_plural': 'LR Line Items',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='lorryreceipt',
            index=models.Index(fields=['project', '-lr_date'], name='operations__project_f589d5_idx'),
        ),
        migrations.AddIndex(
            model_name='lorryreceipt',
            index=models.Index(fields=['-lr_date'], name='operations__lr_date_764724_idx'),
        ),
        migrations.AddIndex(
            model_name='lorryreceipt',
            index=models.Index(fields=['lr_number'], name='operations__lr_numb_2975c6_idx'),
        ),
    ]
