# Generated by Django 5.2.9 on 2026-02-26 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0062_lorryreceipt_lrauditlog_lrlineitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PorterInvoiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('batch', 'Batch Processing'), ('single', 'Single Edit')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=4, help_text='Escalation multiplier (e.g. 1.20 = +20%)', max_digits=6, null=True)),
                ('excel_mapping_file', models.FileField(blank=True, help_text='Optional Excel file with CRN-to-target-total mapping', null=True, upload_to='porter_invoices/excel_mappings/%Y/%m/')),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('result_zip', models.FileField(blank=True, null=True, upload_to='porter_invoices/results/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='porter_invoice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Porter Invoice Session',
                'verbose_name_plural': 'Porter Invoice Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PorterInvoiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('crn', models.CharField(blank=True, default='', help_text='Extracted CRN/Order number', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('skipped', 'Skipped'), ('error', 'Error')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('old_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('edit_fields', models.JSONField(blank=True, help_text='Fields edited in single-edit mode', null=True)),
                ('original_pdf', models.FileField(upload_to='porter_invoices/originals/%Y/%m/')),
                ('edited_pdf', models.FileField(blank=True, null=True, upload_to='porter_invoices/edited/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='operations.porterinvoicesession')),
            ],
            options={
                'verbose_name': 'Porter Invoice File',
                'verbose_name_plural': 'Porter Invoice Files',
                'ordering': ['original_filename'],
            },
        ),
        migrations.AddIndex(
            model_name='porterinvoicesession',
            index=models.Index(fields=['-created_at'], name='operations__created_1e2c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='porterinvoicesession',
            index=models.Index(fields=['created_by', '-created_at'], name='operations__created_550a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='porterinvoicesession',
            index=models.Index(fields=['session_type', 'status'], name='operations__session_3f83f3_idx'),
        ),
        migrations.AddIndex(
            model_name='porterinvoicefile',
            index=models.Index(fields=['session', 'status'], name='operations__session_4f2a33_idx'),
        ),
        migrations.AddIndex(
            model_name='porterinvoicefile',
            index=models.Index(fields=['crn'], name='operations__crn_1d37f2_idx'),
        ),
    ]
