# Generated by Django 5.2.7 on 2026-02-03 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gmail_contacts',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('in_progress', 'In Progress')], default='success', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('emails_synced', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sync statuses',
                'db_table': 'gmail_sync_status',
            },
        ),
        migrations.CreateModel(
            name='GmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_account', models.EmailField(max_length=254)),
                ('token_data', models.JSONField(blank=True, null=True)),
                ('encrypted_token_data', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gmail_tokens',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'email_account')},
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.EmailField(db_index=True, max_length=254)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('thread_id', models.CharField(db_index=True, max_length=255)),
                ('subject', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('snippet', models.TextField(blank=True)),
                ('labels', models.JSONField(default=list)),
                ('date', models.DateTimeField(db_index=True)),
                ('is_read', models.BooleanField(default=False)),
                ('has_attachments', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.ManyToManyField(blank=True, related_name='received_emails', to='gmail.contact')),
                ('sender_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='gmail.contact')),
                ('account_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='gmail.gmailtoken')),
            ],
            options={
                'db_table': 'gmail_emails',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['account_email', 'date'], name='gmail_email_account_ba1b4d_idx'), models.Index(fields=['thread_id', 'date'], name='gmail_email_thread__492749_idx')],
            },
        ),
    ]
