# Generated by Django 5.2.9 on 2026-02-16 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='account_link',
        ),
        migrations.RemoveField(
            model_name='email',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='email',
            name='sender_contact',
        ),
        migrations.RemoveField(
            model_name='gmailtoken',
            name='token_data',
        ),
        migrations.RemoveField(
            model_name='syncstatus',
            name='account_email',
        ),
        migrations.RemoveField(
            model_name='syncstatus',
            name='history_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_email_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gmailtoken',
            name='history_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='syncstatus',
            name='gmail_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_statuses', to='gmail.gmailtoken'),
        ),
        migrations.AddField(
            model_name='syncstatus',
            name='threads_synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='GmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, default='', help_text='Google OAuth Client ID', max_length=500)),
                ('encrypted_client_secret', models.TextField(blank=True, default='', help_text='Google OAuth Client Secret — stored encrypted')),
                ('redirect_uri', models.URLField(blank=True, default='', help_text='OAuth redirect URI (e.g., https://yourdomain.com/gmail/oauth/callback/)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gmail_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gmail Settings',
                'verbose_name_plural': 'Gmail Settings',
                'db_table': 'gmail_settings',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('system', 'System'), ('user', 'User')], max_length=20)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='gmail.gmailtoken')),
            ],
            options={
                'db_table': 'gmail_labels',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('subject', models.TextField()),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('snippet', models.TextField(blank=True)),
                ('date', models.DateTimeField(db_index=True)),
                ('labels', models.JSONField(default=list)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachments_meta', models.JSONField(default=list)),
                ('history_id', models.CharField(blank=True, max_length=50)),
                ('internal_date', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gmail.gmailtoken')),
                ('bcc_contacts', models.ManyToManyField(blank=True, related_name='bcc_messages', to='gmail.contact')),
                ('cc_contacts', models.ManyToManyField(blank=True, related_name='cc_messages', to='gmail.contact')),
                ('from_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='gmail.contact')),
                ('to_contacts', models.ManyToManyField(related_name='received_messages', to='gmail.contact')),
            ],
            options={
                'db_table': 'gmail_messages',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_id', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to='gmail_attachments/%Y/%m/%d/')),
                ('is_downloaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_attachments', to='gmail.message')),
            ],
            options={
                'db_table': 'gmail_attachments',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('subject', models.TextField()),
                ('is_starred', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_muted', models.BooleanField(default=False)),
                ('has_unread', models.BooleanField(db_index=True, default=False)),
                ('last_message_date', models.DateTimeField(db_index=True)),
                ('first_message_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_count', models.IntegerField(default=0)),
                ('last_sender_name', models.CharField(blank=True, max_length=255)),
                ('snippet', models.TextField(blank=True)),
                ('account_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='gmail.gmailtoken')),
                ('participants', models.ManyToManyField(related_name='threads', to='gmail.contact')),
            ],
            options={
                'db_table': 'gmail_threads',
                'ordering': ['-last_message_date'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gmail.thread'),
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_emails', models.TextField()),
                ('cc_emails', models.TextField(blank=True)),
                ('bcc_emails', models.TextField(blank=True)),
                ('subject', models.TextField()),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True)),
                ('pending_attachments', models.JSONField(default=list)),
                ('gmail_draft_id', models.CharField(blank=True, max_length=50)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='gmail.gmailtoken')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='gmail.thread')),
            ],
            options={
                'db_table': 'gmail_drafts',
                'ordering': ['-last_saved_at'],
            },
        ),
    ]
