# Generated by Django 5.2.9 on 2026-02-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0002_remove_email_account_link_remove_email_recipients_and_more'),
        ('supply', '0006_alter_rfqvendormapping_gmail_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('account_link', 'label_id')},
        ),
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together={('message', 'attachment_id')},
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['account_link', '-last_message_date'], name='gmail_threa_account_8d1aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['account_link', 'has_unread'], name='gmail_threa_account_b2c32c_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['is_starred', '-last_message_date'], name='gmail_threa_is_star_e8f997_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'date'], name='gmail_messa_thread__e49ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['account_link', '-date'], name='gmail_messa_account_105bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_contact', '-date'], name='gmail_messa_from_co_d38779_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='gmail_messa_is_read_0e0914_idx'),
        ),
    ]
