# Generated by Django 5.2.7 on 2026-01-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown_master_data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityCode',
        ),
    ]
