# Generated by Django 5.2.7 on 2026-02-06 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown_master_data', '0012_replace_closed_with_dispute_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementCategory',
            fields=[
                ('code', models.CharField(help_text='Stable machine-readable identifier (lowercase, underscores)', max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Human-readable display name', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete - set to False instead of deleting')),
                ('display_order', models.IntegerField(default=0, help_text='Sort order for dropdowns (lower = higher priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agreement Category',
                'verbose_name_plural': 'Agreement Categories',
                'db_table': 'dropdown_agreement_categories',
            },
        ),
        migrations.CreateModel(
            name='AgreementType',
            fields=[
                ('code', models.CharField(help_text='Stable machine-readable identifier (lowercase, underscores)', max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Human-readable display name', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete - set to False instead of deleting')),
                ('display_order', models.IntegerField(default=0, help_text='Sort order for dropdowns (lower = higher priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agreement Type',
                'verbose_name_plural': 'Agreement Types',
                'db_table': 'dropdown_agreement_types',
            },
        ),
        migrations.CreateModel(
            name='GSTStatus',
            fields=[
                ('code', models.CharField(help_text='Stable machine-readable identifier (lowercase, underscores)', max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Human-readable display name', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete - set to False instead of deleting')),
                ('display_order', models.IntegerField(default=0, help_text='Sort order for dropdowns (lower = higher priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GST Status',
                'verbose_name_plural': 'GST Statuses',
                'db_table': 'dropdown_gst_statuses',
            },
        ),
    ]
