# Generated by Django 5.2.7 on 2026-02-06 20:03

from django.db import migrations


def populate_adobe_sign_dropdowns(apps, schema_editor):
    """Populate Adobe Sign dropdown tables with initial values"""

    # Get model classes
    AgreementType = apps.get_model('dropdown_master_data', 'AgreementType')
    AgreementCategory = apps.get_model('dropdown_master_data', 'AgreementCategory')
    GSTStatus = apps.get_model('dropdown_master_data', 'GSTStatus')

    # Populate Agreement Types
    agreement_types = [
        {'code': 'client_agreement', 'label': 'Client Agreement', 'display_order': 1},
        {'code': 'sla_agreement', 'label': 'SLA Agreement', 'display_order': 2},
        {'code': 'addendum_client', 'label': 'Addendum-Client', 'display_order': 3},
        {'code': 'addendum_3pl', 'label': 'Addendum-3PL', 'display_order': 4},
    ]

    for item in agreement_types:
        AgreementType.objects.get_or_create(
            code=item['code'],
            defaults={
                'label': item['label'],
                'display_order': item['display_order'],
                'is_active': True
            }
        )

    # Populate Agreement Categories
    agreement_categories = [
        {'code': 'new', 'label': 'New', 'display_order': 1},
        {'code': 'renewal', 'label': 'Renewal', 'display_order': 2},
    ]

    for item in agreement_categories:
        AgreementCategory.objects.get_or_create(
            code=item['code'],
            defaults={
                'label': item['label'],
                'display_order': item['display_order'],
                'is_active': True
            }
        )

    # Populate GST Statuses
    gst_statuses = [
        {'code': 'not_registered', 'label': 'Not Registered', 'display_order': 1},
        {'code': 'registration_pending', 'label': 'Registration Pending', 'display_order': 2},
        {'code': 'registered', 'label': 'Registered', 'display_order': 3},
        {'code': 'na', 'label': 'Not Applicable', 'display_order': 4},
    ]

    for item in gst_statuses:
        GSTStatus.objects.get_or_create(
            code=item['code'],
            defaults={
                'label': item['label'],
                'display_order': item['display_order'],
                'is_active': True
            }
        )


def reverse_populate(apps, schema_editor):
    """Remove populated data if migration is reversed"""
    AgreementType = apps.get_model('dropdown_master_data', 'AgreementType')
    AgreementCategory = apps.get_model('dropdown_master_data', 'AgreementCategory')
    GSTStatus = apps.get_model('dropdown_master_data', 'GSTStatus')

    AgreementType.objects.all().delete()
    AgreementCategory.objects.all().delete()
    GSTStatus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown_master_data', '0013_add_adobe_sign_dropdowns'),
    ]

    operations = [
        migrations.RunPython(populate_adobe_sign_dropdowns, reverse_populate),
    ]
