# Generated by Django 5.2.9 on 2026-02-13 11:41

from django.db import migrations


def seed_warehouse_dropdowns(apps, schema_editor):
    """Populate warehouse-related dropdown tables with business-defined values"""
    WarehouseGrade = apps.get_model('dropdown_master_data', 'WarehouseGrade')
    PropertyType = apps.get_model('dropdown_master_data', 'PropertyType')
    BusinessType = apps.get_model('dropdown_master_data', 'BusinessType')
    SLAStatus = apps.get_model('dropdown_master_data', 'SLAStatus')

    # Seed WarehouseGrade (A, B, C)
    warehouse_grades = [
        {'code': 'A', 'label': 'A', 'display_order': 1, 'is_active': True},
        {'code': 'B', 'label': 'B', 'display_order': 2, 'is_active': True},
        {'code': 'C', 'label': 'C', 'display_order': 3, 'is_active': True},
    ]
    for grade in warehouse_grades:
        WarehouseGrade.objects.get_or_create(code=grade['code'], defaults=grade)

    # Seed PropertyType (In Shed, RCC)
    property_types = [
        {'code': 'IN_SHED', 'label': 'In Shed', 'display_order': 1, 'is_active': True},
        {'code': 'RCC', 'label': 'RCC', 'display_order': 2, 'is_active': True},
    ]
    for pt in property_types:
        PropertyType.objects.get_or_create(code=pt['code'], defaults=pt)

    # Seed BusinessType (B2C, B2B, D2C, Omni)
    business_types = [
        {'code': 'B2C', 'label': 'B2C', 'display_order': 1, 'is_active': True},
        {'code': 'B2B', 'label': 'B2B', 'display_order': 2, 'is_active': True},
        {'code': 'D2C', 'label': 'D2C', 'display_order': 3, 'is_active': True},
        {'code': 'OMNI', 'label': 'Omni', 'display_order': 4, 'is_active': True},
    ]
    for bt in business_types:
        BusinessType.objects.get_or_create(code=bt['code'], defaults=bt)

    # Seed SLAStatus (Active, Inactive, Operation Not Started, Notice Period)
    sla_statuses = [
        {'code': 'ACTIVE', 'label': 'Active', 'display_order': 1, 'is_active': True},
        {'code': 'INACTIVE', 'label': 'Inactive', 'display_order': 2, 'is_active': True},
        {'code': 'OPERATION_NOT_STARTED', 'label': 'Operation Not Started', 'display_order': 3, 'is_active': True},
        {'code': 'NOTICE_PERIOD', 'label': 'Notice Period', 'display_order': 4, 'is_active': True},
    ]
    for status in sla_statuses:
        SLAStatus.objects.get_or_create(code=status['code'], defaults=status)


def reverse_seed(apps, schema_editor):
    """Remove seeded warehouse dropdown values"""
    WarehouseGrade = apps.get_model('dropdown_master_data', 'WarehouseGrade')
    PropertyType = apps.get_model('dropdown_master_data', 'PropertyType')
    BusinessType = apps.get_model('dropdown_master_data', 'BusinessType')
    SLAStatus = apps.get_model('dropdown_master_data', 'SLAStatus')

    # Delete only the values we created (by code)
    WarehouseGrade.objects.filter(code__in=['A', 'B', 'C']).delete()
    PropertyType.objects.filter(code__in=['IN_SHED', 'RCC']).delete()
    BusinessType.objects.filter(code__in=['B2C', 'B2B', 'D2C', 'OMNI']).delete()
    SLAStatus.objects.filter(code__in=['ACTIVE', 'INACTIVE', 'OPERATION_NOT_STARTED', 'NOTICE_PERIOD']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown_master_data', '0014_populate_adobe_sign_dropdowns'),
    ]

    operations = [
        migrations.RunPython(seed_warehouse_dropdowns, reverse_seed),
    ]
