# Generated by Django 5.2.9 on 2026-02-13 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseLogSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, max_length=500)),
                ('encrypted_client_secret', models.TextField(blank=True)),
                ('redirect_uri', models.CharField(blank=True, max_length=500)),
                ('api_version', models.CharField(default='v4', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_log_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense Log Settings',
                'verbose_name_plural': 'Expense Log Settings',
            },
        ),
        migrations.CreateModel(
            name='GoogleSheetsToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_account', models.CharField(max_length=255)),
                ('encrypted_token', models.TextField()),
                ('sheet_id', models.CharField(help_text='Google Sheet ID to sync from', max_length=255)),
                ('sheet_name', models.CharField(default='Sheet1', help_text='Tab name in the sheet', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_sheet_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Sheets Token',
                'verbose_name_plural': 'Google Sheets Tokens',
            },
        ),
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_expense_number', models.CharField(db_index=True, help_text='Unique Expense Number from sheet (e.g., UEN00001)', max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(help_text="From 'Timestamp' column")),
                ('submitted_by', models.CharField(db_index=True, max_length=255)),
                ('email_address', models.CharField(blank=True, max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=500)),
                ('client', models.CharField(blank=True, help_text='Client entity name', max_length=500)),
                ('service_month', models.CharField(blank=True, max_length=50)),
                ('nature_of_expense', models.CharField(blank=True, help_text='Transport/Operation/Stationary/Other', max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('expenses_borne_by', models.CharField(blank=True, max_length=255)),
                ('remark', models.TextField(blank=True)),
                ('approval_status', models.CharField(db_index=True, default='Pending', help_text='Approved/Pending/Rejected', max_length=50)),
                ('raw_data', models.JSONField(default=dict, help_text='Full row from Google Sheets')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expense_log.googlesheetstoken')),
            ],
            options={
                'verbose_name': 'Expense Record',
                'verbose_name_plural': 'Expense Records',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserNameMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(help_text="Name as it appears in 'Submitted By' column", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expense_mappings', to=settings.AUTH_USER_MODEL)),
                ('erp_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense_name_mapping', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Name Mapping',
                'verbose_name_plural': 'User Name Mappings',
            },
        ),
        migrations.AddIndex(
            model_name='googlesheetstoken',
            index=models.Index(fields=['is_active', '-created_at'], name='expense_log_is_acti_7a9019_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='googlesheetstoken',
            unique_together={('email_account', 'sheet_id')},
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['submitted_by', '-timestamp'], name='expense_log_submitt_39ead6_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['approval_status', '-timestamp'], name='expense_log_approva_508147_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['token', '-timestamp'], name='expense_log_token_i_222b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['service_month'], name='expense_log_service_70f3d3_idx'),
        ),
    ]
