# Generated by Django 5.2.9 on 2026-02-14 11:22

from django.db import migrations, models
import json


def convert_string_to_list(apps, schema_editor):
    """Convert existing string sheet_name values to list format"""
    UserNameMapping = apps.get_model('expense_log', 'UserNameMapping')
    db_alias = schema_editor.connection.alias

    for mapping in UserNameMapping.objects.using(db_alias).all():
        # Get the current value as string
        current_value = mapping.sheet_name
        if current_value:
            # Convert string to list and serialize to JSON
            mapping.sheet_name = json.dumps([current_value])
        else:
            mapping.sheet_name = json.dumps([])
        mapping.save()


def convert_list_to_string(apps, schema_editor):
    """Reverse migration: convert list back to string"""
    UserNameMapping = apps.get_model('expense_log', 'UserNameMapping')
    db_alias = schema_editor.connection.alias

    for mapping in UserNameMapping.objects.using(db_alias).all():
        # Parse JSON and convert to string
        try:
            names_list = json.loads(mapping.sheet_name)
            if isinstance(names_list, list) and names_list:
                mapping.sheet_name = names_list[0]  # Take first item
            else:
                mapping.sheet_name = ''
        except (json.JSONDecodeError, TypeError):
            mapping.sheet_name = ''
        mapping.save()


class Migration(migrations.Migration):

    dependencies = [
        ('expense_log', '0001_initial'),
    ]

    operations = [
        # First, change field type to TextField to store JSON temporarily
        migrations.AlterField(
            model_name='usernamemapping',
            name='sheet_name',
            field=models.TextField(default='', help_text="Name as it appears in 'Submitted By' column"),
        ),
        # Run data migration to convert strings to JSON-serialized lists
        migrations.RunPython(convert_string_to_list, convert_list_to_string),
        # Finally, change to JSONField
        migrations.AlterField(
            model_name='usernamemapping',
            name='sheet_name',
            field=models.JSONField(default=list, help_text="List of names as they appear in 'Submitted By' column"),
        ),
    ]
