# Generated by Django 5.2.9 on 2026-02-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_log', '0002_change_sheet_name_to_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='box_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='charges_at_client',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Charges@Client', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='charges_at_gw',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Charges@GW', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='entered_in_tally',
            field=models.BooleanField(default=False, help_text='Entered in Tally status'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='expense_paid_by_operation',
            field=models.CharField(blank=True, help_text='Expense Paid By (Operation)', max_length=255),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='expense_paid_by_other',
            field=models.CharField(blank=True, help_text='Expense Paid By (Other)', max_length=255),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='expense_paid_by_stationary',
            field=models.CharField(blank=True, help_text='Expense Paid By (Stationary)', max_length=255),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='expense_paid_by_transport',
            field=models.CharField(blank=True, help_text='Expense Paid By (Transport)', max_length=255),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='from_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='labour_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='mention_other_operation',
            field=models.TextField(blank=True, help_text='Mention Other OR Remarks (Operation)'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='mention_other_remarks',
            field=models.TextField(blank=True, help_text='Mention Other OR Remarks (Other)'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='mention_other_stationary',
            field=models.TextField(blank=True, help_text='Mention Other OR Remarks (Stationary)'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='mention_other_transport',
            field=models.TextField(blank=True, help_text='Mention Other OR Remarks (Transport)'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='operation',
            field=models.CharField(blank=True, help_text='Operation field from sheet', max_length=500),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='operation_expense_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='operation_expense_type',
            field=models.CharField(blank=True, help_text='Select your Operational Expense Type', max_length=100),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='other',
            field=models.CharField(blank=True, help_text='Other field from sheet', max_length=500),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='other_expense_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='other_expense_type',
            field=models.CharField(blank=True, help_text='Select your Other Expense Type', max_length=100),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='payment_summary_invoice',
            field=models.TextField(blank=True, help_text='Payment Summary (Invoice)'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='pod_hard_copy',
            field=models.CharField(blank=True, help_text='POD Hard Copy', max_length=100),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='stationary',
            field=models.CharField(blank=True, help_text='Stationary field from sheet', max_length=500),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='stationary_expense_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='stationary_expense_type',
            field=models.CharField(blank=True, help_text='Select your Stationary Expense Type', max_length=100),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='to_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='transport',
            field=models.CharField(blank=True, help_text='Transport field from sheet', max_length=500),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='transport_bill',
            field=models.CharField(blank=True, help_text='Transport Bill URL/file', max_length=500),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='transport_type',
            field=models.CharField(blank=True, help_text='Select your Transport Type', max_length=100),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='unloading_box_expense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='upload_invoice_operation_1',
            field=models.CharField(blank=True, help_text='Upload Invoice 1 (Operation)', max_length=500),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='upload_invoice_operation_2',
            field=models.CharField(blank=True, help_text='Upload Invoice 2 (Operation)', max_length=500),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='upload_invoice_other_1',
            field=models.CharField(blank=True, help_text='Upload Invoice 1 (Other)', max_length=500),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='upload_invoice_other_2',
            field=models.CharField(blank=True, help_text='Upload Invoice 2 (Other)', max_length=500),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='upload_invoice_stationary_1',
            field=models.CharField(blank=True, help_text='Upload Invoice 1 (Stationary)', max_length=500),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='upload_invoice_stationary_2',
            field=models.CharField(blank=True, help_text='Upload Invoice 2 (Stationary)', max_length=500),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='upload_invoice_transport_2',
            field=models.CharField(blank=True, help_text='Upload Invoice 2 (Transport)', max_length=500),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='vehicle_no',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='warai_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['nature_of_expense', '-timestamp'], name='expense_log_nature__be0e13_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['client_name', '-timestamp'], name='expense_log_client__253f71_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['vehicle_no'], name='expense_log_vehicle_82ff87_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['transporter_name'], name='expense_log_transpo_f5bb7a_idx'),
        ),
    ]
