# Generated by Django 5.2.9 on 2026-02-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_log', '0003_add_all_expense_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserecord',
            name='operation',
            field=models.TextField(blank=True, help_text='Operation field from sheet'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='other',
            field=models.TextField(blank=True, help_text='Other field from sheet'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='stationary',
            field=models.TextField(blank=True, help_text='Stationary field from sheet'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='transport',
            field=models.TextField(blank=True, help_text='Transport field from sheet'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='transport_bill',
            field=models.TextField(blank=True, help_text='Transport Bill URL/file'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='upload_invoice_operation_1',
            field=models.TextField(blank=True, help_text='Upload Invoice 1 (Operation)'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='upload_invoice_operation_2',
            field=models.TextField(blank=True, help_text='Upload Invoice 2 (Operation)'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='upload_invoice_other_1',
            field=models.TextField(blank=True, help_text='Upload Invoice 1 (Other)'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='upload_invoice_other_2',
            field=models.TextField(blank=True, help_text='Upload Invoice 2 (Other)'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='upload_invoice_stationary_1',
            field=models.TextField(blank=True, help_text='Upload Invoice 1 (Stationary)'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='upload_invoice_stationary_2',
            field=models.TextField(blank=True, help_text='Upload Invoice 2 (Stationary)'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='upload_invoice_transport_2',
            field=models.TextField(blank=True, help_text='Upload Invoice 2 (Transport)'),
        ),
    ]
